### ISSUE TITLE
Not parsing digit-length

### ISSUE THREAD

**Issue by p1r473** [winauth/winauth#199]
Hello, I have an otpauth:// authenticator that ends in &digits=8, however, WinAuth is not parsing this, and is still only showing the 6 out of the 8 digits. Please parse any entered OTP AUTH for the digits parameter and display however many digits are entered.
Example:
otpauth://totp/Example:alice@google.com?secret=JBSWY3DPEHPK3PXP&issuer=Example&digits=8

Also, it is specified to enter the secret code, or a URL to the QR code image, but the same text box that accepts these also accepts the OTP AUTH URL. Might want to mention that.

**Comment by winauth** [comment]
Fixed in version 3.2.1 that will be uploaded soon.

**Comment by p1r473** [comment]
I have tried 3.2.1 and it is still only showing 6 out of 8 digits, in an OTP AUTH url that ends in &digits=8

**Comment by p1r473** [comment]
I have tried 3.2.1 beta. As long as I select add->authenticator, it reads out all 8 digits. 
However, if I add it as add->Google, and enter the OTP Auth URL, it still only reads out the first 6.
But is it working as long as I make sure it is type Authenticator that I am adding.

However, this introduces a new issue. When entering an OTP AUTH URL in the format of:
otpauth://totp/xxxx@xxxx?secret=xxxx
it HAS to be entered in add->Google, because if I enter it in add->Authenticator, it always shows up as 0 for the code. 
But because I have to add it as Google, it has a Google icon, whereas I want to just enter it as a generic Authenticator (with a generic Authenticator icon)

Why can't I enter an OTP Auth Url with format of otpauth://totp/xxxx@xxxx?secret=xxxx as a generic authenticator without it just showing 0 as the code all the time?

Thanks

**Comment by winauth** [comment]
It doesn't make sense to add a custom URL that has 8 digits in the Add->Google authenticator, since Google's implementation is fixed to 6 digits. If you added that same key into their mobile app, you'd only see 6 digits.

So you should be using the generic "Authenticator". I tried it here and it is works, I don't see the 0 codes. Can you send me the URL string you are using - change the secret part if you need to.

**Comment by p1r473** [comment]
Adding the following OTP AUTH URL as an add->Authenticator im 3.2.1 is giving me 0 as my one time code
otpauth://totp/alice@google.com?secret=JBSWY3DPEHPK3PXP
screenshot of error: http://i.imgur.com/9gdRzQ1.jpg

**Comment by p1r473** [comment]
I just realized I had to specify &digits=number in order to get this to work. Sorry, works now. Maybe have a default value of 6 or something. sorry.

**Comment by winauth** [comment]
Ok, I get that too. I'll fix it. Looks like it isn't defaulting the digits properly. You need to add "&digits=6" or "&digits=8" and it works.

**Comment by p1r473** [comment]
This seems to be fixed in 3.2.10 build.
I can now add otpauth://totp/alice@google.com?secret=JBSWY3DPEHPK3PXP in the Add->Authenticator menu and no longer getting a 0 as my code.
