### ISSUE TITLE
Adding a google authenticator HOTP via URL (qrcode) fails

### ISSUE THREAD

**Issue by boschkundendienst** [winauth/winauth#201]
Hi,
we use liboauth in our backend to provide Google-Authenticator compatible HOTP tokens (Google Authenticator supports TOTP and HOTP).

To setup devices we use QR-Codes because with QR-Codes you can provide the token secret AND the current counter.
So when I try to use the following URL:

https://www.google.com/chart?chs=400x400&chld=M|0&cht=qr&chl=otpauth://hotp/S000011%3Fsecret=TF2M6VZ7E666I57VILOI4XV324DMHUXA%26counter=893

which provides a valid QR-Code for the Google Authenticator app this fails with winauth.

"Unable to create the authenticator. The secret code is probably invalid."
"Illegal character: 0"

Even if I download the picture and provide it with a direct url to the png it shows the same error.

What is going wrong here?
I think your application can not handle HOTP token qr-codes with a counter specified.

To be able to specify a counter is essential in my opinion, for example if you want to re-deploy a token without changing the counter on the server side (eg. after a device change).

It would be nice if you could take a look at this.

In general I am missing the options to switch between TOTP and HOTP and also options for the features of both types in your app.

Kind regards

PCFreak

**Comment by winauth** [comment]
You're right, we don't currently support HOTP authenticators in WinAuth. It has been on the todo list for a while, but there hadn't really been a big need to the userbase. My hesitance was really because I didn't want people to use WinAuth as a back for a counter based authenticator, which would obviously then get out of sync with their original.

I'll put it up and see if I can't get it into 3.2.

**Comment by darkfires** [comment]
I could really use this feature.... I setup HOTP with MultiOTP for a large network at work, and initially WinAuth looked like it worked... then it would randomly stop working, and now it's not working at all.  Just found out why... cause it doesn't support it!  Guess we're stuck with google authenticator for now.

Thank you

**Comment by winauth** [comment]
This has been added this the next Beta (3.2.x) that should be uploaded later today. You're welcome to try it, although I'd hang off using in production till it's had some testing.

**Comment by darkfires** [comment]
Thanks for the quick reply.. we'll help you test it out.

**Comment by darkfires** [comment]
3.2.3 Doesn't work at all. :(  

You can scan this QR code  http://techs.ezzi.net/lwhite.png
If I scan the same code in Google Authenticator, works no problem... WinAuth, fails every time.. and i synced the time.

Thanks

**Comment by winauth** [comment]
It wasn't converting the image until you pressed the verify button. If you try 3.2.4 it should do it once you've pasted in the image URL.

**Comment by darkfires** [comment]
It adds ok, but any codes generated by it aren't accepted by MultiOTP at all.. tried many of them.
Google Authenticator works every time though.  Any ideas?

**Comment by winauth** [comment]
Are you adding it into Google Authenticator at the same time or have you had it in there a while? Remember, when using the QR code you are starting your WinAuth authenticator at counter value 30. Whereas if you had been using it in Google already, that count has increased everytime you request a new code. You must start them from the same counter value and cannot run both simultaneously.

Saying that, there is an error where we are showing the last code first rather than the next code. So in your QR, you'll see 648351 once you've added it. But it should be the next one, 395446.

**Comment by darkfires** [comment]
I've tried creating fresh QR codes, never used, add to winauth, try the verify codes, try to generate codes.. each one fails with error 99 (which is usually the code you'd get if you used a QR code for another account)

I take the same QR code (even after using it in winauth and failing 10 times), into google authenticator, works first shot.

**Comment by winauth** [comment]
Are you saying WinAuth has an error, or the system you are using has an error? Can you provide screen shots of WinAuth errors.

If you add them into WinAuth and GA at the same time, they should be the same codes (except from above where WinAuth is one behind, but click the icon once and they will be the same).

You must keep them in sync. But if you click the WinAuth refresh icon to get a new code and the GA to get a new code, you should see the same value. Are you not?

**Comment by darkfires** [comment]
The system I am using is giving an error, the codes WinAuth is giving me do not match up with GA even with several codes worth of offset

**Comment by winauth** [comment]
Can you post another QR code, with the first two codes you see in WinAuth and GA.

**Comment by darkfires** [comment]
http://techs.ezzi.net/lwhite.png

The first ones with spaces are from WinAuth (it was giving me some duplicate codes also), second sets are from GA.
081 467 
827 403
827 403
150 457
150 457
150 457
634 378
634 378

488415
038729
741436
638937
778989
297577
772617

**Comment by winauth** [comment]
I click Add -> Authenticator. Paste "http://techs.ezzi.net/lwhite.png" into the secret code field, which then changes to "otpauth://hotp/lwhite?secret=GLHLGPCKF5ZUURV7W666JMSWW35PII3C&digits=6&counter=30&issuer=CoreITX".

![winauth 201-1](https://cloud.githubusercontent.com/assets/12179488/8238653/fccd0aec-15ab-11e5-908d-04dc81f8915f.png)

I see 019486. Click OK and wait for it to finish. Click the icon, I see 488415.

![winauth 201-2](https://cloud.githubusercontent.com/assets/12179488/8238704/3a2c1b26-15ac-11e5-9124-7d0e80fd3f30.png)

Click again, 038729.

Are you doing anything different?

**Comment by winauth** [comment]
Are you doing Add -> Google Authenticator?

**Comment by darkfires** [comment]
Thank you so much!!! Working now :D

You're awesome.

**Comment by winauth** [comment]
Ok, well, don't get too excited just yet :)

I've noticed it isn't always saving the new counter. So if you close WinAuth without doing something that forces it to rewrite the config (e.g. changing a setting) then it isn't saving the latest counter. Meaning next time you open it, it'll be reset back to 30 or whatever.

I'm fixing this, so wait till the next beta before using it.

Also, I'm going to change Add Authenticator / Add Google Authenticator to be more clear that "Add Google Authenticator" shouldn't be used for a HOTP.

**Comment by darkfires** [comment]
Another bug unrelated to this one.. when typing in the URL sometimes i get an Error before I'm finished typing it.
The remote name could not be resolved: 't'

   at System.Net.HttpWebRequest.GetResponse()
   at WinAuth.AddAuthenticator.secretCodeField_TextChanged(Object sender, EventArgs e)

**Comment by winauth** [comment]
Issues should now be fixed in 3.2.5

**Comment by ramchandra7** [comment]
I have installed WinAuth in my Desk Top PC  and set password, but unfortunately I have for got my password  and unable to use my WinAuth,  It is requested that my  Password may be deactivated so that I can use WinAuth properly.
