### ISSUE TITLE
Problems accessing winauth

### ISSUE THREAD

**Issue by MynameisGlen** [winauth/winauth#202]
I used to use winauth for a few games that I no longer play anymore and completely for got about it but then went to play runescape and wanted to use it to further secure my account. When I open winauth it asks for a password and I cannot do anything with winauth as I don't know the password  and have tried all things I could possibly think it could be. Somebody please help?

**Comment by winauth** [comment]
Your authenticators are encrypted with the password you entered and so there is no way to reset a password. If you have backups of your authenticators secret keys, you could use those to recreate them.

If you can't remember your password, there are some backups stored in the registry. From the run command (Win+R), enter "regedit" and on the left side expand each entry down to Computer\HKEY_CURRENT_USER\Software\WinAuth3\Backup. On the right should be multiple entries (other than Default). Double click each one and copy the contents of the Value data field. Put them in a file and send them over to me at winauth@gmail.com

**Comment by p1r473** [comment]
Are you decrypting them with your PGP secret key, or how do you decrypt the backups on your end?
Is there any way to prevent backups from being made in the registry?
Thanks

**Comment by winauth** [comment]
@p1r473 Please put this into a new issue.

**Comment by yoarib** [comment]
Lord, I need help in the same way.
-----BEGIN PGP MESSAGE-----
Version: BCPG C# v3.5.1.3

hQEMA53DDyNpqwwqAQgArwUdVW9TWtsUP+T7pc2VDEUTMVJcBBMue1J16ZjG9Ge4
pUKnOh9sjbWuPqymNtCpl08jADoE5pS5mn4m+uXIExwMCN9h94i27ecR4NPbHvrV
wC7lZ65vknBSlSXyo7cMXNHcX7zgCnIp1SpO0bGl8/1X+T8QL/rlIMQ5kOeFnINV
yZkdcpeuMtVMz3xNevZZ8vK0ar31a2VbA61m30ox9rMsA3kglBczs0C2iZ7UhEyg
UXq4z9saiwMDMydSUifZfB8tD6g+SKFQaCTfRwThiyU/Pm6mfeomKOo3Cyr2e7MS
iHEG5HcHX/5hTphp1siAM3Fet1Vi6isEtmVtiS+NX9LAwAFW0PM8O74qaMDejoPr
mAPViHyGFZRxBJ02L4LKZEViJ9ywFyoasBU2h+5YLBFfHyJ0w/Ra6JKf4kdpCW0P
qYWOUBgfkaZfpazxdi5FLPiYVyR9cvL3tF4samzXT6TQfBT/Fh6fscd1X2T54poc
RSc9FpDNH/PjkwTKB/xCPCLhYF0FeZ4S93mT/gHCsP0alUWpSWDkgoYBk2Zz/TLI
OISB1yqQwHBtJKp57tolB0GPgu2vXnBQp9IXJeigbuBT7O0g2ef1zeLLi6U6VXZh
bWbU7mN3VyeHyECGCwSZzKoUDxwyZ9TYzJOexrVZTiZAVkFxMVNb4EMgKkgryvqv
YLtMVOGhtyWxzIT9YM/MVmYMeQJ6/tGqTiUyLLGc+u18O8h9IKF3Dpc5HxZ7ynA9
qN6jqhcPcwRg5ryqfh5u/RDsjNkN1y+FVhxUzMLFL0OxTJDWMQ+mUvgz9qf3Z2in
KLqu3r6cHyDmrUlL7vQB3lmQNu/8NqVVxoZE1X9hIhBKww==
=aTir
-----END PGP MESSAGE-----
-----BEGIN PGP MESSAGE-----
Version: BCPG C# v3.5.1.3

hQEMA53DDyNpqwwqAQgAkAW6nrURIxrK0mMEZUJ2IZoO6hh6XcxRg9rOa/ze5gBk
BQk0SyoxonrGMsFZGrpy00xlj9hkk6wwShuZi+3VHwt7Ba95e5bXaMHqAwZvt1Gv
p4/NQcmHtdvviPx7gO+tBNpgfRKCAvQXAlf8tclim5WM08vkXNIg7b53G2IVye+t
yHl6bNULvQDAWhO5bjMG4t0uz0LKzjWt3PFNy8QebI1AGek3HyTtHhN21aD9U6Xw
98U65OU29ALIohB2AvPJW55lYpZbDjCheaeRZJT2hqKwhblvojNjfU0QiEEDrgcQ
9Md7sHPdLvBPAb3q5zs1wxGLirybdBsSt1jJbjm0MtLAuQFVEKoJGX7cVZS+ygtI
IkezTf3U8BVlpx4x5US2Sr/AZK28aZem5ttF/+3zsDUDslm8Or/WMr5IHQhgsrzv
ToTkSJi3kEeQ1zYVuAOF3X86mJ2ZjmhbT7fj3XB3idh37LXEJRsADKkfqw7jbjQ3
OMQZwqmp0HSd68igurhzCf8uQxg5pm77ye6YjdGLXYVROlmxDEyq9UkaCc9kSXbR
1cB2SWPZc6tOOjarANjfH+qzDq1X++3M8UmNrxW1vww+SJeEkCIgOfFHs647htCm
HKawFofgFEpMH2pGX8dEaba8Zb13/inLLMfHH8x3pTD76XdUErDcYvKK9ET0P2dc
5BEHFcJr9vEpdTAQiYqaRbbt7iMx1MiL8uz5mz7H5vcAw6/ZC6QeNgZCMlGyoPgN
Wn17mjYbZx0bvBjX5OwFRio6VgUCPTkNDkiUwXtkV5vsg3M84ZBvR8mf8nfqqTvT
k7p8GG2dmPjXypMUqey3JTgtyc2DPGoDZqow
=Z9WE
-----END PGP MESSAGE-----
