### ISSUE TITLE
WinAuth didn't save my authenticator information....

### ISSUE THREAD

**Issue by plasmageek** [winauth/winauth#203]
So I heard about this program from guildies; I loaded it up Thursday before vacation, set it up for my Wildstar account, and thought all was fine. I didn't get a chance to log in today, it asked for my authenticator information, and on loading up WinAuth it did not have any authenticator information...I start prowling the web, go to my Appdata->Roaming->WinAuth, and there's the .xml, saved for June 11, with nothing of use in it.... So while it created the file, it didn't save anything else....

Needless to say, I won't be trusting this program again anytime soon, but I wanted to let you know.

I"m using Windows 7, x64 bit.

**Comment by winauth** [comment]
Are you logged in as the same user as you ran WinAuth before?

Did you definitely click OK to the dialog when you created it that first showed the code, or just saw the code and left it?

Run "regedit" and go to "HKEY_CURRENT_USER\Software\WinAuth3\Backup". ON the right there should be at least one line (other than "Default"). Double-click it and post the contents of Value data.

**Comment by plasmageek** [comment]
I am logged in as the same person, I do believe I completed all the necessary steps. In 'regedit' under WithAuth\ I have:
Default
LastUpdateCheck
LatestVersion
UpdateCheckFrequency

There is no WinAuth3\Backup folder?

**Comment by winauth** [comment]
Another possibility is that you put a winauth.xml file in the same folder as the exe file, in which case it would write to that one.

However, it writes the entry into that Backup part of the registry as soon as OK is clicked. That has to happen before the code is displayed in the main window. The only things I can think of are, for some reason WinAuth is being blocked from creating the key in the registry (but that should show an error - you can check by creating a new authenticator), you've done a system restore, or never clicked the OK button.

Unfortunately that backup is the last resort and the key was never saved. You will need to contact Carbine and have it removed.
