### ISSUE TITLE
Steam exporting OTP URLs in wrong format

### ISSUE THREAD

**Issue by p1r473** [winauth/winauth#204]
Hi, when you export a Steam key that was created in WinAuth, it gets exported in the format
otpauth://totp/Steam?secret=XXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXX&digits=5
however, when reimporting this exported key, it now shows up as only numbers.
The proper format is
otpauth://totp/Steam:username?secret=XXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXX&issuer=Steam
I think when you are exporting the steam key you are not appending Issuer=Steam to the end (nor the username, which I guess isn't mandatory but might be nice to have) which is important if you want to re-import, so when you export then reimport, it does not recognize it as a Steam code.

As well, currently, you must add &digits=5 on the end, due to issue 199, so I go to add->authenticators, and type
otpauth://totp/Steam:username?secret=XXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXX&issuer=Steam&digits=5
BUT I get the error 
Index and length must refer to a location within the string
Parameter name: length
Going to add->import works fine for adding a Steam key, but add->authenticator doesn't (seems like 5 isnt a valid number of digits for adding an authenticator... must be failing a sanity check where you check if digits == 6 or 8)

**Comment by winauth** [comment]
Good catch. Will look at it.

**Comment by p1r473** [comment]
Here is more details about this error
![image](https://cloud.githubusercontent.com/assets/9235633/9664315/f942e208-5236-11e5-9ab2-dce2be049d5f.png)

**Comment by p1r473** [comment]
It seems you are now correctly exporting Steam with &issuer=Steam&digits=5 on the end. That's great.
Still can't Add->Authenticator and give is the Steam OTPAuth of 
otpauth://totp/Steam:username?secret=XXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXX&issuer=Steam&digits=5
so that still should be fixed.

**Comment by winauth** [comment]
Fixed in 3.2.12

**Comment by p1r473** [comment]
Agreed, seems to be fixed.
