### ISSUE TITLE
I Need Urgent Help 

### ISSUE THREAD

**Issue by surinya** [winauth/winauth#208]
Hi friends. 

My name is Marco Lara, I use winauth for Paidverts but I reinstall Windows and forget to back winauth data, now I cannot login in the web of paidvert and dont want to lose today BAP´s.

Please tell me how to do

**Comment by winauth** [comment]
I'm not sure what you think I can do.

You need to recreate the authenticators from copies of the secret keys when you created them. If you don't have those or any backups, you'll need to contact the services that use them and request they get reset.

**Comment by surinya** [comment]
ok, thanks


2015-06-24 14:33 GMT-05:00 WinAuth <notifications@github.com>:

> I'm not sure what you think I can do.
>
> You need to recreate the authenticators from copies of the secret keys
> when you created them. If you don't have those or any backups, you'll need
> to contact the services that use them and request they get reset.
>
> —
> Reply to this email directly or view it on GitHub
> <https://github.com/winauth/winauth/issues/208#issuecomment-114988492>.
>



-- 
Marco Antonio Lara Torres
3012446203
