### ISSUE TITLE
should i uninstall curent version of winauth & install the new one from where will i get security key i=or is it the same one which is available in my data registry

### ISSUE THREAD

**Issue by jirochani** [winauth/winauth#210]
should i uninstall current version of winauth & install the new one from where will i get security key or is it the same one which is available in my data registry

Kindly reply me mmediately

**Comment by winauth** [comment]
No, you don't to uninstall.

You need to find and replace the file called "winauth.xml". This is normally in "c:\users\<username>\AppData\Roaming\WinAuth".
