### ISSUE TITLE
how many time should i tell you my current is winauth.exe not winauth.xml are these both versions the same reply me immediately

### ISSUE THREAD

**Issue by jirochani** [winauth/winauth#211]
how many time should i tell you my current is winauth.exe not winauth.xml are these both versions the same reply me immediately

**Comment by winauth** [comment]
I don't understand what you mean.

I realise English is not your first language, but unfortunately I do not understand your issue.

Can you contact someone else who is more familiar with computers to help resolve the issue.

Maybe you also should just contact the service that you use the authenticator and have them remove it from your account.

**Comment by winauth** [comment]
If you still want me to remote into your machine and fix it, we need to set up a time. I am in PDT (GMT-7) timezone, and can do it 1000 PDT - 2200 PDT (1800 GMT - 0400 GMT).
