### ISSUE TITLE
Annoying way to copy code

### ISSUE THREAD

**Issue by makedir** [winauth/winauth#215]
Please give option to display the code as a text field/area which you can double click on and copy from via ctrl+c for example. It is totally annoying to right click and go to copy code via mouse.

**Comment by Stanzilla** [comment]
Won't happen because of security concerns, see https://github.com/winauth/winauth/issues/115

**Comment by makedir** [comment]
Then give option for bind left click in item = copy to clipboard ...

**Comment by winauth** [comment]
There are also some shortcuts ways. You can turn on "copy on new code" and then when you click the circular refresh icon, the code will be displayed and also copied. You could also set up a shortcut key to copy an individual authenticator.
