### ISSUE TITLE
Password Reset

### ISSUE THREAD

**Issue by kdj422** [winauth/winauth#217]
I understand that there is no "password reset" for the windows authenticator, but I need to reset my password, as I don't remember it.

**Comment by cdmackie** [comment]
If you are using the same machine that you created it, there is an
encrypted backup.

- Click the start menu, choose "Run..." and enter "regedit" and click OK.
If you have no "Run..." option, enter "regedit" into the search box and
then select the program that appears.
- Click and open each of the following:
- "HKEY_CURRENT_USER"
- "Software"
- "WinAuth3"
- "Backup"
- For each line over on the right side, double click it, and copy the
contents of the Value data field. It looks like "---- BEGIN PGP MESSAGE...."
- Copy those and put into an email and send them over

**Comment by kdj422** [comment]
To whom do I send the codes to? Other requests for password resets were
answered directly by WinAuth, I just want to ensure I'm sending my
information to the correct location.

**Comment by cdmackie** [comment]
winauth@gmail.com

**Comment by winauth** [comment]
Sorry for confusing.  I replied on my personal account. Send to winauth@gmail.com.

**Comment by winauth** [comment]
Resolved over email.
