### ISSUE TITLE
Forgot Winauth pw

### ISSUE THREAD

**Issue by Kodo55** [winauth/winauth#218]
Hi i forgot my Winauth pw what can i do? :D

**Comment by winauth** [comment]
The data is encrypted with your password, so it cannot be recovered.

There are backups saved on your machine just for this purpose.

Run "regedit" and go to "HKEY_CURRENT_USER\Software\WinAuth3\Backup". On the right there should be at least one line (other than "Default"). Double-click it and post the contents of the Value data.
