### ISSUE TITLE
Can't send error report: bad gateway

### ISSUE THREAD

**Issue by p1r473** [winauth/winauth#219]
Hello, not a very important bug, but I thought I'd report it nonetheless: when trying to send an error report, I'm getting a bad gateway error. 
![image](https://cloud.githubusercontent.com/assets/9235633/9664125/059aa488-5236-11e5-9cff-77c5208030e6.png)
I've turned off my firewall, disabled PeerBlock, disabled my hosts file, so I think, but not 100% sure if its on my end.

**Comment by winauth** [comment]
Server wasn't accepting requests.
