### ISSUE TITLE
Exporting and encoding

### ISSUE THREAD

**Issue by p1r473** [winauth/winauth#220]
Hello, funny little bug here
Giving WinAuth the OTPAuth URL of:
otpauth://totp/Example:alice@google.com?secret=JBSWY3DPEHPK3PXP&issuer=Example
And then exporting, it gets encoded funny, as:
otpauth://totp/Example+(Example%3aalice%40google.com)?secret=JBSWY3DPEHPK3PXP&digits=6&icon=WinAuth
When you go to re-add it, you have to rename it now, or else the name is Example+(Example%3aalice%40google.com)
![image](https://cloud.githubusercontent.com/assets/9235633/9664535/88051974-5238-11e5-887d-9ea9b1817935.png)
In this next photograph, the FIRST key is the original key, and the SECOND key is the imported one. You can see how this new funny name looks, if not renamed (when you import, you can't rename, so you have to rename it in the export itself)
![image](https://cloud.githubusercontent.com/assets/9235633/9664559/af81c236-5238-11e5-8a29-2b39f107f15b.png)

**Comment by winauth** [comment]
Should be fixed in 3.2.12

**Comment by p1r473** [comment]
Much better now. Still encodes the @ as %40 though (as seen below), but that's not much of an issue
If you don't want to change that behaviour then feel free to close this issue now, the actual bug is fixed

New encoded OTP Auth URL:
otpauth://totp/Example:alice%40google.com?secret=JBSWY3DPEHPK3PXP&digits=6&issuer=Example&icon=WinAuth

**Comment by winauth** [comment]
Going to close. The %40 is valid and can be used because it is a URL, and it is all being encoded in case there were other chars that needed encoding.
