### ISSUE TITLE
Invisible code generated

### ISSUE THREAD

**Issue by p1r473** [winauth/winauth#222]
When going to Add->Authenticator or Add->Google and adding
otpauth://totp/Example:alice@google.com?secret=JBSWY3DPEHPK3PXP&issuer=Example
And then clicking verify code, the code text is now invisible
Tested in 3.2.12
Screenshot:
![image](https://cloud.githubusercontent.com/assets/9235633/9753224/dab72eac-5687-11e5-8999-9fc17317045e.png)

**Comment by winauth** [comment]
Thanks. I saw that before pushing out the last version, and thought I'd fixed it. Apparently not quite. It's in 3.2.13.

**Comment by p1r473** [comment]
Yep, looks good in 3.2.13
