### ISSUE TITLE
Major Issue

### ISSUE THREAD

**Issue by randydrew6** [winauth/winauth#225]
Yesterday my computer would not get past the login to get to the desktop, said my password expired even though I didnt set one. And it threw an error every time I tried to set a password. So I reinstalled windows hoping that would save it, after I opened notepad from the cmd prompt and transfered over some files.
Reinstalling windows now gives me a critical error with usbhub.sys and wont even start. I am able to get into cmd prompt again and navigate to my windows.old folder and got the xml file for winauth but it says the password is invalid if I try using that file.

How can I get winauth to work with everything saved from my previous computer? I have a lot of really important keys on this auth.

**Comment by winauth** [comment]
Did you use "Encrypt to only be useable on this computer"? If so, it is locked to that instance of Windows. Unless you have your Windows password reset disk, there is going to be no way to recover it from there.

The quickest option is to recreate your authenticators from the backups of each of their secret keys, or restore from a backup you made in Winauth.

If you didn't make any backups, you will need to open your old registry and pull them from there. Find the ntuser.dat file in your old users folder and open it in regedit. Expand down to HKEY_CURRENT_USER\Software\WinAuth3\Backup and copy out each entry.

**Comment by randydrew6** [comment]
I dont know if I did or not, I just ran it and added the auths, a lot of the time I didn't even extract it. How can I get the backups? the only program I can open on there is notepad from cmd prompt. That's how im getting the files transfered.
I went to regedit from cmd prompt and WinAuth3 isn't in there, perhaps because I tried to do a fresh install. Is there no way I can get these back? I need them very badly.

**Comment by winauth** [comment]
If you have backups of the secret keys for each authenticator you originally added, just create new ones and enter those keys again.

If you don't, can you get the file "\Users\<username>\ntuser.dat" from your old Windows installation.

**Comment by randydrew6** [comment]
What do I do with ntuser.dat?

**Comment by winauth** [comment]
Run regedit in your new Windows.
Click on HKEY_LOCAL_MACHINE
Do File -> Load Hive... and select the old ntuser.dat
Give it a name, anything.
Now Inside HKEY_LOCAL_MACHINE is that name, click the arrow next to it to expand it.
Keep going down to Software\WinAuth3\Backup
Double-click each entry on the right and post it.

**Comment by randydrew6** [comment]
Just tried, it's not there. Don't think there is a backup :(

**Comment by randydrew6** [comment]
by it I mean Software\WinAuth3\

**Comment by winauth** [comment]
There only wouldn't be if either you were running in portable mode (were you?) or if you haven't opened the right ntuser.dat file, i.e. not the one for your last Windows installation.
