### ISSUE TITLE
Lost password

### ISSUE THREAD

**Issue by asrapmoc** [winauth/winauth#227]
I used WinAuth to log in easier and faster Guild Wars 2, without using any password. Now I'm trying to play GW2 but WinAuth is requesting a password. I tried looking for it in roaming/WinAuth but it's encrypted. What should I do to get that password? Thanks.

**Comment by winauth** [comment]
When you looked at the xml file, it has some encrypted data looking like:

<config encrypted="abc">...

Or

<data encrypted="abc".....

What do you have for encrypted="abc" ?
