### ISSUE TITLE
Forgot my Password

### ISSUE THREAD

**Issue by Peppalightning** [winauth/winauth#229]
i have lost my password and i chose to encrypt so can not get it from Roaming. i used winauth for Guild Wars 2 and now am trying for Wildstar. Is there anyway to get my passward back?

**Comment by winauth** [comment]
> i chose to encrypt so can not get it from Roaming

Do you mean that you used portable mode?

Anyway, can you follow these steps and we'll see if we can recover the backups from your registry

1. Run regedit
2. Open HKEY_CURRENT_USER and then Software\WinAuth3\Backup
3. Double-click each entry on the right and copy the value
4. Put in an email and send them to me along with your winauth.xml config file (either from the folder where you run winauth or from \Users\<username>\AppData\Roaming\WInAuth\winauth.xml)

**Comment by winauth** [comment]
Send to winauth@gmail.com
