### ISSUE TITLE
New Steam trade confirmation after October 22nd

### ISSUE THREAD

**Issue by LucaBerneking** [winauth/winauth#232]
At the moment the Steam feature in WinAuth works fine for me.

I noticed the following message from Steam while trading:

Note: After October 22nd, accounts with a Steam Guard Mobile Authenticator will only ba able to complete this verification step from the Steam Mobile app.

Will my Steam-Authenticator in WinAuth still works for trading after 22nd or should I remove it before the 22nd?

**Comment by winauth** [comment]
I think this just means that you will not be able to use a non-SteamGuarded account for trading, i.e. you can't use the email only confirmation code. You must have an authenticator on your account.

In any case, make sure you have a copy of your revocation code saved in case you ever need to remove it from WinAuth - which you can always do from the windows/mac Steam client app.

**Comment by Toff-kun** [comment]
Here's the actual text that appears when trying to complete the trade with Steam Mobile Authenticator enabled (through WinAuth):

![sshot-265](https://cloud.githubusercontent.com/assets/10385850/11410637/ad73bed8-93d1-11e5-8f31-2932049a7637.png)

This happens even if the "Confirmations of Community Market actions" option in the profile settings is set to disabled. So looks like it's impossible to use WinAuth for Steam trading as of now.

**Comment by winauth** [comment]
Thanks for checking and pointing that out. WinAuth isn't intended to be a replacement for the Steam mobile app, just the SteamGuard part, but this answers a question that I've seen asked, if a trade only needed SteamGuard or the app as well.

**Comment by Toff-kun** [comment]
Seeing how there is no way to disable trade confirmations even in the app itself when the Mobile Authenticator is enabled, it would be great if Winauth could support those trade confirmations. The demand seems to be really high now that Valve basically forces everyone to enable Mobile Authenticator (and keep it enabled for 7 days) to keep the ability to trade without restrictions.
But whether it's coming or not, thank you for such a nice program!
