### ISSUE TITLE
Unable to resize the window

### ISSUE THREAD

**Issue by bourdin07** [winauth/winauth#234]
Winauth is not suitable for small screen such as Tablet (Surface Pro), the window is too high when there's a lot code.

**Comment by winauth** [comment]
It is supposed to not extend outside the window, but add a scrollbar. Can you please include a screen shot.

Are you able to get to the cog icon to open the options menu? If so, can you turn Auto Size on. Does it make it fit. If it was on, can you turn it off so you can resize manually?
