### ISSUE TITLE
Steam no longer requires a secondary mail code

### ISSUE THREAD

**Issue by ardaozkal** [winauth/winauth#236]
or does it?

I tested with phone and it didn't require a secondary mail code, but when I tried winauth, no mail ever arrived, hence I wasn't able to add it to winauth.

**Comment by Jaex** [comment]
I couldn't complete Steam authentication too because WinAuth asks for activation code but I didn't receive email for it.

**Comment by winauth** [comment]
I just went through the process. First time, I didn't get a code, but next time I did. Not sure if Steam is not sending out emails at moment. I'll investigate more.

**Comment by ksarnelli** [comment]
Same issue here - I receive the login email but not the activation email.  Tried several times, maybe Steam changed the process?

**Comment by winauth** [comment]
> maybe Steam changed the process
Not as far as I can tell, although it's undocumented anyway.
I'll put out a diagnostic version, hopefully tomorrow, which will help see what is being passed back and forth between us and Steam. Right now we are only supposed to ask for the code if Steam told us there needs to be an email verification. Perhaps they are always saying that.

When I checked this over the weekend, my first attempt didn't send a code, but the next did. So not sure where/why it's failing yet.

**Comment by winauth** [comment]
Can you download https://winauth.com/downloads/3.x/WinAuth-3.3.2.zip

This is just a debug and diagnostic version of 3.3.1

Try and add a Steam Authenticator, to the point where you are asked for the code but don't receive it.

You should see a file called winauth.log in the same folder as winauth.exe. If it's not there, there may be a permissions problem creating the file, so move winauth.exe somewhere else and try again.

Please send the winauth.log to me at winauth@gmail.com.

**Comment by MilkGames** [comment]
same issue ;(

**Comment by ksarnelli** [comment]
Just sent over my log.

**Comment by winauth** [comment]
Thanks for the logs.

Pretty much looks like Steam disabled creating authenticators by email validation. The new version of their mobile app doesn't allow it, as presumably they also switched it off on the backend.

So it looks like you must have a SMS-capable phone number attached to your Steam account, which will be sent the activate code instead.

I've made some changes and got it to register a new authenticator, I will push up a new test version shortly that uses this method instead. If it works for people here, I'll roll it out.

**Comment by winauth** [comment]
Here is a new version that uses the new Steam SMS activation method.

Please consider it a Beta, so make a backup/export of your authenticators. If you are adding an authenticator to your Steam account, make sure you copy down the "revocation code" RXXXXX so you can remove it if anything goes wrong.

First, you MUST add an SMS-capable phone to your Steam account. You can do this through the Steam client or logging in to your account from their website. Adding the number will cause an SMS to be sent to your phone, which you will enter to confirm the phone.

Now download https://winauth.com/downloads/3.x/WinAuth-3.3.2.2.zip

Add a Steam authenticator. You should get the "new device" email as normal, but then the "Confirmation code" will be sent by SMS to your phone.

Please post results and/or feedback.

**Comment by doplank** [comment]
WInAuth 3.3.2.2 is working perfect. I got SMS code to my WP, enter the code, now I have Steam Guard Authenticator activated

**Comment by ardaozkal** [comment]
Will try and probably close out the issue, sec.

**Comment by ardaozkal** [comment]
Works now, thanks. https://gyazo.com/b0df7de1ae2904a3541781bd549052e4

**Comment by ardaozkal** [comment]
@winauth the 3.3.5 version on the website ( https://winauth.com/download/ ) still uses the old method, not the SMS.

**Comment by ardaozkal** [comment]
Oops, that is mail login, sorry.

**Comment by giddymuched** [comment]
I don't use sms text.  I have no friends with sms text.  

Why build atop sms texting?

**Comment by ardaozkal** [comment]
use google voice
