### ISSUE TITLE
Didn't receive Activation Code to my e-mail

### ISSUE THREAD

**Issue by doplank** [winauth/winauth#238]
I was trying to use WinAuth for Steam for the first time, login, get to code via e-mail and next, I receive and write down my Revocation Code. The next thing is I should receive Activation Code in my inbox, but didn't get for over 1 hour. My email is doplank@live.com, is WithAuth send a code to the wrong e-mail address?

Thank you

**Comment by winauth** [comment]
WinAuth doesn't send out the emails, Steam does. It sends them to your registered email address.

> but didn't get for over 1 hour

Are you saying you got it an hour later, or still haven't received one?

Can you try again.

**Comment by doplank** [comment]
Still haven't receive one e-mail yet. I was wait and checking Inbox and Spam, still none of them.

**Comment by winauth** [comment]
Can you try something. Try again, bit use the wrong password till you get the captcha. Then enter it and your correct password.

**Comment by doplank** [comment]
I already did what you said, but still haven't receive my Activation Code. Maybe Steam server goes wrong or something?

**Comment by winauth** [comment]
Are you able to do anything to force it to think you are on a different machine, e.g. connect to a VPN< you a computer somewhere else? Trying to see if it's your account or just the process.

**Comment by winauth** [comment]
Can you download https://winauth.com/downloads/3.x/WinAuth-3.3.2.zip

This is just a debug and diagnostic version of 3.3.1

Try and add a Steam Authenticator, to the point where you are asked for the code but don't receive it.

You should see a file called winauth.log in the same folder as winauth.exe. If it's not there, there may be a permissions problem creating the file, so move winauth.exe somewhere else and try again.

Please send the winauth.log to me at winauth@gmail.com.

**Comment by doplank** [comment]
Here's the log

https://www.dropbox.com/s/9k7zmh0q0nacwsi/winauth.zip?dl=0

**Comment by winauth** [comment]
Thanks. I looked through your log. So during this you didn't get an email? It looks like the authenticator was set up, so I'm just checking what happened.

**Comment by MilkGames** [comment]
same issue. Can you please make a beta build where the whole activation code is removed?

**Comment by winauth** [comment]
I don't think it will help. While we actually receive the new authenticator secret, their activation email has been disabled/removed.

It looks like the problem is that Steam have disabled the ability to set up a new authenticator via email alone. It has to be done by adding a phone onto the account and is now started via an SMS code.

If this is true, then I need to change the implementation.

**Comment by winauth** [comment]
Please see https://github.com/winauth/winauth/issues/236
