### ISSUE TITLE
"Restore" steam authenticator

### ISSUE THREAD

**Issue by dhoepelman** [winauth/winauth#240]
Hi,

I had the same email problems as some of the others here, so added a mobile authenticator through the steam app.
Can I now add this authenticator to winauth, similar to how you can "restore" Battle.Net authenticator using the recovery code?

**Comment by winauth** [comment]
Yes and no. There is no recovery code like Battle.net, only one to remove it from your account. But if your phone is rooted you can access the data where the key is stored and enter it into WinAuth.

If you can run the diagnostic version I posted, https://winauth.com/downloads/3.x/WinAuth-3.3.2.zip, it will help me track down the problem.

Try and add a Steam Authenticator, to the point where you are asked for the code but don't receive it.

You should see a file called winauth.log in the same folder as winauth.exe. If it's not there, there may be a permissions problem creating the file, so move winauth.exe somewhere else and try again.

**Comment by dhoepelman** [comment]
Ah that's a shame. And since winauth gives an error about an already attached authenticator I presume Steam doesn't support multiple authenticators.
I'll keep it in mind should I decide to root my phone.

Problem with email not receiving persists, [log](https://www.dropbox.com/s/mrbpxa9t72h2fup/winauth.log?dl=1) (please notify when you have downloaded it, so I can remove it as it contains the steam username).

**Comment by winauth** [comment]
Thanks, I've download the log. Just to confirm, when you did this you didn't get the email sent to you?

**Comment by dhoepelman** [comment]
Nope, not in my spam box either. Did get the "normal" steam guard code but no "activation" code for the authenticator (steam guard code didn't work)

**Comment by winauth** [comment]
Please see https://github.com/winauth/winauth/issues/236
