### ISSUE TITLE
It is not portable.

### ISSUE THREAD

**Issue by 0rkaM** [winauth/winauth#241]
The very reason that it depends on .NET makes it not portable.
A portable program does not rely (too much) on external features, libraries, etc. that are not standard or available on all version of the underlying OS.
.NET is not available on most, if not all, Internet Café machines and all public computers at libraries and schools and it cannot be installed unless someone has admin rights, which the regular user does not have; so this program cannot run on any of those machine which is where a "portable" program is made for and should run.

**Comment by 0rkaM** [comment]
... and the reason you are closing this is??
Did you fix it, by either not stating that is portable, or making it not dependent to .NET?
Or even by explaining how to run it portable... like from a USB memory stick.
Anything?

**Comment by winauth** [comment]
It is portable within the system requirements, which include .Net. The current version will always have that requirement.

This issue is just semantics and at best a feature request.
