### ISSUE TITLE
Could not compile 3.3.3 version

### ISSUE THREAD

**Issue by heretic13** [winauth/winauth#242]
I'm trying to build WinAuth myself because I trust KIS.
I downloaded the source code. I cannot building.

1. The set of compilation errors.
2. Not found several resource files.
3. Not found projects testing Yubikey.
4. I did not find the file .gitignore.

It looks very sad.

**Comment by winauth** [comment]
Which version of Visual Studio are you using?

**Comment by heretic13** [comment]
VS 2015.
