### ISSUE TITLE
Alert virus

### ISSUE THREAD

**Issue by keyk** [winauth/winauth#243]
When I unzip the zip my antivirus alerts with this virus Trojan.Win32.Bublik.dysp 
please solve it

**Comment by heretic13** [comment]
I have the same. And I can not build a program from source - there are errors. Vicious cycle.

**Comment by winauth** [comment]
This has been confirmed as a false positive by Kasperksy, and was supposed to be fixed in their latest update. In fact, it was, but apparently has been reintroduced today. I have contacted them to get them to check it again.

**Comment by weepilotd** [comment]
Same here.

**Comment by winauth** [comment]
Kasperksy has issued another update with a new fix for this false positive.
