### ISSUE TITLE
Empty phantom window visible when using windows 10 virtual desktops

### ISSUE THREAD

**Issue by eXtreme** [winauth/winauth#245]
If you open WinAuth and you have WinAuth window visible on your screen, then you switch to another Windows 10 virtual desktop there is a copy of WinAuth window, in the same exact position but with empty content. See the screenshot:

![image](https://cloud.githubusercontent.com/assets/197671/11333971/03359370-91d2-11e5-8314-9cbbcd50a89a.png)

The window on the initial screen is completely fine and works ok, it's just this phantom visible on every virtual desktop. 

And then, if you move that phantom window on other desktop you get this phantom window also on the main screen, like it came from underneath the main window, see:

![image](https://cloud.githubusercontent.com/assets/197671/11334103/06ebe630-91d3-11e5-8d07-8774bc16a6d1.png)

If you close WinAuth and reopen it, the phantom is still there, it disappears when you move the window (but is still visible on other desktops).

**Comment by winauth** [comment]
Thanks, I've seen this, but not consistently before. I'll look at it again.
