### ISSUE TITLE
shared secret hasn't been shown?

### ISSUE THREAD

**Issue by autaut03** [winauth/winauth#246]
Hi. I've got some code to generate steam `twofactorcode` code that I send on each login request. But the function requires some 'shared secret', and I cant find it. The only thing steam's given to me is the code like `R33333`. So where should I get it? I know this is wrong category, but it's the only way to get some really USEFUL information. Thank a lot.

**Comment by winauth** [comment]
If you used WinAuth to add SteamGuard, then running WinAuth shows a 5 character code like "G6H5R" that you use when logging in.

The R33333 code is the "recovery code", used to remove an authenticator from your account if you no longer have access to it (e.g. lost phone). You can do that from within the Steam client.
