### ISSUE TITLE
I cant add more than one steam account

### ISSUE THREAD

**Issue by v3rg** [winauth/winauth#247]
When I try to add my second account and enter confirmation code from email I get this error
Invalid responce from Steam 
resonce
status 84

**Comment by v3rg** [comment]
A little update. This seems to be a steam-side problem with mobile number linking.

**Comment by winauth** [comment]
Thanks for updating. Were you using the same phone number or something?

**Comment by v3rg** [comment]
Yeah. I wanted to link all of my accounts but I've only managed to link two of them. Contacted steam support for the issue.
