### ISSUE TITLE
again shared secret

### ISSUE THREAD

**Issue by autaut03** [winauth/winauth#248]
Hi. U closed my last issue, but I didnt mean that. I mean that I'm developing a programm, that uses steam login, and it needs twofactorcode argument. So to generate it - I need to know the shared secret field, but it's only given on response of FinalizeAuth.blablabla. request. Where can I get it fully decoded and plain? I searched for it in %appdata%/winauth/.xml, but there's only encoded 'secretdata' field. Also I tried to dump this field, and I've got an array of byte. So now I hope u'll help me, thx.

**Comment by winauth** [comment]
I closed it but feel free to discuss it.

The easiest way to get the secret it to do an Export (from the cog options button) as plain text. It will create a file in KeyUri format with the secret encoded in Base32.

**Comment by autaut03** [comment]
About first topic - I didn't know, sorry.

Base32 decoding doesn't really work - online decoders show that it's not UTF-8 string and my test project can't decode it too. But I've already dumped it, using your decode functions. Your app is very helpful and I'm very thanful to u for making it open-source.

**Comment by winauth** [comment]
Glad you got it. That error is probably because the decoder is not using the standard RFC 3548 Base32 encoding, as there are different implementations. You can try http://tomeko.net/online_tools/base32.php?lang=en.
