### ISSUE TITLE
Lost Information

### ISSUE THREAD

**Issue by Den241991** [winauth/winauth#249]
Hi, I have used this tool/program for a long time & it worked great, until today.
I logged into the program to find that all my game-list is empty (totally blank) & the .xml file is also blank.. yet i have done nothing to the program or its files other than run them as admin.

whats going on? 
have i lost them for good? i had more than 20 games on the list, if i have lost them for good.. i cant even get on to some of the sites to say i have lost the info :( and if i have to start adding them again then it would take ages :(.

**Comment by winauth** [comment]
That's not good. Do you have anything that might have affected writing to the files, any warning in AV/Malware software? Run our of disk space? Do you have errors in Windows error log? Is it in a folder that is synced to cloud somewhere, e.g. Google drive?

Do you have versioning or shadow copies of the xml file? If so, maybe you can recover an older copy.

Did you make any backups or exports? Exports can be imported using the Add button.

Do you have the secret keys written down? If so, you can add them again.

Lastly, if you are on the machine where you created them, we can recover the authenticators from your registry. 

1. Run regedit.exe (click Start then “Run…” and enter “regedit”. If you do not have the “Run..” option visible, use the search field and find “regedit”).
2. Click the small arrow to the left of HKEY_CURRENT_USER so it expands
3. Do the same for: Software and WinAuth3
4. Click on Backup under WinAuth3.
5. On the right should be list of items. Double-click each one and copy the value of the ‘Value data’ field. It starts with “—–BEGIN PGP MESSAGE—–” and ends with “—–END PGP MESSAGE—–”.
6. Post it here or send it to me.

**Comment by Den241991** [comment]
ok, thank-you.. i have sent you an email. hope this problem can be fixed.. i don't like loosing information.

**Comment by Den241991** [comment]
Fixed, I got my stuff working again :D thank you anyway! i appreciate the help offered :)
