### ISSUE TITLE
Add authenticator doesn't allow steam shared secrets

### ISSUE THREAD

**Issue by LeCoffee** [winauth/winauth#253]
It is to my understanding that steam generates two factor codes slightly off spec to standard methods and numbers in the secret is allowed.

When adding my steam authenticator to winauth using the "Authenticator" option I get an error stating I have an illegal character (its a number) in my secret however steam uses these.

Maybe we could get support for adding existing steam authenticators?

**Comment by winauth** [comment]
Create a file containing:

otpauth://totp/Steam:myaccountname?secret=MYSECRET&issuer=Steam

replacing myaccountname with a name (no spaces) and MYSECRET with the secret key pulled from Steam.

Use the Add->Import to add it.

**Comment by LeCoffee** [comment]
Again I get the issue of invalid character at line one with the character being the first number of my secret :/

**Comment by winauth** [comment]
Sorry, missed a bit...add digits at the end

otpauth://totp/Steam:myaccountname?secret=MYSECRET&issuer=Steam&digits=5

Is your secret valid? It needs to be base32. Where did you get it from?

**Comment by winauth** [comment]
You have to use the secret from the "uri" line, not "shared_secret". They are the same, except "shared_secret" is in Base64. So you would need to convert it to Base32 first.

**Comment by LeCoffee** [comment]
My bots are running with the secret as we speak and using steam-totp I can generate valid codes manually.

My secret is a generic string read copied and pasted in utf-8

I got it directly from valves JSON response

tried otpauth://totp/Steam:test?secret=secretwithdigits=&issuer=Steam&digits=5 still saying my first digit is invalid, feel free to drop me an email and I can show you on teamviewer or something :)

**Comment by LeCoffee** [comment]
Will try the one from the uri now

**Comment by winauth** [comment]
You can use http://tomeko.net/online_tools/base32.php?lang=en

Convert shared_secret from Base64 to hex, and then that hex from hex to Base32.

**Comment by LeCoffee** [comment]
No problem the one from the uri worked a treat! Thanks for your assistance but I really feel this should be implemented in an easier way for future purposes:)

While I have your attention what is the formatting for doing this with XML? Actually I can just export my current ones and figure it out

Thanks!

**Comment by winauth** [comment]
I wouldn't try and import using the XML format, since it can change between versions. The KeyUri format is the best way, which is also how WinAuth exports them.

I actually deliberately didn't add a way to do that for Steam, or even to view the secret key, because of the fact that they use a different implementation. I thought it would be confusing when people tried to add it into Google Authenticator and found it didn't show the same code.

However, the next beta provides a way to import from JSON from the mobile app.

**Comment by LeCoffee** [comment]
Aight thanks anyways :) I run bots for people and just wanted an easy way for them to generate codes for their bots thats all this will do just fine, thanks for your help.
