### ISSUE TITLE
How to remove Steam Authorization from WinAuth 

### ISSUE THREAD

**Issue by azgalaga** [winauth/winauth#254]
I have no idea how to disable it can someone help? I just want it gone now, got tired of this steam authentication bs because trades need to be confirmed and this does the codes only no trade confirm and I used literally everything but nope. So I'll just go ahead and take the 3 day trading wait. Now how to disable it please?

**Comment by kurdt94** [comment]
get the recovery code from winauth, log in to your account and go here:
https://store.steampowered.com/twofactor/manage
