### ISSUE TITLE
Error When add steam 

### ISSUE THREAD

**Issue by Nyseth** [winauth/winauth#257]
![bez tytulu](https://cloud.githubusercontent.com/assets/11856602/11754955/4adcc582-a04f-11e5-8a48-e4452f443e2a.png)
This error popout when i try add Steam Authenticator i use latest version.

**Comment by IDeaDHeaDI** [comment]
+1

**Comment by Skaabais** [comment]
Same problem.

**Comment by winauth** [comment]
I'm looking into it.

**Comment by winauth** [comment]
Will have a new build out later today.

**Comment by Nyseth** [comment]
How i can fix this?

**Comment by kurdt94** [comment]
Will wait for new build, thnx winauth team for all the effort.

**Comment by winauth** [comment]
3.3.7 has the fix.

https://winauth.com/downloads/3.x/WinAuth-3.3.7.zip

Test here, but can someone confirm before I mark it as an upgrade for everyone.

**Comment by MhmdAMiNE** [comment]
Thanks winauth, the new update is working with Steam :+1:
