### ISSUE TITLE
Cant Create steam authenticator

### ISSUE THREAD

**Issue by JesusFrost** [winauth/winauth#259]
when i try create my authenticator, i do all normally, but when i put the verification code from my mail show up this message 

"invalid response from steam" 

https://k60.kn3.net/D/A/A/A/0/A/8ED.png

sorry my bad english lol. ty if somebody can help me

**Comment by winauth** [comment]
HI

I thought I remembered another problem like this.

https://github.com/winauth/winauth/issues/247

Does your account have your phone number linked onto it? Has that number been added onto another account? Could you try removing your phone number and then adding it again.

**Comment by lnwc** [comment]
I had this problem when I was on a cool-down from receiving SMS from Steam for having too many sent to me that day. Inside the client the message it was showing when I tried to do anything that would send me a message was something like "You've received too many messages, please wait a while and retry" - it took ~24 hours to reset.

**Comment by JesusFrost** [comment]
ty for answers :D that was exactly the problem i has a cool-down from SMS now i can create normally again, ty for the help both
