### ISSUE TITLE
Steam not working on Android app

### ISSUE THREAD

**Issue by makedir** [winauth/winauth#261]
Steam not working on Android app, showing numeric number instead of Steam code like "CHJJH".

**Comment by winauth** [comment]
Did you register a Steam authenticator? Please post a screen shot.

**Comment by makedir** [comment]
Yes of course... I exported from PC into txt file and imported on Android via GDrive. It works fine on PC but after import the Android app shows digits instead of numeric code.

**Comment by makedir** [comment]
http://i.imgur.com/7c7saKK.jpg
http://i.imgur.com/40yCblo.jpg

**Comment by makedir** [comment]
You can close this ticket. I totally apologize :'< I am using Authenticator Plus on Android and for a moment, I believed it was from you people too, but of course it is not. So the problem is with Authenticator Plus and not with WinAuth. Sorry again for this. I am asking the Authenticator Plus devs about this problem.

**Comment by winauth** [comment]
No worry. You can import your key into the Steam app (or from), so you effectively have a clone, but it does require root access,

**Comment by makedir** [comment]
I dont know what you mean with that though. What do you mean? :~)

**Comment by winauth** [comment]
It simply means you can copy the data between WinAuth and the official Steam app (and vice-versa) so they both do the same thing. This might be useful as a backup or portable clone.

**Comment by makedir** [comment]
I dont think we are speaking about the same thing. First thing what is the official Steam app? I actually opened this ticket because I needed a code generator on Androud to coypy/paste the code out of it into Android Steam for example.
