### ISSUE TITLE
Adding a Google Authenticator under Microsoft causes a crash

### ISSUE THREAD

**Issue by p1r473** [winauth/winauth#262]
Going to add->Microsoft and adding a Google authenticator causes an crash
otpauth://totp/Example:alice@google.com?secret=JBSWY3DPEHPK3PXP&issuer=Example
![f6f2106e-a7f4-11e5-814f-29c6b2326dac](https://cloud.githubusercontent.com/assets/9235633/11987743/cd423b62-a9b2-11e5-86e6-c8a040ab1f15.png)

**Comment by winauth** [comment]
Thanks. I'll look into it.

**Comment by p1r473** [comment]
Hi, any update?
Thanks!

**Comment by p1r473** [comment]
Thanks for fixing it!
What release will the fix be in so I can test?

**Comment by winauth** [comment]
Next beta, days away I hope. I've been creating a .Net 3.5 version so it will run better as a portable option.

**Comment by p1r473** [comment]
Great!

**Comment by p1r473** [comment]
Works great, thanks.
