### ISSUE TITLE
Import Steam account from iOS phone

### ISSUE THREAD

**Issue by tavrez** [winauth/winauth#263]
The Steam Guard file is located at this address in an iOS device:
/var/mobile/Containers/Data/Application/(steamapp)/Documents/Steamguard-(steamid)

File can be extracted from an iTunes backup or from SSH,iFunBox,iFile if the device is jailbroken. This file contains shared_secret, identity_secret, revocation code and other things, we can have a guide and a manual input form for everyone who can extract it's data from.

**Comment by winauth** [comment]
Could you please upload a sample file (editing your personal data with junk), just so I can check it's the same format as Android.

Also, in Android, there is another file that contains the device id (called steam.uuid.xml). In there an equivalent?

**Comment by tavrez** [comment]
There are two files on iPhone, one contains the data I said above, and another one contains, oauth_token,sessionid,wgtoken,wgtokensecure
Both files are in Apple plist format.
Unfortunately I haven't found any file with device_id in it, maybe app send device UDID as the device id, I'm not sure about this yet.
As I tested with API, device_id is not important, and it can be a random generated number. I should say that I got weird results when I send same device_id two times.

**Comment by tavrez** [comment]
Here are files, can be viewed in windows with an app like plistEditor
I marked the data with an indicator at begining of them, for example here is where oauthtoken should be : "oauthtoken123456781234567812345678"
https://drive.google.com/open?id=0Bxc_H5UGDgF5bjNhSGdQUG5GT00

**Comment by winauth** [comment]
Thanks for the files. In my testing before Steam officially released their forced confirmations, you had to provide the same deviceid as where the authenticator was registered. I need to check if that restriction is still there.

I did check the data to/from Steam on an iPhone, and the device ID is a normal UUID but isn't the actual iPhone one. Must be held somewhere.

**Comment by tavrez** [comment]
I don't think that restriction you said was still there, I wrote an app
with C# for my self to accept all trades, I'm sending random things as
device_id with every request, although I should say that my app is logging
in with it's own oauth_token, not the same one from my phone(which made my
phone app little problematic on getting push notifications from valve, but
it's not matter of this topic now)

And do you know anyway for me to check what it send from my phone as device
ID? Or a sample iPhone data for me to check against my own data.

**Comment by winauth** [comment]
Agree, does seem the original deviceid isn't needed. Although it could change in the future.

I've found that the deviceid is the iPhone's identifierForVendor value, which you can pull from /private/var/db/lsd/com.apple.lsdidentifiers.plist

So right now, you can clone an iPhone Steam app by creating a new Steam Authenticator and selecting import Android. Then enter the above device ID (or make one up) along with the values from your SteamGuard-XXX file converted into JSON. That looks like this with your replacements:

```
{
	"shared_secret" : "your shared secret value",
	"serial_number" : "your serial",
	"revocation_code" : "your revocation code",
	"uri" : "your uri value",
	"server_time" : "your servertime value",
	"account_name" : "your username",
	"token_gid" : "your token_gid value",
	"identity_secret" : "your identity secret",
	"secret_1" : "your secret 1",
	"status" : 1,
	"steamid" : "your steam id"
}
```
I would have to add an plist-to-json converter to make it more friendly.

**Comment by victor-rds** [comment]
Same file can be easily extracted from a rooted android device, I use to recover the secret and use it on keepass, is located on `/data/data/com.valvesoftware.android.steam.community/files/Steamguard-{steamid}`

It's the same JSON structure:
```JavaScript
{
	"account_name": accountName,
	"identity_secret": identitySecret,
	"revocation_code": revocationCode,
	"secret_1": secret1,
	"serial_number": serial,
	"server_time": serverTime
	"shared_secret": sharedSecret,
	"status": 1,
	"steamguard_scheme": 2,
	"steamid": steamid,
	"token_gid": tokenGid,
	"uri": "otpauth:\/\/totp\/Steam:"+accountName+"?secret="+TOTPSecret+"&issuer=Steam"
}
```

I hope it helps
