### ISSUE TITLE
This isn't an Issue, it's just a question about the encrypted password

### ISSUE THREAD

**Issue by BakuDM** [winauth/winauth#264]
As you says in the password screen, you can check those squares to encrypt the key to be used only in this machine even if the files are copied and you say that if you want to format your pc or anything else you should turn off the encrypt option, and to do that you just need to uncheck those 2 squares and it will unencrypt the password?

Because my HD is a bit old and someday he will just die without an warning and if it happens while the encrypt option is enabled I will probably need to remove all the authenticators from my accounts when I get a new one.

**Comment by cdmackie** [comment]
Yes. Those two extra tick boxes are extra encryption in addition to your
password. Windows has a built-in key for every account and installation. So
checking those boxes causes your data to be encrypted with your password
and then by Windows.

So if someone stole your file and knew your password, they still wouldn't
be able to open it. This is extra security, but obviously if you
reinstalled Windows you wouldn't be able to open the files either.

So if you are planning to reinstall, or worried your HD might fail, you
probably should turn off these options. Just untick them and click OK. Your
data is still encrypted with your password, but means the config file could
be used anywhere.

Alternatively, you could make backups and store that somewhere secure. Then
if your data was lost you could recover it. If you do this, make sure you
keep the backups up to date and test they work.

Hope that answers your question.

**Comment by BakuDM** [comment]
Yeah, that answers my question.
Thank you!
