### ISSUE TITLE
Error with confirmations

### ISSUE THREAD

**Issue by RampantZambie** [winauth/winauth#266]
![c73168cb327bbe9a4731869b1ae75802](https://cloud.githubusercontent.com/assets/16399209/12026933/257deff4-ae0b-11e5-9904-2d12a2d7d012.png)

This is the error i get when going to "confirmations"
Keep in mind i do not get this error if there are no pending trades in need of confirmation
I'm using version 4.3

**Comment by winauth** [comment]
Can you download [this version](https://winauth.com/downloads/3.x/WinAuth-3.4.4.zip) and run it, and go into your confirmations where you get the error. It will create a file in the same folder called winauth.log. Can you send it to me.

**Comment by winauth** [comment]
winauth@gmail.com

**Comment by RampantZambie** [comment]
Indeed, will this delay the time until i'll be able to trade?

**Comment by winauth** [comment]
Until I can fix the crash, or if you want to clone it into other software/mobile app.

**Comment by RampantZambie** [comment]
Sending it over now :)

**Comment by RampantZambie** [comment]
Sent.

**Comment by winauth** [comment]
Does [this one](https://winauth.com/downloads/3.x/WinAuth-3.4.5.zip) fix it?

**Comment by RampantZambie** [comment]
Nope :/

**Comment by RampantZambie** [comment]
No, it doesn't

Date: Mon, 28 Dec 2015 15:44:17 -0800

**Comment by winauth** [comment]
Has it ever worked? What versions of .Net do you have installed?..go into Control Panel->Programs & Features, and find Microsoft .Net Framework x.xx

**Comment by RampantZambie** [comment]
Microsoft.net framework 4. 
And i haven't been using winauth for too long as i've only recently lost my phone, But no it has never worked for me

**Comment by winauth** [comment]
Ok, it's that then. We need .Net 4.5. Don't upgrade it though as I'm building another winauth and want to check it works for you.

**Comment by winauth** [comment]
But there was a different bug too :) from the data you sent

**Comment by RampantZambie** [comment]
Oh really?

**Comment by winauth** [comment]
It wasn't finding the trade info...Steam's html had changed. I fixed the regular expression.

[3.4.6](https://winauth.com/downloads/3.x/WinAuth-3.4.6.zip)

**Comment by RampantZambie** [comment]
Apparently that version still doesn't work for me :P

**Comment by winauth** [comment]
Same error?

**Comment by RampantZambie** [comment]
Yup

**Comment by winauth** [comment]
Can you report it using Send Error Report

**Comment by RampantZambie** [comment]
Sent

**Comment by winauth** [comment]
Odd, that's showing the same problem even though I changed it. Let me rebuild it in case I messed up.

**Comment by winauth** [comment]
[3.4.7](https://winauth.com/downloads/3.x/WinAuth-3.4.7.zip)

**Comment by RampantZambie** [comment]
Haha trying it now

**Comment by RampantZambie** [comment]
HUZZAH

**Comment by winauth** [comment]
HUZZAH is good?

**Comment by RampantZambie** [comment]
Huzzah is yay it's working :P

**Comment by winauth** [comment]
Let me know if an Accept/Cancel works.

**Comment by RampantZambie** [comment]
Cancel worked, i'll try accept now

**Comment by winauth** [comment]
Confirm/Cancel...I reworded it

**Comment by RampantZambie** [comment]
Confirm and cancel both work, should i upgrade to microsoft.net framework 4.5 now?

**Comment by winauth** [comment]
If you want. There are some security improvements in Microsoft's SSL, so it's not a bad thing.

**Comment by RampantZambie** [comment]
Awesome, i'm doing that now.Anyway, was fun talking to you

**Comment by winauth** [comment]
Thanks for helping me find the problem. All the best.
