### ISSUE TITLE
WONT ADD STEAM ACCOUNT

### ISSUE THREAD

**Issue by JaViLuMa** [winauth/winauth#267]
I just started usng this application when this showed up after e-mail steam guard code: 
![untitled](https://cloud.githubusercontent.com/assets/16469387/12027425/7cd933ac-adc6-11e5-942c-66f67e12af6b.png)

How do I fix that? Tried every version but still no solution.

**Comment by winauth** [comment]
Can you try [this version](https://winauth.com/downloads/3.x/WinAuth-3.4.7.zip) which will create a file called winauth.log in the same folder. Can you email it to me.

**Comment by winauth** [comment]
Email to winauth@gmail.com

**Comment by winauth** [comment]
Which version are you using?

**Comment by JaViLuMa** [comment]
I am using v3.4.5 atm

**Comment by JaViLuMa** [comment]
And what is your e-mail? I cant find it. And in v3.4.7 is the same problem.

**Comment by JaViLuMa** [comment]
New screenshot v3.4.7

![untitled](https://cloud.githubusercontent.com/assets/16469387/12035077/37c17fae-ae39-11e5-9bbb-7b6a9a664bae.png)

Inside is winauth.log

[test.zip](https://github.com/winauth/winauth/files/73962/test.zip)

**Comment by winauth** [comment]
I got the log file, thanks. It's failing when trying to check if you have a phone attached. Do you definitely have a valid phone number added to your account?

**Comment by JaViLuMa** [comment]
Yes. I can even attach the screenshot.

**Comment by winauth** [comment]
Ok, can you try this one [3.4.8](https://winauth.com/downloads/3.x/WinAuth-3.4.8.zip). I've let it pass the error on checking the phone to see if it gets further. It may fail somewhere else, but might help find out why. Please send the log file again. winauth@gmail.com.

**Comment by JaViLuMa** [comment]
Ok

**Comment by JaViLuMa** [comment]
SENT YOU EMAIL!!! ITS: matej.gamer01@gmail.com

TRADE CONFIRMATIONS DOESNT WANNA LOG IN!!!

**Comment by winauth** [comment]
Can you back to the 3.4.7 version and see if that works. I think there is a different issue in 3.4.8.

**Comment by JaViLuMa** [comment]
Okay I'll try. But what If I have already activated steam guard on v3.4.8 version?

**Comment by winauth** [comment]
It's compatible. As long as you have that recovery code, you can always remove it.

**Comment by JaViLuMa** [comment]
Oh okay.

**Comment by winauth** [comment]
You can go back to 3.4.3, which should work for confirmations now that you've got your authenticator registered. That version won't do any logging.

**Comment by JaViLuMa** [comment]
When I try to login to steam confirmations, I get: Wrong authenticator. Are you sure this is your authenticator password

And I am still on the username and pass menu

**Comment by winauth** [comment]
Cancel it. Right-click your authenticator, do Sync Time. Go into Confirmations again.

**Comment by JaViLuMa** [comment]
The problem still occurs.

**Comment by JaViLuMa** [comment]
Want screenshot?

**Comment by winauth** [comment]
Yes. But did you definitely get an email saying your authenticator had been added? Can you get into your Steam account?

**Comment by JaViLuMa** [comment]
Yes, I can. Checked it 5 minutes beofre. SS: 
![untitled](https://cloud.githubusercontent.com/assets/16469387/12043552/7561f7a6-ae86-11e5-8cc8-26b0b67b25cf.png)

And it happens when I press LOGIN 2 times.

**Comment by JaViLuMa** [comment]
Proof of adding authenticator: 
![untitled](https://cloud.githubusercontent.com/assets/16469387/12043573/aaf56a2e-ae86-11e5-8a69-0d5a0442ee25.png)

**Comment by winauth** [comment]
There is a Steam safeguard that you can't login within 30 secs (or using the same authenticator code). So the 2nd time would fail. What happens if you wait a minute then login once?

**Comment by JaViLuMa** [comment]
What do you mean? I press login once, then wait a minute, then press it again?

**Comment by winauth** [comment]
No, just wait before trying to login again.

> And it happens when I press LOGIN 2 times.

Why 2 times?

**Comment by JaViLuMa** [comment]
I dont know. When I press login, its blurs and starts loading, when it stops, login button unblurs and i have to press again

**Comment by JaViLuMa** [comment]
Do you have skype or something? Would it be easier if we talk not write??

**Comment by winauth** [comment]
skype:cdmackie

**Comment by winauth** [comment]
Can you use [3.4.9](https://winauth.com/downloads/3.x/WinAuth-3.4.9.zip) and send me log file up to that error.

**Comment by JaViLuMa** [comment]
Ok.

**Comment by winauth** [comment]
After a little testing, you need to have "Community-generated content" ticked in Family View to be able to view Confirmations.
