### ISSUE TITLE
Phone numbers for steam trade "stuff"

### ISSUE THREAD

**Issue by Newcool1230** [winauth/winauth#268]
So, i wanted to try this out but i have a problem with the phone number 
https://gyazo.com/157753ef3e86f267acc43f66834eb0be

i have tried other auth's and they give me an error at the phone part too
I was thinking it could be my Canadian phone number, so i tried google voice
but steam doesnt accept google voices phone numbers.....
the phone number is already linked to my steam account.
anyone have any ideas about the phones?

**Comment by winauth** [comment]
Steam does accept Google Voice numbers, I use one for my account.

If you have been trying to set up an authenticator and had too many SMS messages sent (or failed), then it could be blocked. Steam blocks a number for 24hrs with too many SMS sent.

If you've waited and it still doesn't work, you could try removing the number and adding it again directly through the Steam client/website. You are getting the add SMS verify code via Steam?

Otherwise, do you have Family settings on? If so, turn them off first.

**Comment by Newcool1230** [comment]
lol i do have family settings on.
i will try and turn it off and report back to u 
captain winauth

**Comment by Newcool1230** [comment]
the family settings was on
now it is off and now it let me proceed to the next
thing but.....
a error :O 
-----BEGIN PGP MESSAGE-----
Version: BCPG C# v3.3.7.2

hQEMA53DDyNpqwwqAQf+NMAd14A9lCz2OGwJUFoPSx2ZHtnZhBFEHD34yGlzLu06
Lwgq6+m/S12Fz/IF68TxPV+LXaGP5FEoaowJZDu62qSVcFdTXRjBqOnAGj9+vbna
naDS4hE3Xb8ymEjss1WnAITC9q/jEgmx+I4exXZU44opcVjP1JOzeWpDt1LFH6Jb
HP8YDpM8sg6sGpb6+XTC3FFqh/jpTvB0jt97UQIxQYx9O7IXoqSDTlv8B0iimsbT
lko0jtx/GivTONRfgfYdg5nAQ7ffM2DDs5r69l1SF7WWb2YEIBKwJs9qrNQNS0cg
ngfwmZZo8i36kMkoQ7RJCTZGCR/17uH8XQA/3EmHtNLBpQFF1ZWu0c0vyU7Gvk+G
D21V/YMYoHlHuqIpRh80G7kaPtHuIsGZnJN5s2m0jCeilQyzlrQlj4Un/m4lD9Ge
go44N3+e80X8j1IeuYLTMl2KtfCNtSY1vFdSMlhb28Y6Bf0pcPqLCTEyDW/7fMj+
nVkoQG5Dct0zesLoyQoZCM1c1PgF83H/sbMreGSyR6+F3jl6N2LbnaogV2qYiSfz
p6hXKi5uvp4pRk2ilHPV+VT6n+PCuM3mV33JvJ1BSaaB5ioNfM9vhEEfVpDluzm0
Ywd0+dWHhQw8xBa+6Y52BJLxeq2o6ZxT5GT/Dx5xFN1phZAQwDc5OuX/62nyu/Uu
spqQGmT14Gz6zKaJai6PEdrGPV9LVg7OBbgstvZLlFU9H5DuA/9tIJT1OtHMwxlh
lQb0eQPh5qnuSbfeDiloRNyZpFvpq2iy7omTHp1yO1Hbzl4E1fbw9XpGaq8uTDmm
0rvr2a7/YgKGhQFPGdwuwjr/ONBQin7pDTkZtoc61rtWFPu8ft/7cRiMFNNNN/Oh
YJ5ZbwCXIPeLr1bjFIf2H+UtI/HjclyR07sTwxjdVrIt70xo1Zu9+S4JvBcTCLg6
EV2zwHVqNWzNSrgMVS+biJ7AeC+aBLrXAj+rU3vuMKTRWfoO2b8dgDIqLWHzFauI
+caKVjZlOWXB/MIDKt0oyPYRRsGhwW23loxEIohUHK1J2chJv5ys36rkkMzcb6Zz
yeDTx7uAimVg52TdD/L1H2UynRjO1037Haevn8yXVTfyshZ5jl6fRebR4X02Cu7z
EfsPTUCjMYMxRe/qxZqazfh4Dpk2M70=
=cWQZ
-----END PGP MESSAGE-----

**Comment by My1** [comment]
it might be helpful to be able to enter steam family settings pin, because I have them on as well (just as a simple matter to lock the shop)
