### ISSUE TITLE
I Wiped My Computer, And I Do Not Know How To Log Into My WinAuth Account?

### ISSUE THREAD

**Issue by Jimbolimbo555** [winauth/winauth#271]
Hi there I installed WinAuth a few days ago due to Valve`s update regarding the mobile codes and with trading. I know I reset my PC and with it any files from my old install of WinAuth. I have gone through the long process of obtaining my account again via support. I need to know if/ how I can install WinAuth again without it saying there is already a authenticator for this account error. Any way to fix this because other wise I am in a bad situation. Any help is needed! I am using the latest version at this time.

And I do still have my code it told me to write down so I did not lose EVERYTHING. I also remember the password that I need to log into WinAuth. I just don`t know where to!

**Comment by Jimbolimbo555** [comment]
Resolved. Thank you for your amazing program and skills BTW!

**Comment by winauth** [comment]
Welcome :) Glad you got sorted.
