### ISSUE TITLE
winauth eror.

### ISSUE THREAD

**Issue by anapot1** [winauth/winauth#272]
![winauth error](https://cloud.githubusercontent.com/assets/16677777/12284052/99c87fd6-b9e7-11e5-86c4-3760def0a721.png)

additional information. .

i have already verified the 7 days steam guard authenticator using the version 3.3.7. but since it has no trade confirmation i download the version 3.4.3 and replace the old version. after that the 7 days trade restriction has reset. . but i can sell and trade in steam market/ there is no restriction inside the steam. . except for other website trading like betting site. is it possible that the cause of error is the 7 days trade restriction? . . need and update and clear response about this error.

confirmation of the create list item, in steam (when you sell items must be clarify).
because it has to be no restriction since it's already used 7 days authenticator.

confirmation of steam trade offer and trading to other site, like betting site(dota2lounge, vpgame, dotabestyolo, etc..) must be clarify also since it has 7 days restriction.

---------------thanks and more power------------------------

**Comment by winauth** [comment]
Hopefully fixed in latest version. Let me know if not.
