### ISSUE TITLE
Error enrolling new authenticator

### ISSUE THREAD

**Issue by sergun26** [winauth/winauth#273]
Error enrolling new authenticator

   konum: WinAuth.SteamAuthenticator.Enroll(EnrollState state)

http://i.imgur.com/YEBjtWy.png
http://i.imgur.com/UVnLJ3s.jpg

**Comment by winauth** [comment]
Which version are you on?

Can you try again too, since Steam servers look like they might have been down today.

**Comment by sergun26** [comment]
Latest version
Same error with beta build.
http://i.imgur.com/K2JKO4F.png

**Comment by RampantZambie** [comment]
Yeah i've got an issue too, "hexadeciaml value 0x00, is an invalid character. Line 1,position 1.

**Comment by winauth** [comment]
I'm looking into it. Did anyone get a winauth.log file created in the same folder? If so, could you email it to me. Winauth@gmail.com.

**Comment by winauth** [comment]
It looks like Steam is having intermittent problems. Some of their calls are not returning or reporting "502 Gateway error". However, WinAuth isn't handing it well and crashing. Going to fix it, but you might be able to try again and get it working.

**Comment by NukEgo** [comment]
Hello, i forced a frind to try winauth and it works fine for him, but when i type in my Name and 
Password there is a failure "an error occurred while registering the athenticator" "error enrolling new authenticator". I copy and paste the log file, but i used not my account name. ;-)  Please help me, it would be so wonderfull if that will work. Thx.


-----BEGIN PGP MESSAGE-----
Version: BCPG C# v3.4.23.2

hQEMA53DDyNpqwwqAQf7BznSd/CG/qiscPm2opr+bhkbIPryNgHdM8aI5EFPMUlR
XI1Cyi8asuM1xhLdJS3mJ8VVe06fXhQ9THK1zAmIJYZDg0AnjVRtDIsFDLsSy5fc
Af2W9GCz1j6P3JQQewhIa/jhGytidUi94BKu9lc3tkB18CiLP3qfUhw/5Rnura+a
dHXmbRZ/wTJJmAr6pWnoPxzQ/xtdJXUmE5MFU4NLvKSzN8vI4FmxuFPplhFJmITk
fOP0goJ8mOSW4Kb3WNv6T+u4j9LKug78WbNR8YyoZn40l4soxyvzJhvgtKl2OMoP
bp+lpwuirLLQ3g6ytT8qGaDQxd+vUR+dNGAz+3wFu9LHbQHIzd3HAdJXd9iT1bn/
w9gHWiWKltnOGGBJGoJtPrsNJloxEWtVkpvdaq+aGmupMUvrKockUb1owPS5hMKz
SK+zO/t57hDtg2Rx1Y8G1WdK+kNwHY5m/fOnlGn4V29P6x6RoPPE4UmHkfKcAAdN
Xgk4rsjoZ+3jCR8KcphEEas0SToauSC8nM3tw2+Rp35zi630HWMCKbYI7l1rijGX
/aFYvtGHRtWG6yh+tLuFy2c0Gbxr0Cx5nXQtG/uQljam+6B19ZY1qkRLTrFasPjs
5vi3z5sgRTP53M+gc/KHGi+A7CpmQ/Nn8BKBmdvBF+CjhQ0LkWMgMTAyIeIEqLY0
FelMMe7qtpzbOM54UnZjh8/aT5s2YvrQEEgXQDCAr4+bh4UflMcUk4p61GGCMxqs
BReJ1WRLkjS7nB5TMzAP+uMdLpJm6nSnILt+89zOgQn/tVKRZOFKW9mOVqdjBoEb
mfQhmtnySGWMXxQh1gZClAUnfTVD8UF2iL/iNyHDoEx5F9sAEZu9MoLIwklK4vzO
55GpZs3kjBXIjvPjl8rrlDC8e36RtG+p+ZDy26Hbo+4IcDmk99VOH20AL1tu4MLA
TnWsiNVsiFlBmcLPZyEv/Y/2t9TgWlIEV/vtxGKAbNRCGdMHb6Gl6xe5S2h3mSsi
LDOs4q6R9BV/zJHu8S4fY40ZjUJ0164ECrXQ3qQWm3n1LWGABTUlHN158UztEJ1F
g+BtDCbUCDSf2ZF35cer5qKNcVx1TaeZNescRd6UoYiJs1Gl8qFcvhsH39JPqnS0
FedPXTxDEqceF82aPS7KTtDtrYwIJFAhe8E7LEeBPiM6C+3C8CqRHHH9OSWQCobz
VOVBOa4lfFxeifqcng0Nr7+Ly75G17TsiskIlK3uxq5cVmt8Q2Bg1StNAJFai5lN
gV0o30GjiKn/ppI8qswKiG+v4FnQkmhi4H6mjsPn8SweaEJO6FVQKW4TxviBoSlc
9vvM7ipTbH8esdsYdMt8/h817Y6Ijt3z0q7OU3A9zMDT2rA3N4GgxRFb8CLW0biD
Tchtq3aIkG8brsymDYNUxMfEwdZ5pw1Wyd9ZLNCsCKN9ZnSsf1XKJNro8MkPxlO6
xWCQ8ggpaEcYg7VB+mjsSO3xZowU9XmjVJ/2oEZkhucYiO1biAClIYEJl3bRjzxR
yz8n59EbV1tbcOeVMs4It8PN5Nle5jcW5ZVfNDj545d/OYZ/VUyjXqZW2jJ9o6AG
FYUPGgYWaJaUy4Dt8DmywQSs2dW1YPTJpZtPaE1j5ezgmsjgI7/ibcwn5knc7UBp
A6NPLPf5btFFP4HYE1Hw1+2ZY2OEr0MGTGs8R0mJ8rks3h0tFtsIGF24oHPBlcDE
JZE1lhK/UNE0woscIjgwh/PXJ/eF8SA82/6bi5YRJWKca0VNCh8cwRja3teV/hjd
L9kN9vXTU711QGsafhIlPeNmgL4TFoUHScPsPsHEvWhg4C/f3W2gM6y8eTNQD761
Cv7iH3q6a7Aek4WEg11qW6nQZIt3gD62veFWzaQD3UXyG8g/Te73pgoZEiMoqOeG
WM/QRaTsBVChSDMjB1gBtCMlsIfQwqekLilFlIUWQEGvotU7NH/L7C7rWm1ojc/w
j/T6lL6sLVx7iNbEPIk7ssBbSySV9m/rAgpfbPx0SzzFqW09HDusV5PEDK5VuL+A
C77qjIVoA+BHxCCw8kmQMax8GjRvLjmz07U6J2DiyQnJieWKUB4DvfGP+7/6q5bq
pE8wNKG8of6MA+Sgz18CdtYbzQqu1/nh2sVkSemgBp25QLrx93D1LUHbiQ2lPEu1
DtcClJVAsmXno5iqez2n81R4Hh1YvuHB1B5m8qm8p3lJUk7X6HoT5C3SFRBVucbC
v3r+5mhS+04pgzQ2jtz9EKBB35IuFc3eZEA+1eMoFomd8FysgjXck+HTlyGUPv/J
1YvPpYIgRvTYBuZQWC8tImIX7wojGllJFGKBN1OrC6+dv62Z+8nPZKUGWX0dL2Us
cSkdOs6F9bTgmTDFEUBcZ1ldyUMv3OuhvStwZp10JRw1obwRnT2WQF/MAClNSwYa
pRvnkSKFxLg0M3humBJxMHtx8YbYq9tbLPkxZZMuZLBGq2mprmCM9Q64mUwld15f
dt6EPLMAe2L2p0viAOSQF9yFqX+nCn4M7Z0qk6IaxufQ4rAkVKbooZapnq4y6gYG
eQlhKsRTa8eiDBXfEkh0uJGOxdEE1Jj5ip6yE/QUGw+GlwxySvIdqMU9tQMDI8ip
Zn/iYO8jxYfAw7/ThF/nvUiO6C4dSQWthtHQBcGlcE/1iZg0iEZ1RRqwsFuXtfXK
BefI9FlYg4IUATQmZU8Zx1M4VZ1TX3obEGLYIWwH0dnN2BOsJ29rkS44sOUj1juK
m2G9X8/Ee1aQkn0jOYe2z5gz4Sln+jZDic3ftrLYzXqGCixLLMLFSEKtmV+QV6bF
EPYTN0FfhH9e55WJilqrlysJgZjW0FDiq6MAQZdR2gPNb4C58FiA8+c7AuTtlwdq
3r6vve3/Hk60T7c/gnCEu3kVoxlrxu3MSDS2XZJJqkv0eLiuxfR6ti/hCaOmgfS9
/va27YfWBwE5ZqI/1mwdv3vSMRThCMwHW67chFYsc5vdUddOMBViXHP1BMSdlBHw
zNSHA9dy1Vw93TVQw7A8PpuOLwWsaSkvrx/pRTR2gw/GZLJfzHuUYJMLPeVLErQa
BbE62525dg0vIhVi76Svcz72nOZNvoDgB8+WMa1+/nBRZCJAUH1IguONrNiDW9e/
NEZQVZrqmhoOZdCUld6X
=W4Dc
-----END PGP MESSAGE-----

**Comment by winauth** [comment]
@NukEgo The error is just an issue connecting to Steam' servers. Either they were having problems and it'll work again after retrying, or do you have any firewall/AV software that is blocking WinAuth?
