### ISSUE TITLE
Invalid response from steam

### ISSUE THREAD

**Issue by stepanex** [winauth/winauth#274]
I'm trying to add new steam authenticator, after entering code from my email error msg pops up with: 

"Invalid response from Steam: {
"respons":{
"status": 2
}
}

![capture1](https://cloud.githubusercontent.com/assets/8274353/12374223/0b877320-bc95-11e5-94ae-b8624edec7c6.jpg)

**Comment by winauth** [comment]
Which version?

Do you have a phone number on your account and family sharing disabled?

**Comment by stepanex** [comment]
version of winauth: 3.3.7
phone number added
family sharing not enabled

**Comment by stepanex** [comment]
It works now, error message didn't pop up. thanks for quick reply tho

**Comment by winauth** [comment]
No, problem. Just Steam servers were down I guess.
