### ISSUE TITLE
'.'. hexadecimal value 0x00. is an invalid character. Line 1. position.

### ISSUE THREAD

**Issue by echobinary** [winauth/winauth#278]
'.', hexadecimal value 0x00, is an invalid character. Line 1, position 1.

   at System.Xml.XmlTextReaderImpl.Throw(Exception e)
   at System.Xml.XmlTextReaderImpl.ThrowInvalidChar(Char[] data, Int32 length, Int32 invCharPos)
   at System.Xml.XmlTextReaderImpl.ParseRootLevelWhitespace()
   at System.Xml.XmlTextReaderImpl.ParseDocumentContent()
   at WinAuth.WinAuthConfig.ReadXml(XmlReader reader, String password)
   at WinAuth.WinAuthHelper.LoadConfig(Form form, String configFile, String password)
   at WinAuth.WinAuthForm.<>c__DisplayClass31_0.<loadConfig>b__0()

**Comment by echobinary** [comment]
Then the program closes.

**Comment by winauth** [comment]
Which version? Anything odd happen last time it ran? Are you using Steam and doing any trade confirmations?

**Comment by echobinary** [comment]
I have tried the latest stable version (3.3.5), the version just prior to the latest stable version (3.3.1), and the beta version (3.4)  that is up. 
I am not using Steam anything.
I did just recently perform the free upgrade from WIN 8.1 -> Win 10
I cannot remember for certain but I am pretty sure WinAuth still worked for me after the upgrade. 
The WinAuth program stopped working (that I noticed) about a month or two ago. Which is about 2 months after my Win10 upgrade...

**Comment by winauth** [comment]
The problem is your config file (\Users\<username>\AppData\Roaming\WinAuth\winauth,xml) is blank. I also upgraded from 8.1 to 10, and it didn't affect mine, so probably not that. Either something is going wrong in WinAuth and wiping the file, or something else (antivirus, malware, etc) intercepted it and caused the file to be corrupt.

You'll need to create it from a backup. Either a copy of that original file, or add each authenticator using the original secret keys. If you don't have those, there is a backup stored in your Windows registry (follow instructions [here](https://winauth.com/lost-forgotten-password/))

**Comment by echobinary** [comment]
I opened the config file at  \Users<username>\AppData\Roaming\WinAuth\winauth,xml
The file is 76kb and I opened it in Notepad++ to see that the file was full of NUL characters
I followed the directions for restoring from registry backup and copied each registry entry into the config.xml file - saved and then opened the application (beta) and got the following error:

Data at the root level is invalid Line 1, position 1.
Data at the root level is invalid. Line 1, position 1.

   at System.Xml.XmlTextReaderImpl.Throw(Exception e)
   at System.Xml.XmlTextReaderImpl.ParseRootLevelWhitespace()
   at System.Xml.XmlTextReaderImpl.ParseDocumentContent()
   at WinAuth.WinAuthConfig.ReadXml(XmlReader reader, String password)
   at WinAuth.WinAuthHelper.LoadConfig(Form form, String configFile, String password)
   at WinAuth.WinAuthForm.<>c__DisplayClass31_0.<loadConfig>b__0()

**Comment by winauth** [comment]
Send that data from the registry to me. winauth@gmail.com

**Comment by echobinary** [comment]
I got it to work finally. I re-read the instructions and remembered I had a backup stored elsewhere. I followed the Add-> Import instructions, it seems to be working now.
Thank you :)

**Comment by winauth** [comment]
Ok, great. Glad you got it working. Still curious to know why it zeroed out your file. If you can think of anything, or it happens again, please let me know.

**Comment by emoansbert7** [comment]
how to solve i cant open my steam coz of thsi windows auth hexadecimal!!!!!!!!!!!!!!!!!!!!!

**Comment by winauth** [comment]
Your configuration file is corrupted. Restore the file from a backup or reimport from previous exports. See the comment above.
