### ISSUE TITLE
Forgot password WinAuth 3.3.7 please help for reinstall

### ISSUE THREAD

**Issue by Belkiller** [winauth/winauth#280]
Hello,
I forgot my pasword for winauth.
I dont care if i lose my codes but i want to make a new installation.
But i have windows 10 and he asks all de time my pasword after a delete and new downloaded file.
Thanks in advance

**Comment by winauth** [comment]
Rename or delete the file that holds your old authenticator data.

\Users\<username>\AppData\Roaming\WinAuth\winauth.xml

Then restart winauth.

**Comment by Belkiller** [comment]
I do not find this file in that folder i have seacht it before the post and not find
It is Windows 10.
Thanks in advance

**Comment by Belkiller** [comment]
Can nobody help me?

**Comment by winauth** [comment]
That's where the file is by default. If it's asking for a password, it's finding a winauth.xml file in your profile folder (<username>\Appdata\roaming\winauth) or the same folder as you have winauth.exe.
