### ISSUE TITLE
Winauth error with Steam comfirmations

### ISSUE THREAD

**Issue by annors01** [winauth/winauth#281]
Hello.
I'm receiving this error every 10-15 min when i enable the "auto accept" option with winauth.

Unauthorised

   em WinAuth.SteamClient.Request(String url, String method, NameValueCollection data, NameValueCollection headers)
   em WinAuth.SteamClient.GetString(String url, String method, NameValueCollection formdata, NameValueCollection headers)
   em WinAuth.SteamClient.GetConfirmations()
   em WinAuth.SteamClient.<PollConfirmations>d__51.MoveNext()

I understand this is a beta version (3,4.11), but I'm reporting this since more people may be experiencing the same (for future builds).

**Comment by annors01** [comment]
ok... I suspect the error is because my IP was blocked from steam community access. (unsure). 
If i access community page to often (my script to receive trade offers does that), it blocks me out for few minutes... 
When winauth tries to access it, it cannot retrieve any data. It then gives me the error and stop running. 
If there is a way it would give the error msg but keep running, it would solve mey problem (even though it is not the proper way to fixing it). Since on the second try my ip may not be blocked and then it can access.

**Comment by winauth** [comment]
There was an issue, although I'm not sure if causing your problem, but fixed in latest [3.4.13](https://winauth.com/downloads/3.x/WinAuth-3.4.13.zip). Can you try first and see it it helps.

**Comment by winauth** [comment]
And...really fixed in [3.4.15](https://winauth.com/downloads/3.x/WinAuth-3.4.15.zip)
