### ISSUE TITLE
Unable to compile

### ISSUE THREAD

**Issue by Efreak** [winauth/winauth#285]
I imported directly from the github website to visual studio 2015 enterprise using the button ![button](http://i1.someimage.com/0ufZ7yg.png).

The first time I tried to build the solution (WinAuth.sln), it complained that Yubikeyx86.Test.vcxproj was missing. I closed the solution and reopened it. Visual studio immediately gave me a [massive list](https://gist.github.com/2b9e64bb54d7893b043f) of errors with the solution and refused to compile. There seems to be a large number of missing dependencies.

It would be appreciated if there was a wiki or other information on compiling the code. I'd like to help by including some code for Verisign/Symantec's VIP Access app (used by ebay and paypal), but I can't even get what's already there to work.

**Comment by Efreak** [comment]
Updating Newtonsoft.JSON for got rid of *most* of the problems for the selected build (x64 release was selected at the time), but not for any of the other build options (debug, x86, Win32, etc)

**Comment by winauth** [comment]
Thanks for feedback. I'll check it out but wasn't too surprised since I hadn't tried the beta on a clear machine for a while.

**Comment by Efreak** [comment]
Regarding compiling the project:

I went ahead and updated visual studio 2015 to VS 2015.1 (Visual Studio spent ~4 hours running the update. Why can't they do this through windows update like it used to?) and I think I've figured it out. Here's what happens after I `git clean -dfx && git checkout .`:

1. The solution loads
  - [Many errors](https://gist.github.com/c98bf88b1631cd92a7d4)
2. f6 for build -> restoring NuGet packages
  - [2 errors](https://gist.github.com/4ffbc947de9d279f59d6)
  - No exe file(s)
3. hit f6 (again) for build, it works perfectly. Outputs:
  - C:\Users\Efreak\Source\Repos\winauth\Net4.5\bin\Debug\WinAuth.exe
  - C:\Users\Efreak\Source\Repos\winauth\Net4.5\bin\Debug\app.publish\WinAuth.exe
4. Change solution to debug/x64 instead of debug/mixed platforms, then Build -> Clean Solution, then rebuild debug/x64 again (I get the same warnings both ways)
  - [2 warnings about target processor](https://gist.github.com/a2128edf1b067aca0087)


---

Regarding VIP Access functions:

I have very little experience with most of the stuff involved (python, C#, XML, VS itself, etc), so I'm not entirely sure how to go about porting the VIP Access to WinAuth. <sup><sub>Also, I'm lazy and don't care to learn about these things right now, when I could be working on [other stuff](/efreak/node-steam-chat-bot) or even nothing at all.</sup></sub>

If this is not a difficult thing to implement, I'd like to just leave this as a feature request for now, otherwise I'll look at it again when I have enough time to figure it out. The python version that I used to add my ebay/paypal authenticators is at [dlenski/python-vipaccess](/dlenski/python-vipaccess).

**Comment by winauth** [comment]
Build tested on clean VS2015.
