### ISSUE TITLE
Unknown error

### ISSUE THREAD

**Issue by S1AnGeR** [winauth/winauth#287]
![image](https://cloud.githubusercontent.com/assets/5192883/12836068/78d38a8c-cbc6-11e5-97a8-c86d58949306.png)

**Comment by winauth** [comment]
Sounds like [#278](https://github.com/winauth/winauth/issues/278), Which version?

**Comment by S1AnGeR** [comment]
Yes, its same problem , trying all versions : 3.3.7 < and older. Lost all my authenticators... Any ideas?

**Comment by winauth** [comment]
Had you tried the 3.4 beta version? Or ran an older version (e.g. 3.2)?

Do you have any backups of your winauth files, specifically the \Users\<username>\AppData\Roaming\WinAuth\winauth.xml file.

Can you try following these instructions:

https://winauth.com/lost-forgotten-password/

**Comment by winauth** [comment]
..namely the "If you’ve been asked to provide your registry backup". Email to me winauth@gmail.com

**Comment by S1AnGeR** [comment]
No, I didn't use 3.4 beta. 
no backup... I delete winauth.xml , and set WinAuth with new data.

**Comment by rayascha** [comment]
I need help too. This hexadecimal thingy and I haven't exported for a backup. Please help me!
