### ISSUE TITLE
is there anyway to use winauth to get steam guard authentication from the Ice Steam client

### ISSUE THREAD

**Issue by SakifX9** [winauth/winauth#288]
https://play.google.com/store/apps/details?id=com.aegamesi.steamtrade&hl=en Ice Client

**Comment by winauth** [comment]
Not directly. If you have a rooted you are likely able to pull the necessary information. I know this is the case for the official client, but I'm not familiar with this one. Are you rooted?

**Comment by My1** [comment]
just a question concerning this. HOW can I pull the data from official steam and put it in winauth?

**Comment by winauth** [comment]
You need a rooted phone. Then you can use a root File Explore app, or adb, to copy the two files you need.

e.g. 
```
adb pull /data/data/com.valvesoftware.android.steam.community/shared_prefs/steam.uuid.xml
adb pull /data/data/com.valvesoftware.android.steam.community/files/SteamGuard-*
```
(note you may have to move these files into a readable location before they are pulled)

**Comment by My1** [comment]
Well i have those already, had a feeling that those are it, so how to import them? I can't find an option.

**Comment by winauth** [comment]
Click Add, choose Steam, Select "Import Android" tab. Copy contents of files.

**Comment by My1** [comment]
When I had it open last time there was iirc just login. I'm on phone right now but home in a few minutes

**Comment by winauth** [comment]
You need 3.4.x

**Comment by My1** [comment]
So it's beta? Okay nice to know, i usually dl stable when i try stuff first.

**Comment by winauth** [comment]
It is. Trade confirmations have been in Beta for a while to check their stability.

There is a way to put it into 3.3, by exporting from 3.4.

Run 3.4.x on a separate machine (otherwise it will upgrade your winauth.xml) and import the Steam auth as above. USe the menu and "Export..." to a text file.

Copy that file to your original PC and in WinAuth click Add and choose Import. Find and select the txt file.

**Comment by My1** [comment]
or in case I havent used it at all (except for testing data), run it, import, export, throw 3.4 into oblivion, run 3.3 and so on.

**Comment by winauth** [comment]
Yes, be sure to delete the winauth.xml before running 3.3.

**Comment by My1** [comment]
yeah, I have read that upgrade thing, while I dont like such stuf, it's understandable and it's very nice that you can at least export/import to lower versions.
