### ISSUE TITLE
winauth not loading the backup completely

### ISSUE THREAD

**Issue by karontenokami** [winauth/winauth#290]
been trying to add a backup i had after getting a new pc
and winauth just loads one authenticator of the 3 i had on the backup
heres the info that the diagnostics tool gives
Index was out of range. Must be non-negative and less than the size of the collection value. Parameter name: index
   in System.ThrowHelper.ThrowArgumentOutOfRangeException(ExceptionArgument argument, ExceptionResource resource)
   in WinAuth.WinAuthConfig.Clone()
   in WinAuth.DiagnosticForm.BuildDiagnostics()
   in WinAuth.DiagnosticForm.ErrorReportForm_Load(Object sender, EventArgs e)

Issue resolved itself.. looking at the previous similar issues i think this is recurrent.. but now my winauth is listing them 
the authenticator i need.. is probably not giving a proper code.. can't login with it..

**Comment by winauth** [comment]
I think you'll need to send over the backup so I could check it out.

Right click and Sync Time to make sure each the  are generating the right codes.

**Comment by karontenokami** [comment]
yup needed to sync.. my bad sorry for wasting your time and thanks for the amazing soft :D
