### ISSUE TITLE
Data not saving

### ISSUE THREAD

**Issue by GreYzZ** [winauth/winauth#294]
Hello,
my winauth does not save my data which I have to put in as soon I want to recieve the confirmations.

And 1 question, does winauth also support the market confirmations?

**Comment by GreYzZ** [comment]
@winauth 
A fix?

**Comment by winauth** [comment]
Which version? You are ticking the remember me?...what about permanently?

**Comment by GreYzZ** [comment]
@winauth I'm using the latest beta version and yes I'm ticking both

**Comment by winauth** [comment]
Can download this: https://winauth.com/downloads/3.x/WinAuth-3.4.17.zip

Change the properties of the icon for when you run winauth to add "-l debug", or if you use Start->Run, add it to the end. e,g, "c:\path-to-winauth\winauth.exe -l debug"

It'll create a winauth.log file either in your "c:\Users\<username>\AppData\Roaming\WinAuth" folder or the folder where you load your winauth.xml file.

Can you start WinAuth, go through the process of "remembering" your login, stop, restart and then do it again where it should remember it.

Then send me the winauth.log file.

**Comment by winauth** [comment]
Email to winauth@gmail.com

**Comment by GreYzZ** [comment]
@winauth 
Does not generate a log file and if you use a beta version it shows up in Updates "Version 3.3.7"

**Comment by winauth** [comment]
Beta is just reporting latest stable version. Don't worry about it. As long as the About says 3.4.17.

It should be generating log file. Can you double-check the command line, can use "-l debug" or "--log debug". Is your winauth.xml in the standard Appdata\Roaming folder? If not, does it have write access?

You can try moving your winauth.xml into same folder as winauth.exe (make a backup). It should read it from there and create log file there too.
