### ISSUE TITLE
WinAuth massive issue.

### ISSUE THREAD

**Issue by ShadowRaid5** [winauth/winauth#295]
So I tried to log into a game i use WinAuth for and i couldn't remember my password for WinAuth. Well i seen there was an Update, so i updated after copy and pasting my xml file for the authenticator and now WinAuth won't do anything if i try to import that file, it just stays on the part asking to add an authenticator and i can't remove the authenticator on my game without the authenticator code. I've contacted the game's support team about getting it removed from my account since i can't access it to remove it manually. But i just wanted to ask if i did make a giant mistake or if there's anyway to fix it. I know there's no password reset or anything, but that won't help now since WinAuth won't let importing work,

**Comment by winauth** [comment]
What version are/were you using?

This might help: https://winauth.com/lost-forgotten-password/

If you've forgotten your password, there isn't any point importing anything, unless you had a clean backup of the secret key. But you can do the "registry backup" step.

**Comment by winauth** [comment]
Email it to winauth@gmail.com

**Comment by ShadowRaid5** [comment]
The update was for version 3.3.7. And I looked at that article, it didn't help. #1 I couldn't do because i didn't have my password to be able to access the authenticator to export it, #2 again couldn't access the authenticator, and #3 is what i did, i copied the xml file straight from the folder and pasted it to my desktop after updating WinAuth. Then i tried to import it, and it wont import. It's acting like it the xml file doesn't exist.

**Comment by winauth** [comment]
Send the registry data.

**Comment by ShadowRaid5** [comment]
How do i do that?

**Comment by winauth** [comment]
Follow the instructions in https://winauth.com/lost-forgotten-password/ for "If you’ve been asked to provide your registry backup". Email it to winauth@gmail.com

**Comment by ShadowRaid5** [comment]
Ok, i sent the email with the only registry backup i have for WinAuth3

Date: Wed, 2 Mar 2016 08:53:41 -0800
