### ISSUE TITLE
iOS Google Authenticator doesn't accept (QR) codes

### ISSUE THREAD

**Issue by berlincount** [winauth/winauth#296]
When importing codes (in this case, AWS MFA) from 'Show Secret Key', scanning the QR code in the latest Google Authenticator yields a message about the Barcode being invalid (URL format not understood, I guess?), entering the secret manually produces different codes than WinAuth 3.3.7 itself (format differences?) ...

**Comment by winauth** [comment]
I tried this on my own AWS key, and it worked fine. Perhaps there's something in the name that's causing the issue. Are you able to send me the details so I can look at it? Take a screenshot of WinAuth showing the QR code and email to winauth@gmail.com

**Comment by berlincount** [comment]
done! :)

**Comment by winauth** [comment]
Thanks, looks like there's a space in the name and a colon that isn't being encoded properly. For now you could just rename it so it can make it work, till I get a fix. Remove the colon and space.

**Comment by berlincount** [comment]
yupp, that works. the codes generated are also okay in that case. thanks!

**Comment by denry123** [comment]
how can i fix this thing PC got reformated so i cant open my acc.

**Comment by denry123** [comment]
![image](https://cloud.githubusercontent.com/assets/18154430/14127557/6ded9978-f64b-11e5-9d51-71c7a5401ee7.png)

**Comment by winauth** [comment]
@denry123 don't just post on someone other issue.

If you reformatted your pc, you need to restore it from a backup. If you don't have a backup, there is nothing anyone can do.
