### ISSUE TITLE
Unable to "Add" to create or import my authenticator

### ISSUE THREAD

**Issue by WhosUnRated** [winauth/winauth#298]
There is no add button it, it just shows me the cog and the message to click "add" but it doesn't exist.

**Comment by winauth** [comment]
Can you post a screenshot

**Comment by winauth** [comment]
Is your winauth.xml file set as readonly or in a folder that is marked as readonly?

**Comment by WhosUnRated** [comment]
The readonly solved it by the looks of it never changed anything myself but it was working fine before thanks
