### ISSUE TITLE
I woke up and my xml file was blank...

### ISSUE THREAD

**Issue by hunterhhh** [winauth/winauth#301]
I'm stupid and didn't make any backups but I definitely will from now on.
I read a lot online and I have my PCP info from my regedit, but I don't know where to go from here.
Help plz !!!! :((((

**Comment by hunterhhh** [comment]
An unknown error occurred:'.',hexadecimal value 0x00, is an invalid character. Line 1, position 1.
'.',hexadecimal value 0x00, is an invalid character. Line 1, position 1

**Comment by winauth** [comment]
Can you email it to winauth@gmail.com

**Comment by winauth** [comment]
Did you get my message by email?
