### ISSUE TITLE
about other language

### ISSUE THREAD

**Issue by keysersoze88** [winauth/winauth#302]
As I am a c# beginner and my english is pool.....I just want to konw how to use the ILMerge to merge the language dlls. Or there is some other Available solutions.

Thanks Reply.

**Comment by winauth** [comment]
ILmerge is the simplest way to merge everything. This is the command I use within a batch file.

```
ILMerge.exe /out:WinAuth.exe /internalize bin\Release\WinAuth.exe ^
bin\Release\Authenticator.DLL ^
bin\Release\BouncyCastle.Crypto.DLL ^
bin\Release\zxing.dll ^
bin\Release\zxing.presentation.dll ^
bin\Release\MetroFramework.dll ^
bin\Release\InputSimulator.dll ^
bin\Release\ICSharpCode.SharpZipLib.dll ^
bin\Release\Newtonsoft.Json.dll ^
bin\Release\HtmlRenderer.dll ^
bin\Release\HtmlRenderer.WinForms.dll ^
bin\Release\NLog.dll

```

You need at least ILMerge 2.14.1208 for building WinAuth 3.4,

**Comment by keysersoze88** [comment]
Thanks for your replay.

I think I might let you misunderstood. 

I can use the ILMerge to merge the dlls which you list above into winauth.exe and it can running good.

But its language is English.I try to merge the "bin\Realse\zh-CN\WinAuth.resources.dll" into the winauth.exe, but it does not work.its language is still the English.

So my doubts is how to merge the language resource dlls into winauth.exe with the ILMerge.

hope for your replay. Thanks.

**Comment by winauth** [comment]
The CN isn't complete. It was added because some text was translated, not all. I still need to extract the rest of text English text, and then it all need to be translated properly.

So, for now, it's pretty much only English.

**Comment by keysersoze88** [comment]
well，I get the point

thank you.
