### ISSUE TITLE
Please verify your humanity by re-entering the characters below

### ISSUE THREAD

**Issue by Phyxion** [winauth/winauth#303]
I get this warning messagebox when trying to authorise the Steam Authenticator with the code received through email. However, I cannot enter this anywhere.

**Comment by Phyxion** [comment]
FYI, I also get this warning at the Login with Username / Password but there I do get an input box. The next screen though it doesn't show me an input box.

**Comment by winauth** [comment]
Looks like they've changed something, since the captcha is now requested for the email code too, which wasn't happening before. Even the Steam website is asking for a captcha twice if you try and login.

I'll look into it.

**Comment by winauth** [comment]
Wonder if that was a temporary Steam glitch, since it doesn't seem to be happening anymore. Can you try again.

**Comment by Phyxion** [comment]
Still happens. Sign in a lot of times (on Steam) until you get the captcha code. Then you'll need to enter it at the authorise screen as well.

**Comment by winauth** [comment]
It happened yesterday when I checked it out, but then later and today it doesn't. Odd. Make sure you're on latest beta, 3.4.19, then can you turn on logging. Run winauth with "-log debug" option. i..e go into Properties for winauth.exe and set it to:

c:\path-where-you-have-winauth\WinAuth.exe --log debug

Start WinAuth and try again. It'll create a winauth.log file (in the c:\Users\<username>\AppData\Roaming\WinAuth folder).

Can you email it to me. winauth@gmail.com
