### ISSUE TITLE
Can't save confirmation and login info for Steam.

### ISSUE THREAD

**Issue by linhongjun** [winauth/winauth#304]
Restart WinAuth and I have to input username and password to login again. I have checked both options while inputing username and password.

WinAuth3.4.19.1
Windows 7 32bit

p.s. Unfortunately, we don’t support that file type.  LOL I can't upload txt and zip file now.

**Comment by linhongjun** [comment]
Unfortunately, we don’t support that file type.  LOL I can't upload txt file now.

**Comment by winauth** [comment]
Can you add "--log debug" when you run WinAuth.

Right-click icon, Properties, and and --log debug to end of WinAuth.exe

**Comment by winauth** [comment]
It'll create winauth.log in same fodler or in c:\Users\<username>\AppData\Roaming\WinAuth. Email it to winauth@gmail.com

**Comment by linhongjun** [comment]
I sent the email.

**Comment by xDiglett** [comment]
Having the same issues

**Comment by Phyxion** [comment]
Same issue, confirmation login isn't saved.

**Comment by winauth** [comment]
Can anyone with this issue, download [3.4.20](https://winauth.com/downloads/3.x/WinAuth-3.4.20.zip) and add logging by running it with "-l debug" (or "--log debug"). It'll create winauth.log in the in the folder of winauth.xml, or in \Users\<username>\AppData\Roaming\WinAuth.

Please email it to me at winauth@gmail.com.

This log file will contain your secret key. You can edit the file, search for "secret" and X out any codes after that. Please don't delete the lines.

**Comment by Phyxion** [comment]
What's changed in .20? I don't see any recent commits.

**Comment by winauth** [comment]
I hadn't pushed changes, there now. 3.4.20 pushed early really to help identify this issue.

Added more diagnostic logging. Auto-confirm to work on existing confirmations. Silent auto-confirm. Added auto-confirm, into NET 3.5 build.

**Comment by linhongjun** [comment]
Problem exists. Still can't save confirmation info. I will post log later.

**Comment by linhongjun** [comment]
log file emailed. replaced many many secret info.

**Comment by winauth** [comment]
Thanks for logs. It looks like something is clearing the session information. I'm seeing this problem in other issues, where it gets cleared after being saved for a while (couple days). Not sure what it is yet, but still looking into it.

**Comment by winauth** [comment]
Please try 3.4.22. Fixed a problem where session data was being cleared.

**Comment by linhongjun** [comment]
Thank you. It can be saved now.
