### ISSUE TITLE
[Feature Request]Start with Windows

### ISSUE THREAD

**Issue by linhongjun** [winauth/winauth#305]
Maybe useful for private computer.
At least I need this feature because each time I have to input code for Steam starting.

**Comment by winauth** [comment]
Click the Cog icon to get menu, there is a "Start with Windows" option.

**Comment by linhongjun** [comment]
I can't find it.
![1](https://cloud.githubusercontent.com/assets/16095518/13688277/c22cf622-e75b-11e5-822b-23d459075ef2.jpg)
