### ISSUE TITLE
No Start with Windows option in menu with 3.4.19

### ISSUE THREAD

**Issue by linhongjun** [winauth/winauth#308]
![1](https://cloud.githubusercontent.com/assets/16095518/13704757/6df0df92-e7d8-11e5-97d2-18f80a1c8c0c.jpg)
![2](https://cloud.githubusercontent.com/assets/16095518/13704756/6dd296b8-e7d8-11e5-9356-e2e2938cdada.jpg)

But I can enable it in winauth.xml file.
It's removed from stable version?

**Comment by winauth** [comment]
The option isn't available if you are running in portable mode. This is when your winauth.xml file is in the same folder as WinAuth.exe, i.e. not in the usual place \Users\<username>\AppData\Roaming\WinAuth.

Move winauth.xml and winauth.exe into seperate folders.

**Comment by linhongjun** [comment]
In that way, I have to backup it while reinstall OS. Saving config files in system driver is not convenient.
