### ISSUE TITLE
Auto-confirm problems

### ISSUE THREAD

**Issue by AnotherRandomGuy** [winauth/winauth#310]
Hello.First of all thank you for you job, nice program.Secondly sorry for my English if something wrong with it.
I found several problems in the auto-confirmation (only confirmation of sales) . the first is that objects created before clicking "check every minutes" not confirmation at all.So, first you have to press the "check every minutes" and "auto-confirm" and only then to put items on sale in Steam. And then there is the second problem, while auto-confirming and placing the item for sale on Steam in same time it is produces an error "confirmation failed" and after that winauth no longer tries to confirm for sell the object that received the error.As result you must  remove the object from the list of "waiting for confirmation" and put it up for sale again, or confirm the sale manually in winauth.In General, in my opinion, winauth must scan tab "confirmation" and confirm all the existing lots.And do it untill it confirms all available items.
Thank you for your attention, I hope I have described the problem clearly, as far as I allows my English language

**Comment by winauth** [comment]
Thanks for pointing this out. Your English is fine.

I'll look into it and come back to you.

**Comment by AnotherRandomGuy** [comment]
Hello.All described problems are solved, thank you so much for your job.And also thank you for silent mod.
Found a small detail in silent mod confirmation, If you receive the error "Confirmation Failed" then you still have a pop-up window.
