### ISSUE TITLE
no oauth token in response

### ISSUE THREAD

**Issue by kodygardner** [winauth/winauth#311]
idk why this is showing up

 System.Net.WebException: The remote server returned an error: (503) Server Unavailable.
   at System.Net.HttpWebRequest.GetResponse()
   at WinAuth.SteamAuthenticator.Request(String url, String method, NameValueCollection data, CookieContainer cookies, NameValueCollection headers)

**Comment by winauth** [comment]
Steam or your internet is down.

What were you doing?

**Comment by kodygardner** [comment]
my internets fine and steam is up still not working

**Comment by winauth** [comment]
Still don't know what you are trying to do or on what version. Help me help you.

**Comment by kodygardner** [comment]
im using version 3.4.19 im trying to set up the steam guard thing and after i enter the code from my email it says no oauth token in response

**Comment by winauth** [comment]
Create a shortcut to WinAuth.exe and right-click, Properties, add "-l debug" (no quotes). Or use Start->Run, and find winauth.exe but add " -l debug". It will create a log file called winauth.log in same folder or c:\Users\<username>\AppData\Roaming\WinAuth".

Start WinAuth, try what you were doing again, send log file to winauth@gmail.com

**Comment by kodygardner** [comment]
sent it

**Comment by winauth** [comment]
Thanks. Do you have any AV, malware, firefall software that could be blocking outbound access?

**Comment by kodygardner** [comment]
nope

**Comment by winauth** [comment]
Your log file just has one entry, didn't even seem to get to the point of entry email code. It just failed to connect to the Steam server in the first place, with the 503 error. Can you view this page in your browser?

https://steamcommunity.com/login?oauth_client_id=DE45CD61&oauth_scope=read_profile%20write_profile%20read_client%20write_client

**Comment by kodygardner** [comment]
ya that just logs me into steam

**Comment by winauth** [comment]
When you created that log file you sent me, did you actually login? If not, can you try again to the point where you enter the email code.

Otherwise, all I can see is WinAuth is just getting a "503 Server Unavailable" error. It's trying to connect to Steam but something is blocking it. Either your machine, router, DNS server, or Steam itself. Perhaps you can try on another machine. Try and remove anything you think that might cause it to fail, like VPNs, web proxies, or DNS proxies.

**Comment by hailhaven** [comment]
I am experiencing the exact same problem. I get that error when I enter the code from my email.

**Comment by winauth** [comment]
Follow the instructions above and send me the log file.

**Comment by winauth** [comment]
Please try 3.4.22 and let me know if still persists.

**Comment by winauth** [comment]
I think I've finally fixed this. https://winauth.com/downloads/3.x/WinAuth-3.4.23.zip

.Net has a bug in its Cookie handling in some version, causing ".domain.com" to saved rather than "domain.com". Steam didn't like it.
