### ISSUE TITLE
Does .net 4.5 build provide any advantages over .net 3.5 build?

### ISSUE THREAD

**Issue by AndrewSav** [winauth/winauth#312]
Does .net 4.5 build provide any advantages over .net 3.5 build?

Thanks!

**Comment by winauth** [comment]
Two main things. We're able to use more efficient background task handling, which is primarily better for the Steam trade confirmations. 3.5 version will have a delay in startup if you use Steam. 

Second thing is .Net 3.5 doesn't support latest version of TLS (1.1/1.2), which is the recommended protocol for connecting to secure web services, e.g. https:

Servers in the future could not accept request from older clients that could stop WinAuth connecting and so break functionality.

NET3.5 version was intended to allow use of WinAuth on out-of-the box Windows 7 machines. It isn't supposed to be the default. Although I will try to keep it fully working, but eventually it will get discontinued.
