### ISSUE TITLE
Why WinAuth takes much time to load at startup?

### ISSUE THREAD

**Issue by linhongjun** [winauth/winauth#313]
Each time I run it and type password, it takes nearly one mintue to show main window.

I have over 15 records in it.

Will it connect to interneet while loading?

**Comment by winauth** [comment]
It tries to Sync time with servers, which needs connection to the internet. This isn't the most efficient, as it's done for each authenticator. It also doesn't have a small timeout, so can take longer if there is a problem. I'm working on making it better.

**Comment by linhongjun** [comment]
SDA is fast while starting up. Is it possible to start up and type password at first and sync time after that?

**Comment by winauth** [comment]
SDA does the sync in a separate task, although does it needlessly every second until it gets an answer. If Steam is down, it's doing to issues a load of requests.

However, we don't know what type of authenticators you have until it has been loaded. SDA can only handle Steam. so it can do it indiscriminately.

The basic WinAuth was written 6 years ago, and as I mentioned, definitely could do with an update in this area.

**Comment by linhongjun** [comment]
I added a lot of authenticators, more than ten.
