### ISSUE TITLE
Error trying to start WinAuth - Need Help

### ISSUE THREAD

**Issue by Shiftlol** [winauth/winauth#314]
This is the error that i got after i downgraded from win 10 to win 8. Even after upgrading again to win 10 its the same issue. How can i fix this so i dont need to remove my auths from all my accounts?

http://puu.sh/nPRWd/e051fcb4ee.png

**Comment by winauth** [comment]
That looks like an error saying the winauth.xml file has been corrupted. If you find it in Windows Explorer (c:\Users\<username>\AppData\Romaing\WinAuth\winauth.xml), you'll probably see it is zero length. Meaning there's nothing there.

You need to restore it from a backup.

**Comment by Shiftlol** [comment]
perfect worked thank you! :)
