### ISSUE TITLE
[Steam Confirmations] Level icon fails to load

### ISSUE THREAD

**Issue by Toff-kun** [winauth/winauth#316]
![sshot-282](https://cloud.githubusercontent.com/assets/10385850/14002348/1b725f22-f154-11e5-9991-57b44585b2ab.png)
Never got that image to load properly. Other images load successfully, but the level is shown with text and an empty icon placeholder.
Any chance this can be fixed or is that a bug on Valve's side?

**Comment by Toff-kun** [comment]
Why has this been closed? It doesn't seem to be fixed in 3.5.0. Or is it something that only Valve can fix?

**Comment by winauth** [comment]
Sorry if this got caught up in my clearing up.

It isn't really missing much information as it's just the level number. However, on mobile the box is styled with CSS to be circular, have a different background, or use a background image. WinAuth is using a simplistic HTML render that doesn't evaluate these too well.

It really isn't worth the effort of including another HTML renderer with huge overheads just to display this coloured circle.

**Comment by Toff-kun** [comment]
Ah, I see. Sure, no problem at all, haha, just knowing the reason why it's not displaying properly is enough for me. It's a very minor thing, just wanted to make sure it's not a coding typo or something. Thank you once again for your amazing work on WinAuth! :)

**Comment by winauth** [comment]
No problem. I did try and solve it - sorry for not updating - but, yeh, the effort wasn't worth it :)
