### ISSUE TITLE
Strange window

### ISSUE THREAD

**Issue by linhongjun** [winauth/winauth#320]
![1](https://cloud.githubusercontent.com/assets/16095518/14140337/fae7475c-f6aa-11e5-8a7f-39e2fdc6d976.jpg)

Most of time, after startup of WinAuth, the window became strange like picture attached.

**Comment by winauth** [comment]
That's an odd one. Do you have it set to AutoSize or a specific size? Does it correct itself if do anything, especially minimize and restore?

**Comment by linhongjun** [comment]
I use autosize. No correction by itself. But it doesn't affect my use of auth function.
May be caused by too many auth added?
![1](https://cloud.githubusercontent.com/assets/16095518/14161268/dd492728-f714-11e5-9e00-731532ea3995.jpg)

**Comment by Efreak** [comment]
[Same issue](http://a.pomf.cat/ydofgb.png). I have [27 authenticators](http://a.pomf.cat/rqtycv.png) added. Instead of having space at the bottom for the add and settings buttons, the bottom of the last item, the scrollbar down button and the add button are missing, and the settings button is off to the right.

**Comment by Efreak** [comment]
I compiled the latest code myself and it seems fixed. For some reason after updating from git and compiling, I'm getting version [3.4.15](http://a.pomf.cat/lqhoak.png), not [3.4.23](https://winauth.com/downloads/3.x/WinAuth-3.4.23.zip).

**Comment by winauth** [comment]
3.5.0 ?

**Comment by Efreak** [comment]
I'm not having the issue anymore at all. I usually run my own self-compiled builds, not those downloaded from the website. I also don't update as often as I probably should. As mentioned above, the official 3.4.23 BETA didn't have the issue

For some reason my git repo was tracking my fork and not the main repo. Fixed, pulled, compiled, and works fine.

Also, the copyrights ([2014](http://i.imgur.com/3e8WxrA.png)/[2015](http://i.imgur.com/5AuiJXm.png) are outdated.

**Comment by winauth** [comment]
Thanks, I'll mark as fixed. If it comes back, let me know.
