### ISSUE TITLE
My XML file cleared itself.  Lost all my authenticators.

### ISSUE THREAD

**Issue by elyina** [winauth/winauth#325]
So yeah like it says in the title, I woke up today and my XML was just completely cleared.  I lost all my authenticators.  I also forgot to make a backup.  I've read there's an automatic registry backup but I have no idea how to use this and can't find anything on google. Send help.

**Comment by winauth** [comment]
https://winauth.com/lost-forgotten-password/ at the bottom

**Comment by elyina** [comment]
Right, but what do I do with it after that?

**Comment by winauth** [comment]
Email it to me, winauth@gmail.com

**Comment by elyina** [comment]
Sent it

**Comment by winauth** [comment]
I'm working on it.

**Comment by elyina** [comment]
Thanks!
