### ISSUE TITLE
Crashs at start up straight away, can't login to steam without this

### ISSUE THREAD

**Issue by PolygonError** [winauth/winauth#326]
"An unknown error occured: '.', hexadecimal value 0x00, is an invalid character. Line 1, position 1.

'.', hexadecimal value 0x00, is an invalid character. Line 1, position 1."
Can't open winauth, so can't get into steam!

**Comment by winauth** [comment]
Your winauth config file is corrupt. If you look at it, it will be zero length. Which AV are you running? I think there might be something that is stopping it writing out properly.

Needs to be recovered from a backup. If you made a copy of the \Users\<username>\AppData\Roaming\WinAuth\winauth,xml then restore it. If you made a backup with the Export feature, delete the zero length winauth.xml file, start winauth, click add and select the exported file.

If you don't have backups, follow the "provide your registry backup" at the bottom of https://winauth.com/lost-forgotten-password/.

Email it to winauth@gmail.com
