### ISSUE TITLE
Where is the authentication data stored?

### ISSUE THREAD

**Issue by heinrich5991** [winauth/winauth#327]
Is it the `winauth.xml` in application data? I'm wondering whether my normal backup routine covers WinAuth.

**Comment by winauth** [comment]
Yes, by default it's in \Users\<username>\AppData\Roaming\WinAuth. Bear in mind, depending on your settings, this file might be encrypted with your Windows account so would not be usable if restored to new installation.

Therefore I would recommend you periodically use the "Export...." option to create a password-encrypted backup, which is backed up too.

**Comment by heinrich5991** [comment]
Thanks!
