### ISSUE TITLE
GW2 isnt connected anymore but needs a key to connect

### ISSUE THREAD

**Issue by Kimimoto** [winauth/winauth#328]
My gf had to authenticate again but GW2 wasnt connected to WinAuth anymore. To connect it again she needs a key though that cant be aquired. Didnt save the first secret key..

**Comment by winauth** [comment]
Follow instructions at bottom for "provide your registry backup" in https://winauth.com/lost-forgotten-password/

Email it to winauth@gmail.com

**Comment by Kimimoto** [comment]
Done!
