### ISSUE TITLE
Confirmation option didn't show up

### ISSUE THREAD

**Issue by Naristracrates** [winauth/winauth#330]
So I preconfigured the latest release of winauth to the best of my knowledge.  A game came out, so I wanted to sell some inventory in bulk.  I noticed that these items had to be confirmed.  I right clicked in winauth, and there was nothing about auto confirmation or anything that was shown on the internet.  So I decided to reconfigure from scratch, but now my free SMS isn't working, which isn't this organization's concern.  It is just frustrating, because I felt like I had no choice but to restart everything I worked to configure.  I can do it again, assuming i can get this SMS number to work again, because I need that number inorder to change my SMS number in Steam.  I feel kind of screwed.

Assuming I can get everything configured again, what do I need to do to get the auto confirmation option in the winauth program?

Thanks again!

**Comment by winauth** [comment]
Make sure you are latest beta 3.4.x. If you created a SteamGuard in WinAuth using 3.3.x, you will need to remove it from your account and one back again. If not, all should be fine.

Once SteamGuard added, you can right-click and choose "Confirmations...". You must select "remember me" and once logged in you'll see the current trade confirmations and option at the bottom to check every n minutes.

**Comment by Naristracrates** [comment]
I was in version 3.3.7.  That is why I don't think there will be much of any difference.

**Comment by giddymuched** [comment]
I don't use sms text nor do I know any adult who does.  As a developer please back channel our disdain.
