### ISSUE TITLE
Confirmations not working

### ISSUE THREAD

**Issue by zebn** [winauth/winauth#332]
Confirmations not working, always got error, once I create trade offer

aut ver  3.4.23

net 4.5 and 3

http://puu.sh/olAUs/09f135acb1.png

http://puu.sh/olB9G/ee33cd9806.png

**Comment by winauth** [comment]
Which Windows versions so you have (XP/7/8/10 and 32/64 bit?), and which .Net is installed on your machine?

**Comment by zebn** [comment]
XP 32bit virtual machine installed net 3 and 4

**Comment by winauth** [comment]
Make sure you have .Net 3.5 SP1 installed. If you do, remove and re-install it.
