### ISSUE TITLE
how to use winauth with another pc? 

### ISSUE THREAD

**Issue by vako211** [winauth/winauth#335]
how can i use winauth with another pc? i  mean if i  changed pc or windows how to get back my original winauth ? pLEASE help me

**Comment by winauth** [comment]
Create and restore a backup of the winauth.xml file, or use the WinAuth "Export..." option and re-import it into the new PC.

**Comment by vako211** [comment]
how can i create new one and where can i find winauth xml file

**Comment by vako211** [comment]
it asks fro passwor again but i didnt remmeber that password :/
