### ISSUE TITLE
Refresh is not working

### ISSUE THREAD

**Issue by MhmdAMiNE** [winauth/winauth#337]
The refresh button for steam confirmations is not working on 3.4.23 beta version
When i click it to reload the new confirmations, nothing happens

**Comment by winauth** [comment]
Is there a delay where the mouse changes for a couple seconds? Can you add logging (add "-l debug" to the winauth.exe) and send me the winauth.log file.

**Comment by MhmdAMiNE** [comment]
Yes, the mouse changes for seconds.
I sent you the log file.

**Comment by winauth** [comment]
Thanks. Got the file. Nothing unusual.

Can you talk me through what you do, since I tried on mine and Refresh works as expected. If I have the window open, go into Steam and add a new Trade, come back and click Refresh, it appears. What about you?

**Comment by MhmdAMiNE** [comment]
When I go to confirmation and confirm the trades then make a new trade on steam and go back to winauth to refresh, it does not work,
I must close the confirmations window and open it again to reload the new confirmation

**Comment by winauth** [comment]
Do you use remember me? Do you have polling on?

**Comment by MhmdAMiNE** [comment]
Yes , I use the remember me
I don't know what do you mean with polling? do you mean auto confirm?

**Comment by winauth** [comment]
Yes, sorry, are you using auto-confirm?

**Comment by MhmdAMiNE** [comment]
nop

**Comment by MhmdAMiNE** [comment]
If you want, I can record the screen for you to see what happens

**Comment by winauth** [comment]
Sure. It may help shed some light.

**Comment by winauth** [comment]
Fixed in [3.4.24](https://winauth.com/downloads/3.x/WinAuth-3.4.24.zip). Can you please check.

**Comment by MhmdAMiNE** [comment]
It's working now... Thanks :+1:
