### ISSUE TITLE
Installation issue

### ISSUE THREAD

**Issue by kboykin** [winauth/winauth#338]
I think this is .net related, but I can't get the application to install correctly one one machine. My other computer it works fine. 

Running the .exe manually launches the application, but it doesn't appear in add/remove or in task bar.

Windows7 64, .Net 3.5/4 installed and fully patched. Using current\stable version. 

![error](https://cloud.githubusercontent.com/assets/18683583/14824493/3a6ed616-0ba4-11e6-9f34-5c6e17b96b39.jpg)

**Comment by winauth** [comment]
Not quite sure what that is, although Googleing it suggests an issue with ClickOnce applications. Is that how you're installing? You could just download the winauth.zip file and run it directly.

**Comment by kboykin** [comment]
The downloaded zip file produces the same result. I am still investigating what is different on this machine.
