### ISSUE TITLE
Add auto confirm delay

### ISSUE THREAD

**Issue by Phyxion** [winauth/winauth#339]
The auto confirm is going too fast, you cannot sell items anymore when your cards are being auto confirmed by WinAuth due to Steam's request/s limiter.

**Comment by winauth** [comment]
What's the limit?

**Comment by Phyxion** [comment]
I don't know what the exact limit is but SIH is using a default delay between 2.5s and 5s for the inventory.

**Comment by winauth** [comment]
Ok, thanks, I'll add a delay in there.

**Comment by winauth** [comment]
Fixed in [3.4.24](https://winauth.com/downloads/3.x/WinAuth-3.4.24.zip). Can you please check.

**Comment by Phyxion** [comment]
Thanks, it's working now.
