### ISSUE TITLE
Bought a new computer and cant get into my steam, dont know what to do

### ISSUE THREAD

**Issue by hinchy8922** [winauth/winauth#340]
Today i bought a new computer and ive reinstalled steam and winauth but i cant get into my steam account, I think i have the recovery code here which i took earlier, before i got rid of the old computer but i cant see where i use this code to gain access to my steam account on my new computer.

**Comment by winauth** [comment]
If you lost or didn't copy your winauth settings across, then you'll need to remove SteamGuard from your account and add it again. Go to the Steam website and login, and choose the "I no longer have access to my Mobile Authenticator codes".
