### ISSUE TITLE
Lock button

### ISSUE THREAD

**Issue by My1** [winauth/winauth#344]
well as simple as the title says. when you have password add a button which locks withauth and throws all the (potentially sensitive) RAM data into oblivion.

**Comment by winauth** [comment]
It would give a false sense of security. In a managed environment you can't guarantee any memory wiping, plus your data was already readable in RAM, so is really pointless. Close the app is the simplest way.

**Comment by My1** [comment]
oh you cannot overwrite the memory? too bad, but at least a UI lock would be nice.
when you use yubi the ui gets also locked on removal , just so by the way.

**Comment by My1** [comment]
but again why is such a lock in place when using yubi? I mean when you cannot actually wip the ram and the data is already in ram wouldnt it be pointless as well?
