### ISSUE TITLE
Confirmations not working

### ISSUE THREAD

**Issue by Delioo** [winauth/winauth#346]
Hello I have a problem:
 
http://abload.de/img/abairjcj.png

I have Windows 8.1

**Comment by winauth** [comment]
Can you include  the message in that box, as it contains useful error information.

**Comment by winauth** [comment]
Never mind. I found it in the submitted error logs. The error is because you're running .Net 4.0. Are you able to upgrade to 4.5? If not, try using the [WinAuth for .Net 3.5 version](https://winauth.com/download/)
