### ISSUE TITLE
How can I import from SDA ?

### ISSUE THREAD

**Issue by RumbleRamy** [winauth/winauth#347]
Is there a way to import from Steam Desktop Authenticor to WinAuth ?? please a solution
I dont want to disabled SDA and wait another 15 days

**Comment by winauth** [comment]
Click Add, choose Steam, use "Import SDA" tab.

**Comment by RumbleRamy** [comment]
I dont see any tab saying that, there is just login

**Comment by winauth** [comment]
Are you latest version, 3.5.0?

**Comment by RumbleRamy** [comment]
Oh, I realized that I was using an older version.
I downloaded the new version and it works perfectly :) thanks
