### ISSUE TITLE
Invalid response from Steam (2)

### ISSUE THREAD

**Issue by rotom22** [winauth/winauth#349]
I have no idea what I'm doing wrong.
http://i.imgur.com/zoWck7T.png
Happens after I enter the code from my email. 
Tried redoing my phone number in Steam, didn't work. Haven't waited that long, so it might be the same as #247, but it says 2 instead of 84, so I'm not sure.

**Comment by winauth** [comment]
Do you use Family settings? Has the phone number been used on a different account? They also have limits on how many SMS can be sent per day, so try again the next day.

**Comment by TheBilbo** [comment]
Have similar problem. Cant add auth. Instead of topic starter I haven't error. But I dont get steam mail with confirmation code. Tried a lot of time. Nothing

**Comment by winauth** [comment]
@TheBilbo These are two different issues. Yours is just on Steam's end.

The error after entering the email code is likely related to the account or Steam. If it accepts the email code, the next thing is to send the SMS message. I don't know what Steam's error 2 indicates other than what I said above, and also checking your PC's time is correct.

Can you create an authenticator in any other app, like Steam Desktop Authenticator or the (emulated) version of the Steam's official client?

**Comment by TheBilbo** [comment]
@winauth nvm, looks like it was steam lag or mail host lag. Several hours later I got all my auth try codes at similar time.
I was a bit nervous because of new winauth bild as it said it overwritten old data and I didn't have backup. Thank you for answer though =)
