### ISSUE TITLE
Confirmations-login error

### ISSUE THREAD

**Issue by LULMEMERLUL** [winauth/winauth#350]
Hello and thanks for your work !

My Problem is that when I want to enter my steam login data I get an error message.
http://prntscr.com/b5xi5h

I was wondering if the problem is that I am running WinXP and hope you can help me.

Thanks in advance !

**Comment by winauth** [comment]
Make sure you are running the [.Net 3.5 version](https://winauth.com/downloads/3.x/WinAuth-3.4.24-NET35.zip).

Also try uninstalling and reinstalling .Net 3.5 SP1.

**Comment by LULMEMERLUL** [comment]
I reinstalled .Net and when I open the WinAuth .Net 3.5 version I get this error message 
http://prntscr.com/b6cihp

**Comment by winauth** [comment]
Can you click the Show Details button, and copy the text and paste it here.

**Comment by LULMEMERLUL** [comment]
-----BEGIN PGP MESSAGE-----
Version: BCPG C# v3.4.24.19

hQEMA53DDyNpqwwqAQf/Xsny4oFQxcMJ1mlRKdcO92zUWDP1TJLeI1wvyfn3KlCC
UlLK42bqjHrLb32J2i+xpV3ww72xAWL8b4tZAYP4AgY8Tb0Yyorn4L0XwfQ2W8rD
2Y2lkTuY6fP13r8B+pJ0FwCSsHnuVnYDAvBGZCYLeJOFOflbbkLUYMMfGjRhhx1F
HuRjzuybfHUiPHr5tfg9ran2t47jlbPcHqmdyie+cv0A/cd7e5+3IKk0r8MM2BO/
YDrlEKKAWqJDkBZApRBdFFdJUUdWkNIAn66J/rjN4nFRwxZCCVWD23R2squoQ/47
H6ou8C1EksGTLMlUtoUdvXnOAQMHs+ah7CbcBxWGONLJ2wEWlaLp2oZw++upPo/z
H5jj/YIZ4G1oGotTaysdCPRcpW9h+o3na7IW9r6MHc6M83lxoCn4hpiVMQRIlkJ8
MBIkmkGFQq5w3prhpEMlBeX8G1xRPGLTSmNdF+sJ/8VSA3OCQR9TotfyWN75InfJ
LW5AePpFm2Cg5pIvN7TBaPHwvrQTvM0prkUz105Bsm0ohxIzzrwP7OzcSjaKl4xk
ALYz/WsroRraPeRpMlObU7TnwKCNlDAxrrMUz9DRbhz88ky4wjPT/CNvpLWZEroZ
n36YXWqWwrhqIyKAlC5N8cVto6trVPBoNUv08wpv7rP2hO66E/pl7TMmof7qOk1S
+Qmy8QrJy84/mLTihLdfZsfH1IL4S+8F902B7Ir69xC57ik6Wwq9G4UchsDfoTV1
t1mKdNtoCI6OiXl8dztb0/SsdaYQEI8/jw18GHFhwFjQrH/EwvRZprsvNuRNH3jf
oGdxCn9kSZ3c779QxVHJkDG6aSTBronuEfJuVux2wEff0GWwm6RKblwgNVroG5nN
gf2gBxdEJc4ZLUyQd4TgYGyrQnZKdJJTq0/qSZLLlPPLyv4yx8JhW546O+RgYLqz
pT+yVrrSEExjybjB5M5XUmRmaxy4oL27TKVbyYzX9ekZfm7xncEJ1VdzqCu78oA8
m5kOgKNRQJTvTgq2aSZ8SrKvCoEnHpSOQwTizfse754eQ9QMloX9mCpbYFg88w9S
TdKR9caW3u6ZG031pZ6zWFI8gALeZ967cGFX68uLz8+08YTUV7B3h4ywRmA2o//T
YX2/Gz5ta1cqX1XrPDSd6KfwNqctqZJyqOZySLiZ4rbPn9YT42AcAFdrmsJEl90S
S4rCLMA32TsDDTW36JumwMx6/kXpJ2lkjE+YLPVtebBAPYq4ZfUNw1T9fis8klig
ZUpHdAziQI393vjdhCAuLhhQ3/EHFdIe1wGkVulAgOlg8h7q1AU2GG1MbbLKMhyr
0N9Kzy6Et7Z9c8+UxS4EUkKrKdtqmR/4gBBL6ubpZIyUBU0ic29X2CROtBjNtmUl
mmAh5plx2amQyjeRY3xNRaRjspakP/tV6PSQZRc6EDyXfzEjb3qw3OXrDMLYniAB
SfGOiNMBzcrjA0amRnHsJOjh5nDJn3FqQBXupIqJIwbXjAU7yMfpFuvpj0Rk3Egc
X5qEfxIZtPS5WZ5RhBWUXyZmaLso3TLDxQOZO5/pHLEwOMgpi8BSkQyguEzfWDJu
7qknTgzb3GkhuqufJbQfpXQA0CJeQ8vyEKAOG7Rjcgd2jnirakVOb6n/RL8RZSv/
R3FnTMSPo3fMpg/Jzf5305cvTsNsNcsSEVsoe/qMs+O8d+Q0R/Sfrl9vk0/RhADN
vAT9ellYHSRENTAcGoKuKHrrJhOGiamVb76L9tIKPTr9ABB6RrKwjzoDO4YkG0fz
15IS/fJwkryLzMRlFnVqN7ykLcycIaqe4Ga0SW7jcrLd1U4VNsaWDJoI0VIp9+Nu
kp7Ppp4fa17vV0+UuC9JluuE4jgD9duGZJI6zeuTEgf3c2laC9wGKC9PiivqlDlI
HOlp2g4Pcr0+tHg8XoG+XWyQ0Enk2FQokH5ZRacLisuXUA90t9Z/J3gVRISA+pZ+
WvkyWAeiDL7fXOUEKQzYFahT2TYKRBTUR0BuAdd9lBlvHsQbbJ/g/lF7tZhjg8Zp
Q8mtvllzHF1/JKAAlrnQlHalEc3BRqKNWQ8gfSG0XGmX6dCoKGb8l0+f6jKCgwAD
LLYze5yUW3+KbvfznlamdOCEztJ7ONGWZm28xg5VeSa648n1JFu4dwv6TxI+lKdo
Iy3ULkdjnCSpclvmz5u6zeQjR/mDEAQKar3XQqKoKLneKBrj5n5wT9JUWB03O6Sy
qvRmcL8vT7apZhv/40g90m3wZHAPV+vo+8QgxYXY0qgeGjyUA7jVs6VrqASgoFqu
5AeqSf1DCuHTW0dIP3B2BBgYq1LQiaa0UEorgXe71nFWZ/EAw29nZAO88OTdIljD
Pu6oGUVzNdE6pBrBsCaxZDklPmL3BgiyKivHjEhJx3fcaW31drJ0PttisLgf4HXg
9+Npmq3vxC9SM94d21+NC67ksxeDdSJZKRVXBI1KHV4veTyRlFMUwNdpP/XcUN+O
XLBEfsGxu6srzZKgZZam//MluQUYX1Ts8S41RrwKWLfs0/zHiCPkAulb6DqM+iHs
PgmwCZIFqltYdNt+F75VUXa0rYBSinY5z4sJ/lJXH3lcmn+Cfb0OBEGzFaBRYHpn
0iFF4ns1MNbHD7KmP7rU8SWoM5rZLUyY5WmBW4n7vY9SS3aam/qghrLVnrBPEZyJ
cDywPVFk/E7Fwo7asHQ3FtNnIXGH2YkG5L3WYGXxS/WkM9Bfuy0+f+FfuEcLj/dP
FkasYcAWFVXMtPQMcWn/TrVDkeCd21CzPA6AS70wxUwqKW0Qw8Jx56jIYeNCJADJ
nkGBaMnoStt/bd4iiXnEmhx9nWhmrNRcsiAkkQF0GXKWRrPrzly0MC4thyFNAMkb
C8BJWCWesv5AoBG1tLCXG+jhWTtIhEHzEyPD3AQQA0q7d1gbyZGf0Ukne2LkyrUX
jTXSweWny+tsAhhu/wjqM13mCrBLgTMt5hRTU1NHZ9DPFI4Y/z/PblkW8hbc7EjG
/3p0uDtYgGwy/XbE5NJZK1tX73vkN9dTbWjLL5h6b+SlzLq9FS/Clnv9QYot4eX8
VmVMFa4JWBCDTX5VEcXbY7MAVOeSbIUU9N/9OUZK6+PbpOh5n+YI0MgOFHtsJ07L
KOoXGT97qRC1NAu94Hj3QAdzPmHzAcfZZdFBx7ZvIL1odMaLpxwkhlLftxQPo0RS
oCwXCVaejmtuYYKloS5tItPs2Yikc45lJlH9PyzsjI95T+couFSGSOsJHjSQNENY
AXdcXERA0QNMiMEKMSL2qentxoJa9lcqy6eSFt8qJjJtu9nTgGWpRrWdpWSN3O64
fZJSyLHpVJTfsycEnBFfwhtRhxUZhGXrkiu8tQHR6x5gIFmp/Wv5A9kHJljvBkvM
dtTmFd6Y25OMBzh76djfT1q18TJdrCPklfV1m1uV8WdoarxVNVor7OYmAvFqzCi4
P13WbREIwGJ+mqZi+oFfJG5KFbmSYDoLqeOUnBjKC0HkKLmK/IboZtapsiujoKyY
DX8pD8ikr7a1yknJfHqHxR1rWGtHRBlkqSsTHz81968/9n9CPYx2hol47/erUij+
x3WosefFg9YHSvvK2SzHqXHAeGvwQyPrL/8SYgtDNCgBXnsJAlHtqto6B5Q3B10R
wvlMAcguTGhywBiO0GyrgPjFGxhsbvgHzUsEQ0c462gX0dul+8BCTtUnWlMxz65J
xc1MaSAous6Nd98Fk5F6bj5SkNEgehYPfSxDxVgC3gzwfKPNcRJ/YMkOfnTAFVS3
lxuhfceRkRwuuRj4iBo1BqXGMGSyonPEKj8+AP5KvPL9OexH46yO5oQi2gLJL9oe
TSxlizDZOzNJLhiTV/zRJK4LNCckDPe5TuIXJHhF55ANtG+/Lvv8NDhc2rapNYeV
4SWHNs0qUvLSnNafpM+kZJPlYX5gA6Fp906XH5EQYsqC6dCpResLEQPugTKC9wzc
RyLXQM4O6IE5Zu9L/A==
=AJGv
-----END PGP MESSAGE-----

**Comment by winauth** [comment]
Thanks. I managed to reproduce for version 3.4.24 in with Windows XP SP3 with .NET 3.5, when using German locale. However, the error doesn't happen in the latest version 3.5.0. Can you download that and try again?

https://winauth.com/downloads/3.x/WinAuth-3.5.0-NET35.zip

**Comment by LULMEMERLUL** [comment]
I did what you said and everything works, thanks a lot for your effort. I really appreciate it !!
