### ISSUE TITLE
Support for Nitrokey

### ISSUE THREAD

**Issue by beerisgood** [winauth/winauth#351]
I found nothing about this- only for Yubikey.
So please add support for Nitrokey, like for Yubikey.

https://www.nitrokey.com

**Comment by winauth** [comment]
I'll look at this, but perhaps first, support for smartcards in general.

**Comment by beerisgood** [comment]
Alright. Fair enough

**Comment by beerisgood** [comment]
How is the status?

**Comment by beerisgood** [comment]
*push*
Any updates?
