### ISSUE TITLE
Steam confirmations do not size correctly

### ISSUE THREAD

**Issue by JustArchi** [winauth/winauth#352]
It's shown nice with auto-size option, but I wanted to make it a bit bigger so more confirmations could fit, guess what... :laughing: 

![image](https://cloud.githubusercontent.com/assets/1069029/15474035/3b3097dc-2103-11e6-8a3d-6d345e55df1c.png)

**Comment by winauth** [comment]
Oops. Thanks, I'll fix it.

**Comment by JustArchi** [comment]
Fixed in 3.5 :+1:
