### ISSUE TITLE
Linux version

### ISSUE THREAD

**Issue by ekaris** [winauth/winauth#355]
Since microsoft opensourced .net some time ago and there are compilers of it for mac and linux it would be great to have a Linux port.

**Comment by winauth** [comment]
The only open-sourced .net core, which is a new version of .Net, but not the UI framework. Options are to use Mono, 3rd party WinForms port in Core, or port to GTK.

**Comment by ekaris** [comment]
And why is this closed so quickly?

**Comment by winauth** [comment]
Because I answered it. Please don't create duplicates.

WinForms isn't part of .Net core.
