### ISSUE TITLE
Can't open WinAuth

### ISSUE THREAD

**Issue by Rafax011** [winauth/winauth#357]
Hello! I have really big problem. So: I was normally using computer and WinAuth was working, then my brother came and for "joke" he closed my computer. Now i'm trying to enter the WinAuth, but i get that message: http://image.prntscr.com/image/1115a0b096894aeaab784ca77136547d.png (half of it is in polish, it mean "hexadecimal value 0x00, is an invalid character. Line 1, position 1"). I removed WinAuth 3.4.3 from computer and downloaded 3.5.0, but it still doesn't work. Could someone help me? Thanks in advance!

**Comment by winauth** [comment]
File has been corrupted (\Users\<username>\AppData\Roaming\WinAuth\winauth.xml). If you have a backup, restore it. IF you don't have a backup, follow the instructions at the bottom of https://winauth.com/lost-forgotten-password/ for the registry backup.

**Comment by winauth** [comment]
Send it to winauth@gmail.com

**Comment by Rafax011** [comment]
Already i have deleted token from my account, then deleted files of Winauth and downloaded again. Anyway, thanks for help :)

**Comment by winauth** [comment]
Ok, no problem.
