### ISSUE TITLE
Reset Windows - have winauth.xml but unsure how to use

### ISSUE THREAD

**Issue by DashGit** [winauth/winauth#358]
Hi!

So I've been using WinAuth for quite a while now to protect my accounts, and it's been great. However, just today I had to reset my OS. I had Windows keep all it would allow me to keep, and when I loaded up my computer, to my dismay, WinAuth was blank. I poked around for a while and found where WinAuth is supposed to keep its authenticators (the winauth.xml file, located at C:\User\[username]\AppData\Roaming\WinAuth). Here are the contents of said file:

```
<?xml version="1.0" encoding="UTF-8" standalone="true"?>

-<WinAuth version="3.5">

<alwaysontop>false</alwaysontop>

<usetrayicon>false</usetrayicon>

<notifyaction>Notification</notifyaction>

<startwithwindows>false</startwithwindows>

<autosize>true</autosize>

<left>277</left>

<top>261</top>

<width>0</width>

<height>0</height>

<data md5="[probably shouldn't show this]" encrypted="m">[probably shouldn't show this either]</data>

</WinAuth>
```

Obviously, I censored the things that might contain my vital authentication details. So, my question is: can I use this file to give me access to my accounts again? I could not find anything detailing how one might use this file to restore his or her authenticators. If this is possible, that would be greatly appreciated. I did turn on the encryption that forces WinAuth to only be able to be used on one computer, by the way, but as I said, I only reset Windows, and this is not a different computer, so I believe it should work.

Edit: Thought I should mention that I have 2 recovery codes for 2 out of my 4 accounts that I registered with WinAuth - but again, I have no idea how to use them either.

Thank you again for developing this amazing program, and I hope to be able to use it in the future (with my accounts!)

-Dot_Dash

**Comment by winauth** [comment]
The encrypted="m" means that it has been encrypted with the Window machine key (as opposed to the user account key). I can't say if resetting Windows resets this key or not, but if it acts like a new installation, probably.

The file is right and needs to be in that location. Starting WinAuth should just load the file, or you can copy it to the same location as the exe file.

I would expect you to see an "invalid password" type error.

Do you have any kinds of backups from your previous installation? Backups/exports from WinAuth? Backups of the Windows registry?

**Comment by DashGit** [comment]
Hey!

So, I tried putting the .xml file into the directory where I had the .exe, and it worked. So happy right now - thank you for the quick response and help!

**Comment by winauth** [comment]
Glad you got it working.

Make a backup. Click the menu icon in WinAuth and choose "Export...".

Perhaps you have a new user folder? It should work the same if the xml file is in the same folder as the exe (this is portable mode) or in your user's AppData folder (\Users\<username>\AppData\Roaming\WinAuth).
