### ISSUE TITLE
Battle Net Re-Sync Authenticator isn't working?

### ISSUE THREAD

**Issue by BakuDM** [winauth/winauth#360]
I just updated WinAuth to the 3.5 and now I can't access my Battle Net account, when I use the Authenticador Code provided by WinAuth it fail and give me this code: Error 3, BLZBNTBGS8000000F
And according with [this page](https://us.battle.net/support/en/article/BLZBNTBGS8000000F) it could be either email, password or the Authenticador Code, I am pretty sure that I am using the right email and the right password, so it must be the Authenticador Code, I tried to click on Sync Time to Re-Sync the Authenticador, but the codes still not working.
The Steam Authenticator is working, the problem is just with the Battle Net.

@winauth

**Comment by BakuDM** [comment]
Had to remove the Authenticator and add a new one to be able to access my Battle Net.

**Comment by BakuDM** [comment]
Alright, it's happening again today, so probably WinAuth is having Sync Problems with Battle Net.

**Comment by winauth** [comment]
Can you double-check your PC's time. It's the most likely think causing the problem.

When you Sync Time in WinAuth, wait for the next code. Also be aware, Blizzard blocks you from  using the same code twice, so you need to try the next one (30 seconds later),

**Comment by BakuDM** [comment]
Yeah, my PC's time is right, WinAuth was working normally when I was using the beta release with Steam Trade Confirmations.

And I just tried again now, Sync Time and wait for the next code, the same thing happened.

**Comment by winauth** [comment]
There should be no functional changes with the latest beta and 3.5, certainly nothing in the Battle.net area.

Mine is working, and no one else has mention it yet, hence my suspicion of the time.

Right-click and so "Show Serial & Restore Code". Does it look right? If not, this is the indication that the key is corrupt, which is really the only the other thing that can go wrong when calculating the code. Code = fn(time, key).

Are you using any auto-entering username/password in your browser? Definitely sure it sending the right password?

**Comment by BakuDM** [comment]
Yeah, it's right, I had to remove the older Authenticator and add a new one yesterday, it was working fine until today when it started to get the error again.

I am trying to login on the Battle Net Desktop App.

I will remove the Authenticator from my account and add a new one again.

**Comment by BakuDM** [comment]
The weird part is, I can login through the Browser with the codes, but I can't through the Desktop App, but yesterday when I removed and added a new Authenticator, I was able to login again.

**Comment by BakuDM** [comment]
And suddenly now I can login through the Desktop App again, what the heck is going on, the only different thing I did was deleting the battle.net and us.battle.net cookies. O.o

**Comment by winauth** [comment]
Is it working now?

**Comment by BakuDM** [comment]
For now, yes.
Thanks.
