### ISSUE TITLE
Error

### ISSUE THREAD

**Issue by peterkristel** [winauth/winauth#362]
Winauth don't startup!

![0a991dba41434483680b65f7e9c24e70](https://cloud.githubusercontent.com/assets/13722542/15707402/df6bc816-27f8-11e6-9dd9-d3f22f65416a.png)

[Newsted version]
[Tested older versions but not helping]

**Comment by winauth** [comment]
Your winauth.xml file is corrupt. Restore it from a backup. It's in the folder "\Users\<username>\AppData\Roaming\WinAuth"

**Comment by peterkristel** [comment]
All my accounts are removed ...

**Comment by winauth** [comment]
The file is corrupt. Restore it.

**Comment by peterkristel** [comment]
what file?

**Comment by peterkristel** [comment]
<?xml version="1.0" encoding="UTF-8" standalone="true"?>

-<WinAuth version="3.5">

<alwaysontop>false</alwaysontop>

<usetrayicon>false</usetrayicon>

<notifyaction>Notification</notifyaction>

<startwithwindows>false</startwithwindows>

<autosize>true</autosize>

<left>630</left>

<top>415</top>

<width>0</width>

<height>0</height>

</WinAuth>

**Comment by peterkristel** [comment]
thad?

**Comment by winauth** [comment]
> Your winauth.xml file is corrupt. Restore it from a backup. It's in the folder "\Users<username>
\AppData\Roaming\WinAuth"

Same as password recovery:

https://winauth.com/lost-forgotten-password/

**Comment by peterkristel** [comment]
There is nothing in the export file

**Comment by winauth** [comment]
Obviously. You need to use the backups from **before** it became corrupted.

1. Restore winauth.xml file from a backup, or
2. Re-import authenticators from export file, or
3. Re-add all authenticators from the secret keys you saved

If you didn't make any backups, make any exports, or write down your secret keys...well, first, learn to backup your data. Second, follow the "you’ve been asked to provide your registry backup" instructions from https://winauth.com/lost-forgotten-password/. Post them here with your email.

**Comment by peterkristel** [comment]
Can you add me plzz on steam or skype ?
Skype: jelle.claus1
Steam: JSJGamingBE

**Comment by winauth** [comment]
Not at moment. At work. If you can follow instructions I can solve it.

**Comment by winauth** [comment]
if you can send the backup data, I can recreate your xml file. Closing fir now.
