### ISSUE TITLE
Invalid response from steam status 8

### ISSUE THREAD

**Issue by zikk87** [winauth/winauth#363]
Hello. Guys need your help. From morning have this issue "Invalid response from steam status 8" 
Ver 3.5.0
phone number added
family sharing disabled
![untitled](https://cloud.githubusercontent.com/assets/19707585/15742644/eaea32f6-28c8-11e6-9872-d6e9754c662f.png)

**Comment by winauth** [comment]
It's a Steam internal error. Not sure what it means. What stage is this? Logging in, entering email, or entering activation code?

**Comment by zikk87** [comment]
Hey. Tnx for reply. This msg pop up after i write code reciving via mail.

**Comment by winauth** [comment]
That is when it is sending the SMS. Do you have family settings on, have used that number on another account, or tried too many times in 24 hrs?

**Comment by zikk87** [comment]
Hey. Now all works fine, thanks for reply and for this app. It is very
helpful:) Bye

понедельник, 6 июня 2016 г. пользователь WinAuth написал:

> That is when it is sending the SMS. Do you have family settings on, have
> used that number on another account, or tried too many times in 24 hrs?
>
> —
> You are receiving this because you authored the thread.
> Reply to this email directly, view it on GitHub
> <https://github.com/winauth/winauth/issues/363#issuecomment-224039398>,
> or mute the thread
> <https://github.com/notifications/unsubscribe/ASy2wRCywS8--z85dB3NDfdqHEduI-IRks5qJGGRgaJpZM4Isbpi>
> .
>


-- 
Отправлено с iPhone
