### ISSUE TITLE
Can't login to confirmations menu

### ISSUE THREAD

**Issue by Naristracrates** [winauth/winauth#366]
So I started getting "failed to read confirmations" dialogue box on my bottom right, and it's pretty intrusive, yet I don't want to shut down Winauth.  So I update to 3.5, no big deal, and I login with my credentials in the confirmations menu, and I get a remote server 503 error.  I've double checked that my Steam credentials are the right ones, but logging out of Steam and then re-logging on.  It just happened today where it would say "failed to read confirmations."  Which is bothersome.  I have added the .exe into my windows firewall.

Any suggestions?

**Comment by Sniper296** [comment]
Looks like this is because Steam Community is down. [SteamStatus](https://steamstat.us/)

**Comment by Jiseru** [comment]
When it is down and you have auto-confirmation selected, it will spam the notifications at you if you have the option selected. To the point you just force quit it and you can't change the option since you need to login to change it but you cannot.

**Comment by winauth** [comment]
Thanks, I'll look into the spamming notifications once Steam is up and I can test again.

**Comment by winauth** [comment]
Steam is back, but I've fixed this in 3.5.1.
