### ISSUE TITLE
Error when trying to add steam?

### ISSUE THREAD

**Issue by lololfloss23** [winauth/winauth#371]
Hi, I recently had to get a new OS for my Computer so I re downloaded Winauth so I could get onto my Steam account, only to find this issue when trying to do so
![help](https://cloud.githubusercontent.com/assets/19845179/15944541/3629b0d4-2e4b-11e6-8c2f-6ba12cd01e1f.png) Help would be much appreciated!

**Comment by winauth** [comment]
Which Windows version?

It's a know issue with the .Net versions. If XP, uninstall and reinstall .Net 3.5 SP1.

If Windows 7/8/10, install .Net 4.5.
