### ISSUE TITLE
Already added to account.

### ISSUE THREAD

**Issue by Konstrife** [winauth/winauth#374]
Hi, I wanted to use Winauth a while back but I was really skeptical about it and just dismissed it instead of going through with it. Now that I try to add my steam onto it, it just gives me this error.
![error](https://cloud.githubusercontent.com/assets/19871811/15984593/bf634cc8-3014-11e6-82d8-c52aa6e05106.png)

**Comment by MilkGames** [comment]
Go to C:\Users\usernamehere\AppData\Roaming\WinAuth and delete winauth.xml
