### ISSUE TITLE
I have a problem with WinAuth

### ISSUE THREAD

**Issue by Wasterbull** [winauth/winauth#381]
Well I made a formatting but Windows the files kept me even though I ordered 100% formatting.

I installed Steam and downloaded WinAuth, the latest version 3.5.1 and the problem appears:
![s](https://cloud.githubusercontent.com/assets/19977803/16121559/1ef08f04-33ba-11e6-9e75-cd91a524d06a.png)

**Comment by william2323** [comment]
please help me to fix hexadecimal issur error

**Comment by Wasterbull** [comment]
Ah! I solved the problem. It was still difficult to solve, I had to download the WinAuth and remove Steam Guard from the official website of Steam, so I can use it, I hurt a lot.
