### ISSUE TITLE
Confirmations error

### ISSUE THREAD

**Issue by belowhell** [winauth/winauth#387]
When goes to confirmations it goes to login screen
![1](https://cloud.githubusercontent.com/assets/20137244/16354830/db58a12e-3ade-11e6-9e40-a68c6cac8f71.PNG)
![2](https://cloud.githubusercontent.com/assets/20137244/16354829/da92d9ee-3ade-11e6-8f78-9084b1ba0ef7.PNG)
and when i login. it appears error
-----BEGIN PGP MESSAGE-----
Version: BCPG C# v3.5.1.2

hQEMA53DDyNpqwwqAQf9Ehe648C5danFGODbopVnTjSfzzH0PDzv9V72uH9JU66k
0BJFx/qZ6U50Bz6obA/I8pRIS3/+fWg0OmsNMAGtYwnjwjS1F1ljeuqknkOamR1E
YQHXfFZi426I5Vv3Hhj10AEl09Hb9jxd1r2cAETOdeMJcMkVmXc5Y3ArxwPsehNO
RFNBP2zm8ZxEoFqQXh/4qZkbuYKdT9cQiRV36Z2BLkIUVOYXCcA4YGnoIf0Srlt0
uRfzza+qvM82NfQmKDdaHygKUUdmPsDNEdGljpBy0PaHuV2bBdbTYrG7jWK4e9Lv
x7HcFy8grmS+LMg6J/DuapTjckLeraQWkvFzWb7hPtLN5wGn29bc8nKhJw9+ST42
z6/G7r6xYh89qeBalfQ/3p+gen/j+fKrGK8Gf51GBdVgz9bk18AT8olrF15TKWgz
y4ON1CtPdVDEvotN9cs+UlHud8Be5FvwZPyJnBhFc8x/TNNzwyYHCt0dH9RCKQzr
AUbjUWVJKR9KN86fbOGhP/6x3chy7/D8lqu8XPQTbyd5Fm/5gaOrwVDRcLYtTKMn
5T+VAa0hSGUL0lBToLYp2mVIT5g6a8QiI2IVFPbzeeq8vG4A0BoZGZFPzmlZM2t8
aLoX31/fH6cMmJ3rw1P4SlK1KzFfLX9j2HcMmQswqXLYp71WQ3qRUfxQulpJQ+W2
RlRfEyS932aK0zl6XuzqdeUNrlZkQq5+RY7zTqzPWzQsLS+ztpXP6kAqCl2AGMgN
YUh72acUxTbWna4/mHmuiM5bbFR/H9z9qbl9N3yT9Gsh5CDUQh8kq88tVuRcqNjf
m5SetD5FZyG3N9JvL+xFwE6xVQVT2MIPKc/rxJdSyzQFSlXcJYq7AO7WAdt8pik5
tAuFlpNWB1KiBY5flN3zVMwhV/pC5MhA9i+1re2u2Pgros9uWbneqsVJzVLxX8GX
uZM/ngpW0UnqsCx+mpkVA4LOkfvXgSVxQdSPFfNwxNv1lxbbUxVyD9QeEgDCX3ja
ZgTBN8RvDTN5tH03y60U7k28JHuSeejQ/iZDM/PuySu6DwjLMJYGlszS9Wn1clJr
SYkHo/ZsubNhhM/M8QiOUy2peC3jetlKBTbleK8C/5imfJpGILRkTYCW3tYWuDes
Hn/DRenaKkwqwhhDqBNqbzMzmmkitWye4WxulWQLDXWyxTqr5f1zjdFo8+9izGS4
G+nu7uvsejTi9o7ZDZPMDZaykm77xXTgC62iF338Br+N6pAhCntd+sgeqPy9Tc7G
XJ9catp13syUnIN22XWrxaZ+9aJLY0bV6ENBmGPIMVS4B/SzNEoYINvX2sIyeeL/
WsquHPYNICLIcA17w6pvlDjsBv2lUIMk/T6ynKJNrM15ApWkLeP4AqFMsWOAf3Jl
2uawzq4aGGNsIsj4FTEi4mLqIg4YQqzceSQYQjWwDHhdlFUHTNVjyzmmdiY18gWa
tThsmM04yDQwt2hZW9dVP1ILaDNIWYmRUterVYKHzljOTXrWSzFeynqeOMy2ycph
eEDb2aiqBSuQXBOHtYq4/04Q/w040Mz801gaGfFYmvFkTnGDwzZMmekD0P8XOJO8
0K1iiEwiiKyhJVLC6ncKeTSglpc9VuS5XdCtEBFZeOmXwoDfeyyL0RLilSgzTQYS
0RMG+tmLOWa4Bo2yfTxwXrkRDfopDGBB3lTkB1/ohkMDoG4/MUJoShwM2PMJE91k
awstXQqgDSvdGJbACnvXeJZuyvVVlFKx9jbzA/4x9X2C58HPLUblb7VW7UUdz315
3JkoVvBIXdMyq59fa92cUL1bTzBi7iV5PIXGgTrvq8GM1DnLbKwGabGMcm2iquyK
FUZCh6XV8yIK2x2S76PI5HwbtRL1mYVc7CiLpL6LdYAq3BzFPvFhioav6P50fqvB
psOTuirCkZEJDnlaUCpa5PoN3EL+ijXqO96rPLXwfM86fjuafwGvQsQAx7npYKY7
FH+wvung1tuFLp78ixIfrQYmUff1SDpVnPbkhQytRhpQWuyvvScWxH5T6EEkw7qN
/q+ajWfKK/GM6ggzcTatcY4ebMxQR2tNhv7KxVjTzGZnN9OCQ1eYzkx7NPPLKSou
rUtue10Kg8Ugh64LjYB30qU4upMa3f+Vr9GcYPyjCc9NoxLBc0bGMf/0rGferNTA
flZYk45BAhMX9h/2tglhRNyhaWFCY+lfno99Y8bRhDVPjnu3rkw8ETtFUZKZr2me
/Gy2P1vq1/z8OK8TrVK6njFqAWnHy4gGnbIZQ5NTe+QVDSiswYrWZ9H9l+jJyoo8
6jcbXufP8aH1c3lM8KE33YpQ5SDvnXN7c3VAsP5JREOC9jCbBaYbLGNh5yDrbXJe
GRkb/N6u8KTiq1GMWqfBc80+ZM8nuP7FkQSvMYPdJ/sNvyvxWlilcCgctopjm+S5
cHO+AFrxY3RR+AIaHEf8JvH3UWVJ0DwhA70+B8HLLz20h06WCIBtD7lbZgtNiBea
51GXTqSh0tMt0l/wvEgobex+scCEtshi0i4bW36CHCfbQ4ZGlZ50d5GcELO13Ssf
xDydIJlpFBtqSSWu0PEHiMR7zF7+U5gBS8NIIp3wo33BfMHcxe772ON6sDYCxeI3
bAAswA9z/PfZV2+t1GEF36dHrImpeI2SmSzcX7Y29DdMH6OppPBvqvmx5PPUr4BA
9ETzPNfkVUeDqH62tlonnHSIympjLdKkDjF/QOCgV8uc18OYCB41rZGNGWSkU1JY
rbgXYwzVhgusvH7dyU6n6f9EFXH603akY+nLhx9dyoBU7wNFPupm6qkZw6A71pSJ
ZBLRP6hWudu+9+q5uQ49hWhISBZe7AFlhZ7ndm/GBTTbY7qN548uwe4yjYfujHSP
H0L/AZS1cVmTGN7fWaCWMWwWegTVR/+R6i+j8E1IhLJS0KQO3wZJ/ktoiPQioxmA
ykGlK+tttK1/du5XKb7XteizLTUpLt2kqimmN/TxTDJ+aMNf9NLQDXSj7HN+Zo3A
P370lNegviErGuQl/SUaH+4UYTBNDj5j+wxfRg1ThcFIFq+qbrwmEPu9i89Tem+z
bLyBbqe6vsT19Vp2QeM/Ekk9yzXjnsNsLSrxhqQBkS92Inga0M/0bwpxBuI7Vuyd
ux1sRWWrnLvCRCcvsrdMawJx3ioY94WHILwJwgr1KC3ZvBAkdoL1ZDNV35Gi0YyG
qMQQezv+bCbFyoiB0OdMdmdpiZEkVzdtffq9oakEN3TsmnEkabJ910iI+DbXkbsK
NUrBCZ3kQalWPYfpryYMlzmZPy6c8oV13FprFykgsgYNpOnFa78ZYB741cWKduEy
AgQFgqvKbHOUO1FmhH53lD53hz6QdMy7l4l8z3MEA/cbAyq2F+qZ5PB/KpvYCn6i
7ook36hYnfqIb+pQ1r4Lsl/sueM1f9ZxnXoVg2LHrDzT45nw8kr8Wh7FO2O4xYbU
2Vg2bfPu4o8fJkG80V1uZeXefA1TEEr4gjaxavpsfbSnkAFII9DTG4rA9dU30YSp
COgkY+bl3HTyALsvdfB4YHAlIHhGKcurIqlXwv3triCG3EbA9o9JMe+/k2EpTRdS
8Xcqpg8ylyV+ks59rvneasN2IcWuPhnvDFxT1VqwE+wUU96PosjJlprUd97P/zyh
hUWMzq1OrsisSaV1YAMqdiy0/WEx9Myo+eq/UA5i5ulGihQSVptK5PFVEqIt358B
Qgi5LuQ5lbF7eS76mD8/nOgeCZopvFyfD0xpJrwjmh8h0ypTBxXLTim7N1XvOCRL
ucC76LdyjNAgIhv23Ziw77NzDRVZQ+bT6U3cBtYteozZBIS53nfpgtlYX6KGKbmW
/dCv1DFDCFOeQ1YYte2Jin95CF816+3enQdbGC0U9+j71ICnvsPJBh5sZkMurfjZ
FEApHb4C4kQvsIQZZwnqfm/CdM+oGTuuPy2oMBIJ9stvv7ElkPhz0mRTZsIiQZVr
NmUPUvYCpdbUDnLkFvw4cLiE7BaK8mxoTirfjg6Y2qr38ssgig0vmcYPy2bT5VPM
IwT0AQPflIU3on0uZ5rcjAmwYBiEpXxYRUWOU0rGH45GrXwEvtS/KzcNlBhYPXOC
69dsOU9zj2YYtS2DuL81Op44eFxOyRlx5Ei2B/jVfheYVL3BjJ75wPwnEsYCVHLC
dT9UE79NJTMo0XjD2Z7ye7Aw/NkAqoZ0SNimZJWRif+ihHHFyTWxdR6hIt+EFF+c
wOQ0T1HYMCHqOOq9ngHJUQ2sn7E+tXlScV1p9WdfEZjbjDMffas84zi4el5vqpfs
5FNr+KAeMr7m06tqlroAmmyzk8x7wzM3oUHTJtRSpL61/VMuBbLjy+ct8juwZH9l
tkpyjZg7S0xKZ+K0W/36JhTQTZh2uY/n6yhS1Fpc7jDK97NQWXivRuJIj0js4r8l
ZjnZ2jw6067SB6/+MTKAOrGSbhyv5DyNDdMj6KTNCsgZCw7h1GHDExKQ0+gU52lk
3MHz5GR5yHU4xRY3iKupJAmXXTmDCInLtLMWkUJlde9XQB6jm+ZyDhS7l6gPqOgn
4CJmGHpglhoqmzXuGhyoMkTk+UKyMUmAMXS+YY2IMReUxofNDIZMs1kjXUiDBDzM
yPtosb0cp/YPg0jPNZT4HG7G7oG78xCDWr1OFjFPJb3h/ft5wvcVg+aXJ7WwRoRe
FrY7rQv0zeiTmdEKV2Wa6wJTx6Jdv5X96/C7Cl+o+FVGUaf89cy8lgy+geQ/xD4r
EVOdjezzXoSi4R85cL9MGGQZq55RHWzUPRKq6IekLv1DVHe0HdNNby5CmTXAcNN+
aUNYk1Zj+0cO1llQtDbXjA2lLm6Ua8GUhwLKKEnVGfF7fEf/81WuT2SIjHWlJIO3
ENqMxYXJ+UUSg4oIEKnu+yQCxyua4YPofN5AxqLltscWWyGfqfRdeTaLsCVK//OH
jTSS0GgJKJq4V4/5Z1rVGdbT9Blf9blY5JkHvAOW791wkH6K3GE9dDAgFNyHF8Yo
u2nM9cmHn0j0Tay7yuCULrGvBx1IOh9S/bT0cxY0KCdX/v7fjmNQqcJLZhnF9gsi
3MhKZocmo9ih+akSgrJQU5y0S/X7emDgiqU2poxp/j71f452N6srQ00+3JapG0NJ
xp69Cq8/PFpLpj0Bygf6hCyghvx6XUkb/qGhptAWBXN/wSGfiFQH+EUiiwUdksxt
k0lkoyyLnf15bkV+Q0GgqSxS4wVx0cBYQZjAEs5UfcfO1s3nAI4vHbfTn/oJIRpO
bxTUApiSyhO9zWjoPIXMj1FWao0/i12dZnWRo3CKbfaOI7RreKAD4K95K8Hgsn/O
ZEqzLor/n5KN158luHbQqmNJTCibcSkjueeI8RvjXQVgv0q/C39ryOI=
=x9Ll
-----END PGP MESSAGE-----

**Comment by belowhell** [comment]
can't access recovery code too

**Comment by winauth** [comment]
Which version of Windows and which version of .Net do you have installed?

**Comment by p0kaifu** [comment]
windows 7 32bit, .net 4.0

**Comment by p0kaifu** [comment]
error fixed when im update .net to version 4.5

**Comment by winauth** [comment]
Right. The error is because we require 4.5 and this error happens when using 4.0.
