### ISSUE TITLE
Battle.net authenticator codes not working, locked out of account

### ISSUE THREAD

**Issue by Keanu73** [winauth/winauth#393]
I know there has been a previous issue about this before, but WinAuth has locked me out of my battle.net account, as authenticator codes always become invalid. I also cannot send a support ticket because.. well.. I'm underage for battle.net, and they require you to provide your government-issued id.. So is there any way to solve this?

**Comment by igromanru** [comment]
Let me guess, you haven't your recovery code?

**Comment by Keanu73** [comment]
Hm? @igromanru

**Comment by winauth** [comment]
Make sure it is synced. Right click and choose "Sync Time" then wait for the next code.

**Comment by Keanu73** [comment]
Yes, I have tried that, but it still won't let me log in.

**Comment by winauth** [comment]
If you right click and do "Show Serial & Restore Code", does it look like junk, or do you see a serial something like "US-1234-1234-1234" (or EU) and a 10 character Restore Code of letters and numbers?

**Comment by Keanu73** [comment]
It doesn't look like junk, it looks perfectly normal, I've double-checked.

**Comment by winauth** [comment]
If it looks normal, then it's generating the right code. Are you sure you still have it on your account or using the right one?

You can try going to https://us.battle.net/account/support/identify-account.html?requestType=REMOVE_AUTHENTICATOR and removing it, or putting it a customer ticket.

Or you can use that serial and recovery code to recreate the authenticator on a different system (e.g. a phone) and use those codes, but they should be identical.

**Comment by Keanu73** [comment]
I still have it on my account.

**Comment by winauth** [comment]
Did you sort it?

**Comment by Keanu73** [comment]
@winauth Yes, I have.
