### ISSUE TITLE
Steam confirmation problem impossible to confirm auto or manually

### ISSUE THREAD

**Issue by gusminho** [winauth/winauth#394]
Steam confirmation problem, i cant confirm trade or market item auto or manually, open a windows asking me my steam login and pass when i try manually, and still that not work even putting my login and pass, show me a msg saying : 

invalid authenticator code: are you sure this is the current auth. for your acc.?

*sorry for my bad english

**Comment by winauth** [comment]
Right click and do "Sync Time". Wait 30 secs and try again.

**Comment by gusminho** [comment]
i already try that, still the same :(

**Comment by gusminho** [comment]
not working man, still with same error :(

2016-07-03 18:41 GMT-03:00 WinAuth <notifications@github.com>:

**Comment by TheBilbo** [comment]
its steam side problem during huge event like steam sale. I've asked winauth author to make couple of try to confirm item. He said he will look.
For now - activation is like pain in the ass =(

**Comment by gusminho** [comment]
i just try right now, and still the same.

2016-07-04 9:34 GMT-03:00 TheBilbo <notifications@github.com>:

**Comment by gusminho** [comment]
nothing working yet, any solution?

**Comment by gusminho** [comment]
with no solution, i just remove this and im using other soft for authentication, thanks anyway.
