### ISSUE TITLE
Winauth not starting up.

### ISSUE THREAD

**Issue by glandyxy** [winauth/winauth#402]
Whenever I open WinAuth, I get this:

An unknown error occurred: '.', hexadecimal value 0x00, is an invalid character. Line 1, position 1.

'.', hexidecimal value 0x00 is an invalid character. Line 1, position 1.

Any way of fixing this?

**Comment by glandyxy** [comment]
Ah, simple solution: delete everything in %appdata%/Roaming/WinAuth.

**Comment by winauth** [comment]
Anything particular happened before this failed? Looking at trying to find out why this is happening. What AV do you use?

**Comment by glandyxy** [comment]
Nothing happened before it failed besides trades 'failing' when it actually
succeeded. And my anti-virus is Avast! Anti-virus.
(Not quite sure what you meant by AV but I presume you meant anti-virus?)
