### ISSUE TITLE
the PGP key 

### ISSUE THREAD

**Issue by blackrose007z** [winauth/winauth#406]
ps : why u blocked my other account?? i just don't know what to do so please help me my PGP key is down here there is 2 keys
-----BEGIN PGP MESSAGE-----
Version: BCPG C# v3.4.3.63

hQEMA53DDyNpqwwqAQf/UB1DzYrsMfjyhUZa/mp70nRr6xBpmOKXJ3Z12oHm9dYb
lSDoijMCDTlOtpBCZX9HExy+NapTFzjM3r0H67oJUh4OgmUYsQpOVkB13R2DKVIX
YWluVRCz9JgLIlVV/wavdxyyWHii6UtOFcCOxImYmlcKZEc6RfVF3TiWps4ra23p
xyrBNFwVvZaT1qBjxhCn7MnwcZaAARtHMkPx0WNxnsw4/NciYlRaLmI/gbgmGHzm
fSg/ypW90Uo1vlg0PWDc/QHn7Oa54/QrzyonG39t4ryOR8SbAYXtRJatRH5Svtg8
t2B+GvS0ZO+1ZK4NnnfIVpTpvni1/Gb+0Ov1cJD9AtLCngEGP97Rkgv+hH7MJbbd
5G4NK7Lx7vbVbeM2ADUhFlP+qpcCFZaNGFttTtbq/PFAcNi6ubExipkMQO/24oxf
hWzAIUKzfdXbdebt91Uy2Jaj3QdIXF6bZovujfUKcb07DUPCd6B3II4GyRjgGF7d
ZEK8wzzPE6zNOIAXWztSRilfAM3pzCLG5EwDPvVrN8VF2/6n3J0aqyYtn3MzydSZ
BTIyBA6yws9VPCS+rjlw5DRZLbNc90DU2ZiPkdb6HG4jRIoTBN3DemHgee/+OJrg
7g0ZJtHNljDsn2KRuc7AdUOJXUHpuVYgDgRQSrmu2eAPie/doFrDGOklAaHUVU+I
HdVAAQjyIOjTQq2B8y0beRcZzAwUpim6Eptmi1iqxx8gYuPF07s23Tul1rZ4qlRO
aJiWyel/4hG1iRrM6mg7CDtazP4OxfibwD0L7Z/OdQcQoFPh2qXduogy/j1hu8HN
wkMe9lZSrtaNi2FFe+HznQ2RoxG6zZdN6pAX3jNLYHdUvVHbKJts1vxR15egAcGr
w7vpMSwS0vJBn9CX7lqVm0x179/XJPHqk/vpP6WhZ8Krh+4Cufg6t4vDs1Pk0ffX
LrkF+Kd6eNx00qRDjbaXlvoJjvGRzG/HfNi84wOxpHkAeXZMlnvrpf/mLy+sO2T3
WkVdEAUkq98yLaTZ7byZYMMDcsT+LG+7s2e5DdupWVfiBBRS1Wr0wJTzHrkvRHXL
+2aerUYQVuyE2YMhRfCG4rgPC42Z4imNWGUX6MPGrEkh/t8zts3upKGAwP5LzYVC
q/lKuJzKpeXaNEbM9mjKoqATclIR4ja53w9Y+sLQlHhQIhcC9eDNhW1nyk+JwCvi
z7XEKelz5SQ6LmH3my91rTKYHx7rfvLrE579wiUWtDmWU0vEbNGJyhZ2v0ph0gc7
BU35M5vjMhRYqeKzkl/WUtwL+d2L8kaCWNXEyZu7YQCNEhlF/P8jS8LHmmhvmI1U
61abvhB/gYHWfnz0HGDj4iBRz6JApD7bqcq0W01mkoSd+XcZwXUt5aYFMdhvvd/1
ZBfgxDY5c3Y2371UipyFn1Ka54ALsAH05vA08J5g0HYOtnB3Slo+V+FTwo5wWJzt
S465rSh6GEsNLgIGi7fnWs9PobfImc9dETwOMVkyxgI=
=xXJG
-----END PGP MESSAGE-----

there was another one i don't know which one is for my account so i'm gonna post them both

-----BEGIN PGP MESSAGE-----
Version: BCPG C# v3.4.3.63

hQEMA53DDyNpqwwqAQf/YnPlX3NMODmX1MInrQLRsiT7usqCVxPEmvPWsWl+EfdH
MHrOfVFTPjEkY/qs7ouM5C2Z4ZTBd/k3AU9yYPuaHA10tVh6gFJ/EAhLevOCoBf6
p+o5ViezOJ3/+CyJF8DhIiy26yC3F/CdCT733Pv1Q1/M2Dbs+ujKwIP/aMXgTqbM
tBxLhovvB4xKMyKzRMhMLRiGBVMMijNOZ1WdvXoaxUTTxYsKknYT9WTWVjuD/NaW
uZAVj6xquXuVxDoApY+dPoyFu+FflQG5u7QFfAx4eJs9s0nTqd/gbn6/frfE9dRl
1T/rTxpbvsHP3ECXXBLKJ7kyP9YB6R5PLS8WBLfxydLCogFMtQUKtLUprE5p5fDl
OBnedgSM0Dcpe7bCIZI4FUZdt/NsyKlRYKYoEYFKZStouQwMjTvFIPM0uhlGf5Yr
xCa1IUV5uaaNwLtgmDpftdHOEOHg/E7vnsGVeJTNabXzmyOsGGQe4VPsWLAqFYMA
HeH8T6a5ASNAADcXvRYStuK5AccBQIJ1bsSCSqblUdzi1QAYkmbhdXvv2Zs0qUhU
wUwhF6LRE+f77+TRQ7jgXrWhHsr2Ikk6lOsOEtVVtstNPcI1LqqdBnMSt/o2s2SC
xn2K1pW0cQA7E5GY1eAoaWlbY7lBwYm4Ro4dEDiVNzuVnUIjcKp91ogSdp5mhRiM
YQ3osf5xDqEkC4Ow/IIkjfqFmC5JKElHQKuFaVYfMKE1/tRygudQLIIEceSdxCIn
KuNNhfPI7110OuqjtUrnrRKsTh0mxdui60Gd85b2XBic8XyGU0DhJXH2vJXxrYme
OiKIULUBHpRFLLDvZhVGgxI4eDquUzi3QK8yRhMBxjQj99UR6EXwa82B4e5zYduX
UdaEM4lIqsjWDWufE9YnAVMhI1R6VaSqE/I0Jnnw6KxN/MT0pcZIk2y7p07NAor+
gor0NVDc/lf0khRapIKvGUI9EuJZ6XZKxQhxw92TtmwKqNCnTz8BXQ3LomwCMztV
A3u1F12cPfb1/IevmUcKofjp97tJelh414ZebXmLRpitnnl7UlEfFK34uelZjW8U
KuMmtHAnFw2bjtt4bzviIg7249VgwdYhZ6cpS2/28Sk0o5FB21JcUNo9npsn0Z0Z
RvgprDWIZKRjsHDdCNUI5WM2UJjpvjwmflp01ayrlsuyLB6aDY1b6Mt3Br1xx6U8
KE8FbIBoKO2HiEKGDWJSvbB6oiNJXHG6KO5nfj5Pz2lDl8JHeWYG8hqLEQy130QM
yjjy60aLwAYR+vde8MXsLa/t4RzkMbS1eJ2WFS+gPvNvIOH/cm1pZ48gKmvbGOfK
6drMa0mnKjSgrRPyjvCd2af/gT3Npv2INi5/dvUwZnSjXDzN45cpN9ZC52gsZipu
ZC9o5Y22fjJrJEuw5sRAf3yf1mXUgmXUhcqC2/kddM0JJdr9f98mBMgZnF3fGafA
gG9pXa+cWxAgdoihCLYzfT7xX/QjkO+hhPMcr4gap8VG/5mE
=lsXl
-----END PGP MESSAGE-----

**Comment by blackrose007z** [comment]
i'm gonna receive my bayonet doppler FN tomorrow and want my winauth to WORK so i can do the trade

**Comment by winauth** [comment]
Because I could do without all your drama. I'm not your mother.

I'll decode those backups. What's your email?

**Comment by blackrose007z** [comment]
blackrose007z@gmail.com :3

**Comment by blackrose007z** [comment]
u just saved my life <3

**Comment by winauth** [comment]
Glad you're sorted.
