### ISSUE TITLE
Invalid Password after migration to a new windows active directory

### ISSUE THREAD

**Issue by rregan00** [winauth/winauth#412]
I keep getting invalid password after a migration to a new active directory. I have the winauth.xml but I do not have anything in my registry. I tried to delete all traces of winauth and then try again. But I guess that doesnt work because it still says invalid password. Please help. I need this fixed.

**Comment by DKPRINCE007** [comment]
i feel sad for ya because am stuck too ;-;

**Comment by rregan00** [comment]
I fixed it just now by moving the winauth.exe to another folder. Once I did that, it solved my issue.
