### ISSUE TITLE
Authy support

### ISSUE THREAD

**Issue by ColonelBundy** [winauth/winauth#415]
Would this be possible?

**Comment by Nanianmichaels** [comment]
Long time, no reply.

Bumping for visibility, but my guess is it's probably not possible. Authy may be using a standard OTP implementation, but since you never get to see your secret key, you can't add it to WinAuth to reproduce the code generation.

Though someone with actual knowledge about this might be able to chime in and clear this up once and for all.

Damn shame if it's not possible, though: it's the only thing not allowing me to drop Google altogether (HumbleBundle requires Authy for 2FA, and there's no way I'm using a site without 2FA if it has it available).

**Comment by XP1** [comment]
@ColonelBundy:
> Would this be possible?

@Nanianmichaels:
> it's probably not possible.

Yes, it is possible. Authy uses standard 8-digit codes excluding the first digit (so 7 digits) with a 10-second interval.

The Authy seed works in 1Password.

However, when I added the URI into WinAuth, the code doesn't match. Maybe WinAuth's time interval is wrong?

Use the code here to extract or export the Authy seeds:

* Generating Authy passwords on other authenticators:
https://gist.github.com/Ingramz/14a9c39f8c306a2d43b4

Read this article for the technical explanation:

* Extracting OTP seeds from Authy:
https://randomoracle.wordpress.com/2017/02/15/extracting-otp-seeds-from-authy/

**Comment by XP1** [comment]
WinAuth now works with Authy seeds. After I posted issue #525, @winauth commited cf84f2a.

The custom period implementation, necessary for Authy seeds, has been added to version 3.6.0. However, there is a bug, which means that you have to manually edit the `winauth.xml` file. See my [post](https://github.com/winauth/winauth/issues/525#issuecomment-320880893). As of now, pre-compiled binaries are not available, so you will have to compile WinAuth yourself. See "How to compile WinAuth": https://github.com/XP1/winauth/blob/master/COMPILING.md

The next enhancement for Authy support is `digits=7` parameter in the URI. In the current version, WinAuth crashes when the URI has `digits=7`. It would make things much easier if the user doesn't have to exclude the first digit of the 8-digit TOTP when copying and pasting every time.

**Comment by mikevb1** [comment]
Using 3.6.0, when you manually edit the XML to allow Authy codes, you can change the `6` or `8` on the same line to `7` and it'll discard the first digit for you.

**Comment by winauth** [comment]
There is a binary, it's now in the release part of Github. Sorry, didn't mention it.

https://github.com/winauth/winauth/releases

I'll look into these issues.

**Comment by XP1** [comment]
3.6.1 is much better. Saving and crashing bugs fixed and new 7-digit support. 👍

**Comment by winauth** [comment]
Great! Although I forgot to upload the binary :) there now anyway.
