### ISSUE TITLE
Steam authenticator on new system 

### ISSUE THREAD

**Issue by KrakenFromSea** [winauth/winauth#421]
So i formatted my system and installed win10. 
How do i get back my steam authenticator from old system? 

P.S sry for bad english

**Comment by winauth** [comment]
Restore from the backup you made.

**Comment by KrakenFromSea** [comment]
It doesn't work, i have invalid password error and i can't log in

**Comment by winauth** [comment]
Sounds like you had "only use on the computer" on so it was encrypted by your Windows account and unless you made a backup using the Export, or have access to the old registry files, there isn't much you can do. It's like wiping your phone. Use the Steam recovery code to remove your authenticator from your account.
