### ISSUE TITLE
New PC, no access to old one and therefore my WinAuth

### ISSUE THREAD

**Issue by Balou3** [winauth/winauth#444]
Hi, my issue is probably quite common: I have a new computer and didn't save my password or any WinAuth files from the old one... FAQ says: 
"If you didn’t write down the keys and don’t have a backup, then you will need to contact the Support for the services you use and request they remove the authenticator from your account." So here I am :-) Help is greatly appreciated!

**Comment by BrazilianArmy** [comment]
It's not the WinAuth but the service that you use. 
e.g: Steam Support, Google Support

**Comment by winauth** [comment]
> It's not the WinAuth but the service that you use.
> e.g: Steam Support, Google Support
