### ISSUE TITLE
Get error when open winauth

### ISSUE THREAD

**Issue by koukoutm** [winauth/winauth#451]
I had an issue with my computer and when I reboot I got an error message with winauth 
http://prntscr.com/cslvt8

**Comment by koukoutm** [comment]
i can send you pgp messages

**Comment by winauth** [comment]
Can you send me the backups, winauth@gmail.com

**Comment by koukoutm** [comment]
i send you my corrupted xml file and txt file with all my backups

**Comment by winauth** [comment]
I've just emailed over the restored file from those backups.

Anything odd happen when your file got corrupted? Any crash, anything unusual? Do you use an anti-virus or malware software?

**Comment by koukoutm** [comment]
i have issues with my hdd and i got a bug just after opening winauth (hdd problem) and atfer that i got that error and sorry for my bad english


________________________________
De : WinAuth <notifications@github.com>
Envoyé : mardi 11 octobre 2016 21:10
À : winauth/winauth
Cc : koukoutm; Author
Objet : Re: [winauth/winauth] Get error when open winauth (#451)


I've just emailed over the restored file from those backups.

Anything odd happen when your file got corrupted? Any crash, anything unusual? Do you use an anti-virus or malware software?

-

**Comment by koukoutm** [comment]
thank a lot work perfectly now !
for people who had same issue just provide your registry backup here : https://winauth.com/lost-forgotten-password/  and contact the admin by opening new issue.
