### ISSUE TITLE
SHA256

### ISSUE THREAD

**Issue by kangjun100** [winauth/winauth#465]
Hi, does winauth support SHA256 algorithm and produce 8-digit codes?

**Comment by winauth** [comment]
It uses the standard [HOTP algorithm](https://tools.ietf.org/html/rfc4226), which uses HMAC-SHA1. The default is 6 digits, but can be configured to use 8 by importing a [KeyUri](https://github.com/google/google-authenticator/wiki/Key-Uri-Format) from a text file:

e.g. 

otpauth://totp/Example:alice@google.com?secret=JBSWY3DPEHPK3PXP&issuer=Example&digits=8
