### ISSUE TITLE
I forgot my WinAuth password

### ISSUE THREAD

**Issue by pepzii** [winauth/winauth#477]
From the beginning, I decided to create a password that I knew I'd probably forget later on - but never wrote it down obviously, as the idiot I am. Is there a way to resolve this? I've taken off Authenticator from an MMORPG called Runescape because I can't access WinAuth since I've forgotten my password on that.... I've tried Googling this and there seems to be no answer... except to contact you guys. Please help, I'd love to be using WinAuth again without having to use my phone.

**Comment by pepzii** [comment]
Please anyone?

**Comment by Chanilove** [comment]
It's disheartening to see that this hasn't been answered yet. :( I'm having the same issue.

**Comment by winauth** [comment]
https://winauth.com/lost-forgotten-password/
