### ISSUE TITLE
Was WinAuth affected by the recent Cloudbleed leakage?

### ISSUE THREAD

**Issue by ImSpecial** [winauth/winauth#481]
I ask because https://www.authy.com/ was affected. But I'm not really sure if WinAuth / Authy.com are related in anyway.

**Comment by winauth** [comment]
No, and WinAuth isn't related to authy.

WinAuth itself does not store anything online, so isn't affected. The websites and services for which you use WinAuth could have been affected, so you should consider changing their passwords and 2FA token.

Our own website (winauth.com) does uses Cloudflare but is only a plain html site and holds no personal information.

**Comment by ImSpecial** [comment]
Alright, thanks for the (seriously) speed response.
