### ISSUE TITLE
could not find recognizable digits

### ISSUE THREAD

**Issue by kitkat163** [winauth/winauth#490]
Launched WinAuth and received the above error, afterwards WinAuth launched with none of my authenticators or asking for a password as if it was just installed.

Adding the winauth.xml did not help, updating to latest version also did nothing.

What do?

**Comment by winauth** [comment]
Sounds like file is corrupt. Backup? or recover https://winauth.com/lost-forgotten-password/

**Comment by kitkat163** [comment]
I did not have a backup, as far as I can tell anyway.

I was able to find the secret keys for most of the authenticators that were important to me. As for the others is there something I can do with the "If you’ve been asked to provide your registry backup" portion of that link you posted? When I go into regedit as instructed I find 4 items with three of them being PGP Messages but I don't know what to do from there.

If not I can live without, thank you for your time.

**Comment by winauth** [comment]
Did we sort this? If not, please can you comment again.
