### ISSUE TITLE
WinAuth Error 

### ISSUE THREAD

**Issue by Johnny1337x** [winauth/winauth#491]
An unknown error occured: '.' 

Screen: http://puu.sh/vgXA3/ce16fd6edd.png

**Comment by winauth** [comment]
File is corrupt. Restore from back up or https://winauth.com/lost-forgotten-password/

**Comment by Johnny1337x** [comment]
I downloaded Win Auth completely new and it still gives me the error.

I have all my Steam Accounts connected to it..

Any other ideas?

**Comment by winauth** [comment]
The winauth.xml file is corrupt. It's in \Users\<username>\AppData\Roaming\WinAuth\winauth.xml Either restore it from a backup or follow instructions for recovering in the link.

**Comment by Johnny1337x** [comment]
Ok, I only got a Backup which is old and doesnt have all accounts.

But in the registry I see all 25 accounts.

How do I add them to the authenticator? With the code, dont understand

Thank you!

**Comment by Johnny1337x** [comment]
I got all the PGP Keys, but dont know where to enter

**Comment by winauth** [comment]
Email to me winauth@gmail.com

**Comment by Johnny1337x** [comment]
Done

**Comment by winauth** [comment]
Restored from backups via email.
