### ISSUE TITLE
WinAuth doesn't work when I click the icon on my computer

### ISSUE THREAD

**Issue by candi7x** [winauth/winauth#492]
I had recently(a week or 2 ago) downloaded & used WinAuth for 2 factor auth for a site I wanted to protect my info on.  I have Windows 7 with updated service packs & updates.  Everything was fine & went good setting it up. I used it only a couple times to secure some info on a site & to test it out.  Now the other day the icon had changed into a white square box with little objects in it(little broken apart pieces)).  I tried clicking on it but an error box would come up.  See below..........

![cptr4winauth](https://cloud.githubusercontent.com/assets/27330611/24991818/a0b93e1e-1feb-11e7-8219-800269d3d6c0.JPG)

So now I can't get it to open or work at all. I tried typing "winauth" in the search from in my start button(lower left corner of my computer) & found the same icon there & the same thing happens when I click on it there. But somehow now the icon has changed again to the same as another icon that I have for another program.  I'm really confused.  Please help!  I have my password & personal code for WinAuth.  & I also have the key for the site I used it for.  But I haven't backed up.   Can I maybe just download WinAuth again?  Or is there a way to deactivate it so the key & QR code show again on the site I want to protect the info? 
Because I was also wondering if there's any way to deactivate the winauth, 2 factor auth for the site I am using it for so I can use it on a cell phone instead? I'm gettin a new phone that will be able to use apps & I'd really rather have the 2 factor auth set up on the phone.  That's why I wanted to know if theres some way to deactivate it from my computer.  Or can I just put the winauth or googleauth app on my phone & use it there with my password/personal code.  Please help!!!
Thank you!!

**Comment by winauth** [comment]
Looks like you moved or deleted the exe file. Download it again, which will use the same configuration file you already had set up.

**Comment by candi7x** [comment]
I didn't move or delete or do anything with it.  I'm not sure if an update or something did something to it or what happened.  But Thank you for your help.   I downloaded again & its working good again.  Thank you!
