### ISSUE TITLE
Corrupt XML File

### ISSUE THREAD

**Issue by zaptil** [winauth/winauth#496]
Dear Winauth programmers,
my XML file is corrupt and it just gives out a bunch of NUL s and i cant do anything with it. I made a file to export my authenticators a while back and I read that you guys can recreate the file when u have something from my registry. Just wanted to know the steps I have to follow now.
Best Regards

**Comment by winauth** [comment]
Can you email the registry data to winauth@gmail.com

**Comment by zaptil** [comment]
where exactly do i find that again?
ill try deleting the winauth file and importing the accs from the old file aswell
Thanks for answering this fast

**Comment by asdfok** [comment]
@winauth why am I not getting any reply? I already sent you an email with my registry data attached.

**Comment by zaptil** [comment]
why do you think this is the appropriate place to ask?
please leave my thread

**Comment by winauth** [comment]
@zaptil please send it again and reference this issue
