### ISSUE TITLE
error 

### ISSUE THREAD

**Issue by yoarib** [winauth/winauth#497]
I ask you to help me, I opened my normal program add my account, I finished everything and when I re-opened my program, nothing was saved and I was not able to log in to my account in advance thanks

**Comment by yoarib** [comment]
hello!

**Comment by winauth** [comment]
It saves the data in the file in \users\<username>\AppData\Roaming\WinAuth\winauth.xml. Check you can write to that location. Did you definitely click the "ok" button? Unfortunately, not much can be done if it wasn't saved. You will have to go to your service's support.

**Comment by yoarib** [comment]
And what do I do with that?

<?xml version="1.0" encoding="UTF-8" standalone="true"?>

-<WinAuth version="3.5">

<alwaysontop>true</alwaysontop>

<usetrayicon>true</usetrayicon>

<notifyaction>Notification</notifyaction>

<startwithwindows>true</startwithwindows>

<autosize>true</autosize>

<left>-32000</left>

<top>-32000</top>

<width>0</width>

<height>0</height>

</WinAuth>


2017-05-09 23:32 GMT-07:00 WinAuth <notifications@github.com>:

**Comment by yoarib** [comment]
<?xml version="1.0" encoding="UTF-8" standalone="true"?>

-<WinAuth version="3.5">

<alwaysontop>true</alwaysontop>

<usetrayicon>true</usetrayicon>

<notifyaction>Notification</notifyaction>

<startwithwindows>true</startwithwindows>

<autosize>true</autosize>

<left>-32000</left>

<top>-32000</top>

<width>0</width>

<height>0</height>

</WinAuth>

2017-05-10 9:30 GMT-07:00 Yoarib Hernandez <yoaribxolo@gmail.com>:

**Comment by yoarib** [comment]
hello! xd

2017-05-10 9:31 GMT-07:00 Yoarib Hernandez <yoaribxolo@gmail.com>:
