### ISSUE TITLE
Uninstall 

### ISSUE THREAD

**Issue by ghost** [winauth/winauth#498]
I have had WinAuth on my computer for a few months now, but I have had no need for it. I thought it would be useful when i was having issues logging into my ubisoft account. Tried googling on how to uninstall. No luck though. Can it even be uninstalled? I really do not want it on my computer anymore.

**Comment by winauth** [comment]
There is no installer/uninstaller Find the winauth.exe file. Press delete.

You can also delete the settings stored in AppData\Roaming\WinAuth.
