### ISSUE TITLE
I lost my secret codes for WinAuth 

### ISSUE THREAD

**Issue by Nyelladaniel** [winauth/winauth#500]
Hello Team;
I am using WinAuth on Bittrex.com for my bitcoin wallet. Somebody stole my laptop and I lost everything that was in it and now I have a new laptop but the problem is I dont remember where i saved my secret codes. Please help me remove the Win Auth in my wallet so i can create another protection. 
My user name for Bittrex is danielnyella@gmail.com

I will appreciate a lot
Regards
Daniel Nyella.

**Comment by winauth** [comment]
You need to contact bittrex, nothing I can do.
