### ISSUE TITLE
An error has ocurred in WinAuth. Method not found

### ISSUE THREAD

**Issue by WinieR** [winauth/winauth#503]
Hello, I come to report an issue.
I've  executed the file, and an error gave per WinAuth
it say

"An error has ocurred in WinAuth.
Method not found :'Int32 System.Environment.get_CurrentManagedThreadld()'
Some diagnostic information has been recorded and saved that might help track down issues in WinAuth.
Ut wiykd help if you can submit this information so we can investigate the crash and try and fix the issue. This information does include information about your authenticators but is only used by the WinAuth developers solely for the purpose of investigating bugs and error reports. It does not include any personal or identifying information. Any information sent has been encrypted using PGP and cannot be read by anyone else.
If you are happy to send this information please either click Send Error Report or you can click Show Details manually copy the text and file a bug report at (Link github - winauth issues)."

and this is the text

-----BEGIN PGP MESSAGE-----
Version: BCPG C# v3.5.1.2

hQEMA53DDyNpqwwqAQf+LTc7MBi71uF+bes5GWt5NtKlUEfnqnz4BPt7uOqxNYSU
6rVN472CW8b0Jdf6uU6oy5Rrlg3v2DTTE3591qpz20hbk52erPTalHJqUfgxecxi
lVpdbHsfLXxpMeOn2GTcEg5CUx48sfZ7Fs6xKYT0JoOkqqUNhcS6TAkrG1/Zs09j
Zqpy6PfiQkW2+ksZ7SYls2vxur7PtF/VeZV3AtQbuPOgOOyJ3v2wYXuOKW0v9oUr
NIJae5RUd5G3ctQYz4TH2NwJOS9+qkM+urrCKgJdAkd/7vAaGCwnoGepdZ6TYMN2
CKLa5sKrDaGYLjis8B6NtZK/Yf06MyyzW4/focJmltLDEwEaNh+5X7aAyd8TIN90
R8J6L9axDpNyN2mzQz3dyyXyiWR0d9q7yjWdA/wBh5nB90Y1RuSn5bD8+uJOTEA0
BMBif77RoSu2r5Kf3KKq6w2zdAFlyRfkZB5QFbEzMuWwtlNrKA/+oOHFo4CorXKd
yVYWZ1iD+3PjAk+nkDunaoc+SXh40TCQizPyxKQXyUDklsMlkImyTS6jagdOVeNe
3jGSECtLbI8v0kBO43cJ35eQAsxY5/R4d8rMjaR/+uQaTLNepaaDo7of6pAgzROK
CRGA5Z/6CGCW8RvnEiprLC9BveC60Suxykl0weIcdJxHmPLMOw3LOa+QFcy4zF7y
lc75ygbmwCzlQZXbJROV+K2njdno7tIqVU6rZ/IdVD5xxSaazPJOQhvYUzPSK0+1
uKFXSk/0H7jrAngbVx7EkwDWVkOANyVgDuD1K23VEl1w9nxYso6oYD4LAjhJxTXp
zXacW2ewPzZKf8g1dV29LsBy+W6BMg0Wr7hfYH7NG/AzE8HUpZPoJESKPDMXQMCb
Hseh3U9sgXD4pKkotX4hwbph/RlCzWd4kobu8RvcbDQiTZ6+0CLQIyaKErsDqX9j
6ELJcG8f8yqJg30RDk76wAz0vin5Ex6Cmd5D9RJY8/wHlKqNJdAURvgGWTI/pQMF
ES4/1DU3plTN3qC0Feyow3LYeO6hbD+XRp5iogjGgWQLqElS8ksywSzK6eSmjmQB
DH3ZmW4p0crx+12eKEjOcF16uEwmLgblfF49Mi89kVKLDQ7gNTxlXNIFbTVqW+ov
iwxS8XOuWCtNy3z2BctIzXbh5vA/3TpUPFl1NpZSbZZOxN8jKa+WVeOMgo7EY8BW
GBnREhASsVOIGt8CrGDWlx9/KuDiKRimua42oVB9oGD5XoOwSRp2Q8emW/Xiyx8G
P9eyuaywXxvlFV3/2/sxwo68ifDmmmET9oiJ6Zsw0X4UL4UYN/J+wljvQIM299tz
FlpW3129mrViMW881v1LAOpHmBlXi5IhMiBKs4TYcrumOCqAxKGiIUyHk6FeVKM5
ovUP1EvR7H9fnw+8qoN2kPpQC+5mTg2WAgVhDgI6cPhiIjeW34xfbOf23IxCNS5p
TqiZKuyriwEtKDCu1xP5D09dy6RNT/DsI84xLiWv+8clPoYvEynNM2Zshu2xoi8K
pnXQ/851ForQCqMBRTx988IXnJgwxp6M1LewN7dF2tL6TRdH06fQl1YOo6HHpYph
OstnAkUgVsS2cskTs1HXonTaHAp98ugchczO2ugHXMkRsa6+hAQx8SRxVkX0Vltx
LRFYTIw=
=nIBx
-----END PGP MESSAGE-----

**Comment by winauth** [comment]
Install Microsoft. .NET 4.5 (you probably only have 4.0).

http://www.microsoft.com/en-us/download/details.aspx?id=30653
