### ISSUE TITLE
winauth.xml store location / encryption

### ISSUE THREAD

**Issue by zQueal** [winauth/winauth#508]
According to #495 it's possible to remove the `winauth.xml` from `%appdata%/WinAuth/winauth.xml` to wherever you've put the `winauth.exe`--but I really feel this isn't even close to enough.

This is just as bad as storing passwords in plain text. It's hard to take WinAuth seriously as a windows based replacement when created time, server time difference, and secret data are being stored in known locations in plain text.

**Comment by ksarnelli** [comment]
The secret data in my winauth.xml is encrypted.  Yours isn't?

**Comment by winauth** [comment]
The sensitive data is encrypted in the file. If your isn't (it is by default) then you need to enable it using the "Change Protection..." menu option. You can use your own password, the internal Windows Data Protection API and a YubiKey. The last two means that even if the file was stolen from you it would be unreadable.
