### ISSUE TITLE
Issue with Winauth - urgent

### ISSUE THREAD

**Issue by itamaram69** [winauth/winauth#513]
Hi,
I created in Winauth 2 step authentications to many sites, and they just don't work today! It's been working fine for about 4-5 days and today when I try to login to any of the sites with the 2-step authentication, it says the codes are wrong! why? what's going on?
Please help!

**Comment by winauth** [comment]
Most likely the time in your authenticators needs correcting. Right click and do "Sync Time". Wait for the next code and try again.

**Comment by itamaram69** [comment]
Thank you.. do I need to click it every time before I do it, or just 1 time will be enough?

**Comment by winauth** [comment]
It should be automatic when WinAuth starts up, or once a day. But when done it is saved into the config file so will work unless your computer's time changes unexpected. Let me know if it happens again.
