### ISSUE TITLE
Password prompt stays on top

### ISSUE THREAD

**Issue by Efreak** [winauth/winauth#522]
Once the password has been entered, please unset the *always on top* so that it doesn't remain on top of your other software while WinAuth decrypts. In fact, please unset *AlwaysOnTop* entirely. Making sure it pops up on top of other windows is a good idea, but it should be up to the user if for some reason they want to put another program on top of the dialog box.

**Comment by winauth** [comment]
It's by design because of the use of hotkeys to force it to the front.
