### ISSUE TITLE
Crash error due to not compatible with FIPS

### ISSUE THREAD

**Issue by sjva22306** [winauth/winauth#524]
Got this error when trying to add an account:

"An error has occured in WinAuth.
This implementation is not part of the Windows Platform FIPS validated cryptographic algorthims ...."

Was unable to Send the Error Report, Winauth crashes.

Details:

----BEGIN PGP MESSAGE-----
Version: BCPG C# v3.5.1.3

hQEMA53DDyNpqwwqAQf+J/gygs2vnexv+yp+vuvZ6/Oa1TJnGbMXSI9zBSGeiNGK
GB4WViGj9eOTMGOD9I/+c0hz5jGjRACRrDjtS37CxNf8ghCOQwod/N9s/A8qWxfl
FRg6scK+FaHjdLLXHi3lA76sPNZO7EOhyY+zBF06k8RqQ28YmwnHVkD7PiYN6gSx
66Tfiy513NpWBF+1pAWhS6pH5wNXwOWioH+6nv20NwyvzjOyFgR40DPIQD8ZFnfI
rWDV+E5f0O0nkqQN3IhouQKHpekWiYDuFIYks4fXJ/Q+DO/ZNmjSo2zrUULmvCx+
vqoP5124MrZZgs3O2oZJ3T88/wJ8JB6d1kkg1ow5ItLCtAEaakQzS+i7hcG+UFJ2
m30k6z8XxYz7UVy9kbnhRygkYHlLRZzo3JOfXi5sSLHnfeUSIARJhDvKYkufvJ0A
Np/VV0OhffuCwpcna8xmHI3LOn66U+sdWEtiBgMy1ibhmpSn5bYo06q20bz2h1e3
UYU1/Q0CTA341cQs9mBnyx7Orru1CEA7W/TUuXV3usBiVepmjG/QnOWQHFkqvlx4
YGOYkIgeDgKgbxwkzx2IVZ+qDQqBgu8xfElooE3A1aYM8p5MGjYxw9IB7cbRoN7/
uAPAykuv8/7FV+l1rW9qELCbBKU2/2XGLpHQ4I20ZMJCoZnffvdUu2ctykPqG+lK
8tnRK7MpycvXhhU+ZZkSxKWrNzzsPNnOT3JAMyfjn3jWRj5aWCsJzLGv8PIGF0eL
axFrvoFQ80rh3d3GN5EnIVScMH7m23kkv6G1ixLA8NGUdpTGvOeOewB5kUp+Wr8t
Jh71Hz+BJNyqsbHdzr0Lob/7k4zzvgZOeO+fR9cB5ITzm4qZd2WOHJ8dqajllaE5
UInU54Cfcxwss7vBM2q1g5NwJ2A5lTSP/KFb7EwRjZx/AxJ5zrFgNGa1wqJr54D5
fRGvQeT7de8UFUEiephQ3o82gTqXulRknt7DW9GP/SKqKD1sJMO1FYR/fQiR8Oh2
MLilapRV2tym654J5Rwur709YTOj8rKd/eiVUAiTb0OickLVI92akgP9eS7U+K+R
8tM8CxhpFTbChbeuqOa4HD0wurB+EOm29373b71yFH5YDMI3Agw15Hsy2s/LBBkb
UZ8OToXi/jr+WcswqSO+uqS6hgZfPhkVLqMBW5/yyjPK6fD6RALur8dEX0PvphGo
3JG2Z65FU+V+2FEf3VVoBm2QKsuCvj9aX1oUbHS0idnabjYnVQI3PBLloJCBtxuH
FWZgaFbaDdZA3wcgm0VPbTX9dkKGV/Wox6oJDdBW4Yc4C7mH71LXhC948kDsMcfo
GTIg/gE8bP4He3ofr1aLuhqEkzOLEr1uWvpXtesYbqDrnnpdJDQo2D1GbvP8dvoV
QF+VKeDnUN7Rz8RRDB8M8AISwpjrmZwTFt/wS6Fb+Ku9TXfaUxV8YtCnqRzDe01+
Yga37IPGnek5C2ES2cZFiuxpsCWECFdjeqafF4QNSE5hkp6CArw4MppNQz33zgjr
I/rQkoeo
=ej+H
-----END PGP MESSAGE-----

**Comment by winauth** [comment]
What version of Windows are you running?

**Comment by winauth** [comment]
Have you had FIPS enabled on your machine?

**Comment by sjva22306** [comment]
Windows 7 Enterprise, and yes indeedy, FIPS is enabled!

System cryptography: Use FIPS 140 compliant cryptographic algorithms, including encryption, hashing and signing algorithms - **ENABLED**


I'm guessing WinAuth is not compatible with this security setting enabled?

**Comment by winauth** [comment]
Looks like an old version of a SHA256. Have updated it and in next release, or in 3.6.0 (https://github.com/winauth/winauth/releases) if you want to try it. 

Please make a backup (using Export.. option) first, just in case.

**Comment by sjva22306** [comment]
Still failed.
I used version 3.6.1

Please reference below pic.

[image: Inline image 1]


- SJ.

**Comment by winauth** [comment]
Thanks for trying. Image didn't come though. Can you upload the error like last time?

**Comment by sjva22306** [comment]
Same error mesg, but the details are different.

An error has occured in WinAuth.
This implementation is not part of the Windows Platform FIPS validated cryptographic algorthims ...."

Was unable to Send the Error Report, Winauth crashes.

Details:

This implementation is not part of the Windows Platform FIPS validated cryptographic algorithms.

   at System.Security.Cryptography.MD5CryptoServiceProvider..ctor()
   at WinAuth.WinAuthConfig.WriteXmlString(XmlWriter writer, Boolean includeFilename, Boolean includeSettings)
   at WinAuth.ExceptionForm.BuildDiagnostics()
   at WinAuth.ExceptionForm.ExceptionForm_Load(Object sender, EventArgs e)
