### ISSUE TITLE
Parse period parameter for custom time interval

### ISSUE THREAD

**Issue by XP1** [winauth/winauth#525]
**Parse period parameter for custom time interval**

WinAuth needs to parse the period parameter of the `otpauth` URI.

Key URI Format:
https://github.com/google/google-authenticator/wiki/Key-Uri-Format#period

A period or time interval of 10 seconds is used for Authy seeds. The URI extracted from Authy looks like this:

```
otpauth://totp/Authy?secret=ABCDEFGHIJKLMNOPQRSTUVWXYZ&issuer=Authy&digits=8&period=10
```

See this post about Authy seed extraction:
https://github.com/winauth/winauth/issues/415#issuecomment-318291066

**Comment by winauth** [comment]
Has been added https://github.com/winauth/winauth/commit/cf84f2ad78685a83d0596335eb0bea4b8737435f

**Comment by XP1** [comment]
Thanks. WinAuth now works with Authy seeds, but there is a bug. When adding the authenticator, WinAuth saves it as 30 seconds instead of the custom period. I have to manually edit the `winauth.xml` file's `<secretdata>` from `30` to `10`.

After that bug is fixed, the next enhancement for Authy support is `digits=7` parameter in the URI. In the current version, WinAuth crashes when the URI has `digits=7`. It would make things much easier if the user doesn't have to exclude the first digit of the 8-digit TOTP when copying and pasting every time.

**Comment by winauth** [comment]
Can you try 3.6.1 in https://github.com/winauth/winauth/releases
