### ISSUE TITLE
Winauth does not accept password

### ISSUE THREAD

**Issue by triveni-260** [winauth/winauth#526]
Hi,
I've been using Winauth for a while to VPN into my work. Lately Winauth opens up when I boot my laptop and already displays an "invalid password" message in red. After this if I try any password, including the correct one, it just keeps displaying the same message and won't let me log in. I need help ASAP. I thought I was doing something wrong, so I uninstalled my VPN software. But I realize now that it's Winauth all along.

**Comment by winauth** [comment]
> and already displays an "invalid password" message in red

Are you passing the password over the command line? If you have changed (or something else changed your password) the file will be re-encrypted. Your best solution is to recover it from a backup.

**Comment by triveni-260** [comment]
No, I am not passing it over the command line. And nothing has changed either in Winauth or my VPN. how do I recover it from a backup? I'm not even sure I have a backup

**Comment by winauth** [comment]
https://winauth.com/lost-forgotten-password/

**Comment by triveni-260** [comment]
the only thing I have is the regedit backup. What do I do next?

**Comment by winauth** [comment]
Email it to me winauth@gmail.com

**Comment by winauth** [comment]
Also send your winauth,xml file. It's in \Users\<username>\AppData\Roaming\WinAuth
