### ISSUE TITLE
WinAuth codes not verifying

### ISSUE THREAD

**Issue by DingFandango** [winauth/winauth#528]
I've been trying to verify a google authenticator for dungeon fighter online and I've tried to verify exactly 17 times, only to be locked out of my account as a result. WinAuth was working fine yesterday but suddenly none of the codes sent work. I tried verifying with the website itself and it still said the codes were invalid.

**Comment by winauth** [comment]
Likely the time has changed. The difference needs to be known because code are based on time.

Right click over the authenticator in WinAuth and use "Sync Time" from the menu.
