### ISSUE TITLE
An error has occured: Could not find file "winauth.xml"

### ISSUE THREAD

**Issue by JourneyOver** [winauth/winauth#529]
So I had to clean install my computer recently and now whenever I start up winauth to re-import my stuff whenever I get to right after re-importing I end up with the above error message and nothing imported to winauth at all.

-----BEGIN PGP MESSAGE-----
Version: BCPG C# v3.6.0.3

hQEMA53DDyNpqwwqAQgAgSeP7CIMcjjPfoxvrfuM61n9ZjnJV2L7AWImQMbVFXjU
LzslREeVeNlT7d3IVJpyWatAJgR54ZWeJWza43v9aOzcwtfACWQXVZQcBeprBPv0
USbdqnOftgbB0s+ICxrx8XEPCuBbfp7JfaCHbuCN2+bXBydoIeMiVdfVdxOfRANr
v+pBJVZFpcYiuRkF6NcuJTTs7Nd2IeYKTIL/prj+p7Z7AOIEukyOFldZk6pAAD+v
TlSvAUnCQ7A8IbOlCpxcqk//VzucM/YeJ0ehHd970CKi47c3dHWpc4BRlkHTCxKd
1Es9ffYaGgaiA1a3fYyVOhQ5RE5Cu0OPAyAWvKJC19LsAbdkA714KUsy/XbKFX96
xsDCrxrkTHBGUzLyzr/ygkOOakwXlhqYnTQmeekzfQ7X0p/f081K4LJUOE2f+v/o
huJkCh3xzj8k7k1V1sAHskfTksrRhnWIG+Ldt5HOIhOHdjGfZ7Jf94jne1aLAjAF
hEtSgDhZ+HVAs01KsdLKqhQkj35icaLLDlxzIIV770hgXr7z2cObOJrWNc2LCs3B
XvDeO9JYlcmRbN8H51K2rscVgBQJCHJUJHS/jEoW57C8ET0sSab4t9BdkH/4kqXU
j7ixPbfVUi8Nw46is8ecXCPRYY+iH+5ipd1md/yQEYdmmXdGkeeIkdXFSSpmSLp0
zdoGiA8fnR9KnQlEa9ri9520iclsBTBNSECiT17P3tunXL9JXOazwHDluxvWsDmP
sMo87fx7k1KpY4iF8O7egMFWeNdANQKhEvGCwCkSEHEum5buXIDfS+3JC/EU8o5m
Gqjwi7GI5md3y3Mb6RBC5ySma0MZnUkwro+Bs63J96LSgJrqdh8B7L+wHssgJaVA
8YUXnqD2xQKxjbQm4wlg7Lbk1eWfIaW1pYZOv9cUjq9AOsl6iTkcosZyWoEERX/N
W+KXhEneGzoCp3ZQDVhJSEFsw3zVwAew41xD4lHhS9iVI9VJrXjSpUrMQO3qvD4P
sbmCCJOzVFnSPeE/ywgBrhw9MO9lug9/PJaS68WmB9kRvnGVEAd+Kkj73qrE78fV
2zZ5VEf8baGovmZVDR2ajpj9WBB7Qq2bTyg+yszZI0t6YBmVEtiTSQ54e+I+syzi
LKunp5qEQE65HOgYcSRLcSQDwogdVNOUYyzyA8nG/iVVazfi0KFqG0tcJlXoN3B+
xvl30sWTQ7ebj///Dge88UyU/LPc+SiEwRHiQjoC9JukjpgUz4ercctZ8zUrCALi
NVZDrhAT1uCMrDxgHprKsCfqHFf9h7jjU8AaG7bc1fgVMfCguM/aPEZuhaM+MTIX
WejgT4rJXxcFclQ9eoD1BTBHEkwz+9XLrt8xKiLaK6XakAu/Iu3M/xWLp5QYuMP2
IAdl470rGRMUYV1S8trMGEag8qQaTS0IFnehDjDSqdmVeLHTSLMwc0fcpjmHvgkl
2+licrZMGPwsV2EkTXKRwQTuB2A6nJJiXncXf15/HIbPGfgFdneAR5OeLbntaw8U
+nE6zK9kUhn+wWvCxDC5B05zmKTT+Fe91BBXYvR9QrCtS6eUfZFo4Xkn8YoTkeWN
tMYtEr5H1D9T+6qLQw46jGZY8kRSiKn+9/9sTqcBR8tCWm0D30y7wZsWNgzVQCAf
UlrAlr0cauKWiUWHL9UG38wEzI7/hVEJwytjlxNV6a7M3VQRyNvB03sfM7dzofo7
wA8UVboI7quo6K5EZqFPv8elmJqBjHzyqdLlfI5PUz9XJB3S++QSul060u3RXzS/
hSY0l3tVzUV2u+QoXKACzMu6YAgJ2ocFmdj1Stishzx6DQRWBsAnTNN8/aymp6jY
DiIcZgNsEHNbAjhFL1dMop0Z6p8C6PSr9jJ7SbZxjSFbbI8H0jO7CmBeH2t4lrFN
oioBPNa3mXAMWM0ImwBiRkz2EcWmb6xOhBNz+M3FfHmMXyD2FbdU0hSIftiWX52d
z/b8mNY2NDpv/dPzpi23UAqPUYstBiVRie1AQTN+bjFODKvoFEa6xybfpdLMP9FR
NSeUh+qEDNnqB9m0JFefkZWmaS0EFNm4kPmgVKY4cPcDtUOKvJzCEWjVcQ/fAH97
OognOIQudctAXN12EcyHytKp5ZokvJNJElwW+pU6hPjYvnwyCiZYp+i0dMol9Lb9
/fmA8vF04QqmRngpSMuXCt0ttsPjfLFS794egllm1o3L5vnUIxUx0q+qZqMKZblM
XinbAQts8MdwRqbL5CMNGu+Zgvb/DHskXp9mi7cTWVthCOMhgmZIW+IDmF30wPQn
olVprgHmEgp6toqjNt2LZNadsnlmKIE0iIvTXpOt2Y2RhpKYafIxPt8V+VeAxZ6a
8bBUoejCueeAIceNHHlrfREvJQFiuiA+cH6hYFFuPaKsWkFS/xR0u5009I8aR8RO
ZuKwOOkIN4YtMnbgTBA49yTHqMMTyYtnhZEoWQEjm5oJEyDEBdx7y5VEbWuoC6sL
sFIPte16NINCTzO4rhM8Cqs/hPccJnskEM+V/8WsH/S4SLowfOpU8eT7hMtYdbfN
EWzfHuYGO4R2dfGm/EH5JwYKqTJ6qFjXCUNr6c0l7/C6jm7SJRDYZTETqKMAr8sd
ovNt0rl2to5rWwGN8T1EOLRMSDE5ODjmUrUtetYiNJPfYRvClAhT4S7dyODT3XfU
39G9AsVNn4VoGiQHFG4TsC2g5pkkiNa38r9c5WTBXlkPlfDbi/TbyhSRUJhTdgoZ
a7boLLR4spUZER5JiydTc44uXrLmmUMCebDPhp2rUfstimybnq2C7Z0GVrr3sRLc
hjC0BpYI8ENdoD5MrtwAsG8NpOr0O/m01IMhdBq0BR1iVkTb/DXasHEexe5JcPPZ
dOnHGdzkUH9oxycDLhZh4RIU+AEzWvdlmHOnLMnh50Y9EU4trUmgfOQYNvHy27S9
CT495KXws1pNSIwTo1+6sPgbJjVBvG9wrdOIU8A3E0Cwf/Nos6kfp8lrsIBbM7+g
xs2BitoWHxwZElEWiflFeYHSzwJuS8aeE/3ZsxjmBNwrFSx5ToCJU0nzmQ9CRphS
bPRKTekwmSBnk6MjZ58gvRXQSHB+oswWhWDowaqp8gBeBDzkajW9KN5Ccu0TOaj9
ya6Vd0WmBCK8iHyzWArL7wf59qb4htoA2Ynaa5vPEAbGgw1ZvJWUg1WqyPjjh1k8
tyDV7FL2V5Juu2ZaPQZv2DZdZLS49/zjWwF6/u4IOvU+Y2u/Aalulyh4U5J+PazQ
I46DXYdOgnJdctjuqiPreMfESqAZZ2hIEFxkepgkeMjG+3/kzeLbOHIurkRTBOs+
RYKjg+QeGzIenPqZtTfcbsE3WwJIvlQIFmcg4UsvvOY5YLwR2GX0FjoAKjkCnV8I
WBojTj0G9TsMJbNJvpBeLIuJ09Q2KCGw4f0EdgPxLZPlYt4U4j1m+emfGq2T6KM6
s9QkOZuSw2VpSjyUK7bU1UfeSdGanmwCrbJUJDz1nsEiLigNdvotKxKBk1Xuy8MW
ZP2RdZeZOG7kNmLHsurKPeD5kpTGVQo3DcLiL7wE/ksA3RKAxxvbnotUQyu5CsEY
TjCAfkRSVer7IbwFPJ2GOI18Q4WCKwXKVKpgD9+QvrXlrxDd1gncfip5ZJ0kZMUG
5gnikk+Qpi6GLB+SOQGB09dDb9YMy3bAjBluZNqvaqOm9bEMyCwdqxqBLyLGCXST
poWh8lI+vR8khG5ta7cn/FWI8xAEZfzl6ojsN3nhRNUm6QtTwRSwAcf4GOcxGJ2u
2Vk7z/MkvxkCcXsL3iXqBIYf1y17kV2LjbGPGB3qtRVaCwCioI+7n3KBSC19SRDO
k/VcuLxSC/+oqNkNksL3avujqbI0ZqraErdJvxl1H4C3VM86IQxC3YrFs5QBXbLZ
+/Y70PYXc7bjr8wVmgcJhDTxVXNarkxM66v9eINzzVuM0zlUqe91qFdEJ+yj/4xW
heSVUy2hpwj2uGXtOTJf2UZnmkIR1D30wdHemuCZFCkkO2QAL7MMQq3vjQkVZtm4
Ofl4TfvV7ickWFQ/RQzDfULQ6t0xf4rFGIUrATAEkZ1Q2NOKukyW6+VEBM9qyCZs
lZfzb+WpW7S65/rA6KJqzTyeaLmgoH6o++OB59iKMbp7cN52l8vTXN2Yls/TnwzK
PLxh59gC2CAZ+fNDLOqkdObODP165kd5c0Opl8qda9XlaCs8gFxNKP9yk+7lI0r9
erxRMFmYhiKyA1/0tQgDBpV/6XqIpih417HPzFT+q2neeVbzz/AhMsmkpdrpibIs
oz8sCZJnXOHUJilN2gV8XKszNiyvDvU9YqWpSW1YSGcWq9soc9PUzBSbl/tF59f8
udL4DGPgydidTT7kv/wrssprZLolj8RgvQSNoOKpBZH6NW7gnKwBjKgtUHuS1Nby
SEDL0/LdiOmo5h0TEgp/p/DfoWlJdORrQXcuZjOxK1EXWHcxKqpwcjOepGAc3Kqf
N3p1+xQCvX98l8ZvEtBTFIEOv/j7tCWUJU2G5wvGX1JKZJ6hoCn2TFqVp6nks0ew
aOPDOU9by9JzI1KP1Nv7wdBE6XQUeS94XKHNJ2rZUY0PCNuX3Dz/avCzLgx0mxgf
3ALtfRC39F6v7OXnOnUDWtaR6L++f2FsbyJ4Y0XoHH07gDys7WOVWTpXFXZon1FW
MdqVmElJe353HPM08wZM2tkUed8cxcUheE33ilEEpgKYWxdD/JHNBVf2qB/F7Arv
UN7eHBNG7Ad/3ScrpI5Tk9Wo1MjRxwiEQjStDeoRTWiPhTX2kAJQzn2TtWXpZy3E
iEXul8rAT4XXtOwvguQOJd2nBll8jj9hjN/7mFFr6F4bMulluOVTh/Gz3O8FoWb5
TI661AV6gOYoedozrwua9otRJ9Zn8SAUuCmXr6BReYfWDgPstNii38R8+MYxASEJ
7NR8Ga1FQGQ25DfkiL6eMo/2gbz2SEJjy/RIFjSxWUwA4OI7PrJEuGuHfe0FfweJ
6Lav+5R7nS0eHBljmIxz1FdeKdbod/9pR8cgWRhzZ3YkbWIi9ZzSkJgB/2D/pvZ6
v9l/5TfDmuhQdl15q3W3yfxxfGCOo0wgpBLZoCga20QG9tYN52zEeCgsMHdH0Grv
tURin1jJ8md9BhZqBX0pxhXEsZyuqgmT42ZX4cObzzVSbDfesqfNb6mFwSxGqt5c
UL+T+T2yZpstLL95HkdgMofIc2h3Qr8ha8nhyhAmcldN9djaAolTOF7EN2WcBUv9
z6iut8eId4w7jyuWoCSvdTl6acKvXjBoweI3g8nxr9E9jEut7GbTkL/Y9ztwx6/o
brD0XT8tBijbbsi4hEn/WXiGCKPYSlHkj/WTjzW2WS2de8yh1akPAqxic0809Mm7
6H+XNyVcusQWEMm6Alp3Z90qDj8zxclEvABb/iWvAyoGk4dXfo9cpQFdfYKI4n2V
8pQbPeH4rGi3saB0iXofi8Fmn4gkoEvVtRJ2x9AIAoVzBd0joPqfbi4NoO+mIS6m
Bv7WPESHJVFHcmt/QzItfP9UAimYAmdgL0RzO6Xj6A2DJ/3iJrYhod/CQCE0jIqA
ZyjMNMPk3aWM8hJZTLJ5xQjD094f6fP8HcJG1WxeY9Ce4hPIocomVHGWqbXaYYOU
T8fspg4lyZdUrBlnia7iwtm89lE1RQLfYMvsacDijyTV7Ry7NwLweI2B4wy/BCSi
3xwyyY9MBLaX0JFtbsV/YFaD9YTjgD2QXboQOYuyYWcAEQBLbEGGVcjIR7XvTSGo
BdTGv/dmWyvMUyA7RPHQmk59v980ro4wea7Do3eJ7oum++zI7JZzCgsjcoCgdw8T
GcE+tCd9ghe0yqHNOrbCjbtRLVryRA/GC8f2pnG6tugTFvWQUnetKKi/uvD7kQ33
5b652hz/yADa/14Yluqv8T9jTSQeUlIaECQzKMtnbCgnYBINJTHI/9jqRKucqpfO
hBW9ybORqeHk6JfFqMz7eOaabMQx+Px5XhJhTWf6MIECb1njJ/QYdMjwG/17Y5bn
p7Kk8On0fN6KYVd5ZFQhcVAWi9ds5SNXJG8ILJtegnnrhl8sVDUqMpFEIZU1XSbL
9YGvWHCMDJFWJX3RqZCIbTUGJouw4AvVOqmqIWxeOkrDfCB/j1C0Dqse8vGPh+yr
77uJiBaWlKDkNsxS84cYW6X7qfLvPVkUGWRg13varM1hX/Whn1q+9FcayQ/EsZgc
xiCy57pcb4o78TUetV614gY7ivJjd3laDminJhHyUY9rJCFC/HaEa88PQRms229C
c1LvymCBWCY8tF88R3aMKwMzUboPlytujGys2IoC5RJgf2nwIWe423d1sVikqy8z
SKmojZJQKFxMw2a/hMTq0qDWJeGa+zjwxKV+GfUnsAFG+C1wwGeIgByQXxWfm6kD
Ygte42KsvgbaI35D0KJ2vJuF3phXbr6UtRbynMQ8swp8A7sIdCcmc2J2ChgYPxw+
6dLips4SYW8O1ScSJ7CDs+3Mz5vErGkeVHLuSj4xg53h
=IQmu
-----END PGP MESSAGE-----

**Comment by winauth** [comment]
Upgrade to 3.6.1. There's a bug in 3.6.0.

3.6 is a beta release and should only be used for testing. If you are using it live, I'd recommend going back to 3.5.

**Comment by winauth** [comment]
Actually, the bug has been fixed but not pushed into a release yet. 

For now just create a dummy file called winauth,xml in the folder.
