### ISSUE TITLE
Get shared_secret and identity_secret with Winauth

### ISSUE THREAD

**Issue by rafaelguedes** [winauth/winauth#535]
Hello,
don't know if you can consider this an issue but any help would be appreciated it.

Is there anyway to get the shared_secret and identity_secret with Winauth?
I've accessed to a file with an object encrypted that shows both secrets but I tried to decrypt it from base32 to hexadecimal and I can't do what I want (configure a bot).

Any idea?

Thanks in advance.

**Comment by winauth** [comment]
If you are using a bot, you'll just have to use or copy the decryption code. Or, don't encrypt it, which can then be read and just decoded.
