### ISSUE TITLE
WinAuth Error, Method not found: 'Int32 System.Environment.get_CurrentManagedThreadld()'.

### ISSUE THREAD

**Issue by Refusek** [winauth/winauth#536]
-----BEGIN PGP MESSAGE-----
Version: BCPG C# v3.5.1.2

hQEMA53DDyNpqwwqAQf/fGCVq/4qTTc6ZK968oFk32iKVoHL+B/VjwVnjLqiBOSH
5E/pNgyqjAekATlxD0XyErhgJUlAvsmXCmARoeuWRhm8YXN08zX9kkEmZLR+H5eQ
XKF+WPpFL/yjOq+WOUbWp2fiZ3DGk2xCKSV5rZbGLDTou5X14Jx4Y7HgLYYECi43
Gp4k3jRumVI5B2+jn1JiGQhYDC45wMbOman1hjrsDHhkxmrryjhBuOPrRWRM/V6m
do5nzLG7qrZdT8MWzVH52O89coGJj54GkmzQ1ot8yOpM1w/d082W5Liq/ZTyEKEI
i9sKlHwZXTI1AD+pFngFQ2h3caeG4Kv7EoQGT+iY3tLNdwFYQ41j1CDw0P2BcXpB
jSre3t+fxhC+AaZo3xI6fAyoHGRKQpgvuKiOnFRlLnqWBB2Nf184m8vc6q8+x0nI
SxqWKQaiLsaOCxmqk5PIgyhvyGjZD2ALSrQh27FCmixJzl+WQ+aPS/rRQwYGCt6F
X1FTWA1C1wsKylEJNMxVBFBRxuIHkXkdNUV3LAKWIxqwLFxVRic6knRJaQXMZoBf
T6qyI/P31o8np8Aw6zM/otOHSldjdQ2158F3JrvhiUOlEhg6ZTa7TvY96s4DNewR
B7soYZsRbsxn5nmwp/82ZpeUKzw6+EG6WobNC9yzwrd/VUWirlvTQb8gasD0pkXH
3wdnlQ4UMHuODaaG6N68YyG3E6E2yj5+wIklQt5e+YH1/SU3JH6ZyYegeLl+klqh
gNensNtffrV+kfD9aZp1QYfx5TL8WQqOP5BpC+yTaPeN6j/R/7sG0x1jP6yNXXEq
R835fhCPW9TyTt7Cognxp48GuPijaUoN70S+FrdVbPWdcyB8+Bivh4wHkWGBg/lW
lK6ivXtSZAMvIxAGO6ooDu/n35jStzgVwA6Vol6vOXh37W9wdfAomOaLUiCPP1im
v0kei/DcswMkNHdLpHaO2B6EUif3ikyZhYKHtnCu+784L3A48pdAe1dGAl2g00/6
vjJYoms5w+ns2WhfKhHnwurpwQgCcqRYJEeyNlniMSWbOxq3hIu4Gfzdk4LcklrC
KaV832Hs2I4ye6BhHVD9JzqE4evaIo4Fs2CVag6/4wsulcn4NEacItvYULJSso5t
tJ11RNWnOHyADJQoBcWuAxO3wPu8NzcGWt6VFOQl2nIwIRSYYg2Ul7OUZ0Cai+5L
69yXVdPrCGCC7yNDs6eIAVzWtJ5yGWBDeX1XWPUUIo/BB/z0qSQR2ygvpRWBGuTu
Up2FbBgSWqAc3pB1NdKkWAYUzbyN5mROVldXPRDrPVzN1S8p1XgpwjqOzs60Nwjs
cBVkSRKyKhixjkK1RF3VxNODtP8srYKGGOMO0WuM2pxr+ZxIHf1X2nmBFBAb8VzV
dHej1oISPlK0qOCZ25J/vgF9JDTy8cTolwLTp+1cfIUObH3JYnv8yUNxpPZAqOR8
krypfVvNH6knZxJRMwu2Ll3ZVpJjVBKyGaFlkFqKYM4F9z9/5xZObywKJGby1W0h
9ts512fXAyjYssMpFx8YKUAAk/7y81xW7XRIWVIX2a/H69lXRbRUNXULVOT7+yr6
D5IAVb2y7daZNE046V0wRFKTSTj63iEHH0SJn92o5Eja4QQXmZpBLHGg+1NgG8Dw
nDVzse/MGOIUkpfipHnBxbnvjncxe6INbcX0sodrZx1fjZR9L1hJJQBF+4NlxqeL
lUHI7ERb91JxMyoLLlj2n5G8+iOyHRDkDZkjoNtmC1AUJvz0JFo/QPeMWy4asQTJ
gTlnWDAYsI4I8M4M7Rd3IZzQyLALQWx3Uys5V+TmNULbr8ZKJjo1oZq0ctKOTTYb
q0QsJb60yNQrXwZRAkCWpIY3VcJ1k4s84gJejOQjTbhtqVDN3k34ok3Si7mS0tkx
Pc9/FWuJmWrlngCfJwZ/ijB0QrUxb8tpKxRTk1fLiBetIxszAqWItQapV5een58r
gKNCgUip6E5QDa1vhxEunzcFkIxNPfLm/QTqPk12Rcd/oYd2X6inMziIdCRfuAoX
EDmhVrAIoyw8s79CySyYuErIo5sQFfMdFxmc7ysoan9Y7idCZG92wwNZD4Zam3aA
/7MzvgalKmAcWQ0m93olynHdaQvWHTYggwDL2DXV4um6Kz0WdtolPlqGVEKequsx
zhJpr4YnPcmd7XgD/tXYtm9ITfsZbIRP2cvM+JOGZ6Jrx2TWg7OUwZfPqbdH7Wx1
PDu0yeaIem0D0OV/U0cYdI9B0GIZhzMBfctcw8g441BeG5kOKOf8TSNge8ZvIC4a
dVq/U+GXuISKrnyZ98Z1iWD31z5iHwUij8nqa0kzefOK0P0BNuuHcvZ9KIhOBP5q
/nKrKt8C4qmpUxgpVIqTVfNBAHCgoESryN6RBlItVe62Zf1Y/1BVbWhtefYh2xwK
ua5wLweQ/Iz5Zu9UmQGyLk973jafGSzC65Rw6Klq3W8FlB07Ju8JSn8CYlZBFUs3
DMBlKANtCHofi2zLVOCAUU9PrF3mrcKoG6G7zKxNJfsuTW0Uv7+t5nuSUp8G4Ee2
yLAXh2U1USyMGz2SMvMT2glaR7GQO8p4PrzdhNpQ6bvL/oEc0z7Hxy6ZXNfwzBbA
DSdtbUVzPCMkGUhSIb4MbSkFXsI29WB9pxSpA6w6t6UHwwMdG4RE2LU9Rhwj45qH
oQfTJilGOwuxl9P5LQEqDM9lnK1GtywXa9J560ssqASO623XjbanUVjNBwLZbVcU
ND7u0NneZSUs1WHzBqsFyE1F1Iz9PeXo3dj8fDL63cpYEfJvaiIvVP8qpP0Ich1K
m+9xRjK5zbZUcM818VjQKbLgcJWkjr1l0UljINndy0U8BH4afZx2bjvYR7nywctt
2OQY1KoJI4n8xPMV/FaqBK0Qyexr2llxxVnxWt3t1mee0DwXDBqVubeJpm2j7TdP
iz/DGvK8S7XcekElWOs8vqiDFANqXVqpdoDHAg9Qxja2e4B7vIX094V7qtd1OtkO
2+qfAOMc+417UtZc7bjb0/EwPidUuqTArtCMntKuLw18FUGMyN+xpqXpIbnl0Yz/
EBA94YMJzgPDRMOm+2oRxnmy8x2kce2ZaELpk/2cw78oV2z7ZK15S5mTBLWNNUCz
cmH9mx3KTVCyI8UHkPIa27R+nmh9Jxq1LYz02TAbQRofvd4wxP1csjog7GCbQRwg
hXM46lPLSYQWoKXK57EE6gV0/HMXBByCtWiyuyfDMR7pSzKD4a7Y6yf726sB0/oN
NEgBn+kPW3Pw2CSXYQPHul48VpGr8AVXQDpFunH6e6LMVOb53UCZKP/rcfCQhbn3
EJ50eSi9oTBU/zSJ08N/rx6QGPs3yI0xnp3QGwM4plecEcGQgJnaTya8HnU6YqXD
syLIAuT+4qcjNVCtnMp6BkWA5S+hohFEV3gpyb9jg85UM1rXAAoZf3Ld22PA3Z2n
Pb/yiDltEIUuU3dUXZui0LXAb4l3Jo/fMmqsKrqTd6s0YA5YzE8N/Mbt59r1vvoD
byXnhr4YgT9a8nvtYC6SJddi0xPZnx/bAIBvvpZko4z1Nj7Ppc+OjR0O2Pmb5JKo
BpLFRX/pE488umrAHWqfGmFy8x4fQj7qTbfzaNlU+B6/gq7739Y32ySdnsUBpRVZ
AlP6UsTDPiNyGdTOcMfPiaTqAVMsxrEWmaHRbXx83uIBL99zXU+GBXlwCf/a9sha
pTiaVDn94qhBDz8seX0xoeyJtsaWVqBlu41nFBAMjl5MzfbVHSdZ3X3OBk4z+Dc2
Jmfs+mals/kYVwyERiURpO3z/DNUGS9y2h76wJTArI9Zs33+BW18q1+Ec0NUSH7s
KDvMouwL6Z9yOm6H4v3DrSUuhloYvgm2sCjoHbMCpOYJLviByrKkLQu4N6k3l4FG
yE4BP9uRy4lFDmEjHrLees7DM5kEx1ey/odRwas50QKLoyOT8bcBU2Fhk3XAKp+K
aysZ993L302TdmbgCPW37VNhlWmyet73YY2qxSGIeAmNFr/s6DWytOhKUEDvLt3x
1EaVrTlJfzTXqWiovU53M//guFMG7T3LPtSMdeZAT1kFV8mSg/T0DBUbIW2QYwuP
zDacoGBHptDsRO3iiTFn/dAh2XQa++wIsOqOyLvBdyIecouYP3/R0BPH7mUbJwdU
Yt/Tp/t07oHpwsVADBt8y6gB9AIPQbKdPVfCRkoZikPbilq29pYjTa5eU21AIY9y
bZlLFwgig8h2OseAAWC4krDIAsGtTZo9y1R1YJNdLg3y0xgdY62uWLolz/brsq6Z
MjwZ8tsOMEippBC5V5wGBkLAP6bh/65yrMc5+9XolnKHwyMoKN6mEhl3ZOMoQifF
c6eNmnOi0Q6WdvM/MhttM4Dqnt7bw0R6VzhCwy9XDgKfFITHhnvHHrDUbT3gC56T
C6qQpU9hdCW01USyl+cW0FFb2btC152Ji+hSzQ3NmUsbshKzuUD/eojj6hNjOQ6S
VSuouQnN+lJZQWvcOKXBfeDTGgJWDss2UEq75VaZLInAno1dNEXGxSoiKwbZVDvF
rMVRVVc7XaAvcnbr4qsX4qlj+fGzn6jUz+OYtu4gwg6gwQ/ImuW+BFyk9v+MULpu
eP53CSOblbVd78FgZdzEDg8y0qMkOrgcMF4s6BrttvqNR+NcknXgFWPpoOX8Da4K
l0APRjtl8Nts6bDpwRm8wt4lytdIoYAaWqkchYcA2t2tn+uJKRtDu6HjbhuLyHKK
XnN2qlt2qctjfHoxmOnKSCRb7ubpd1s9A7D72JoaEMcUVQR1NjE5EYaJsA2VIwRk
h+x9BEUehnOz2ZDy93fRdxk2+Ka9AUr7EWOZDOfJTE8FVCwQ10ztv2eOZTHV+aZi
BK5eNrJznb7Qy/PzRhxxne5h7pegMcMi13tO3Gubwz9WwjtNUQuQFsbx278gAt0F
WkDiY7apz1GDX1hgWTdXN2iNj3v4q7A0KoUk2SPgIl+S7PHidBPS9+/Ska9TPfIC
V6V6/x+cvm9r0npifndxr0nsW7+j21XFJJm4mMlQimB1S4PDB8n66zWx+QeADzH9
zGiaheKtKoO/O0rs2cgmtrbLlX/PP3NLn8LcJKS91MPy+fPY5yB5pw0RC3mDgmYZ
MDobLa0g7w7nIPYFFW3n3j+NUK19cTus/YJLY8abT7PW9I/jOnSP0A/7dFcUzQBX
SgLjEFBmHsOLLjAzVmH/KX5vGtRLLiAbSQ==
=QDWn
-----END PGP MESSAGE-----

**Comment by winauth** [comment]
Do you have .Net 4.5 installed?
