### ISSUE TITLE
New computer

### ISSUE THREAD

**Issue by rokkvi90** [winauth/winauth#539]
Hey. I recently got a new computer. I was going to install winauth on it so i could easily get my codes and confirmations for steam but i couldnt add steam for winauth because i had winauth on my old computer. What i did was that i opened my old pc and removed steam from winauth and then uninstalled it. However this did not solve my problem and i can therefore not confirm any trades unless i boot up my old computer  wich id rather not have to do 2-3 times a week.

Anyone know how i can use winauth on my new PC?

**Comment by winauth** [comment]
Export all the data from the old WinAuth using the "Export..." option. Import that file onto the new computer by running WinAuth and clicking the "Add" button, choose "import" and then selecting the file.
