### ISSUE TITLE
I lost account of WinAuth

### ISSUE THREAD

**Issue by lostinhell** [winauth/winauth#541]
Hi,

I had a similar issue to the person here: https://github.com/winauth/winauth/issues/384 and I was wondering if the devs could help me out. This is very urgent and if it wasn't such a big deal for me, I would never post here. I've lost access to all my emails and information, Google won't help me in recovering a thing and I'm basically royally screwed. I'd strongly appreciate it if someone could help.

Just to add, I do have the PGP keys and the registry files in tact like the person I linked above, I can post them if the dev is willing to help. Please.

**Comment by lostinhell** [comment]
@winauth you there?

**Comment by winauth** [comment]
Email them to winauth@gmail.com

**Comment by lostinhell** [comment]
Done. @winauth

**Comment by winauth** [comment]
Let me know if you're sorted.
