### ISSUE TITLE
Compiling

### ISSUE THREAD

**Issue by DeathlyLife95** [winauth/winauth#549]
I got an issue when I try to compile it throws winAuth.YubiKey.x64.dll is missing
And Authenticator.dll couldn'
![error](https://user-images.githubusercontent.com/9542984/31134504-e958f5dc-a827-11e7-8e9b-725ae31dea90.png)
t be found, on Net4.5

**Comment by winauth** [comment]
Did it compile the WinAuth.YubiKey dlls? Can you do them manually?
