### ISSUE TITLE
winauth invalid password

### ISSUE THREAD

**Issue by brdriac** [winauth/winauth#550]
sir why i cant login to winauth?
my password never change
please help me

thanks before

**Comment by Bibize** [comment]
I don't remember having put in a password on the winauth. Please explain to me how I can recover that password

**Comment by winauth** [comment]
Perhaps you changed your Windows password, or reinstalled Windows? This could occur if you had been using the Windows encryption setting

Regardless, WinAuth doesn't just randomly add a password.
