### ISSUE TITLE
Help me backing up winauth

### ISSUE THREAD

**Issue by wwickedseek** [winauth/winauth#552]
Yo, my winauth got broke, i found a clear .xml file
i went into regedit and copy the last key then i past it into a .xml file
But now it says
invalid data at the root level

What should i do?

**Comment by wwickedseek** [comment]
Here it is:

Version: BCPG C# v3.4.23.2

hQEMA53DDyNpqwwqAQgAt0s3vTqRiNdR3XW5bBjGnBV4/XTqL7rlk9GQGWaKeUYb
XehjTfqB1E4tGOcLEQ8OfDUYwF8BfyM9r4f1gZ2zIw8STT1dwaoCHBMSAFO4bnjX
Sh4L5yJIiPEr227ELhbhRWPhqVFjl1idmANtilc82ZxL+8pnxnOILwHRtb2eg4WN
kKNqhFo8ywJECNJwe7apy/Al08wC9VNSF0tAetnvxf+WThVjWZh0V0qf0OyPHnZ7
ct544luPIBvvGiOEslSpsld0+Ue73wpbPUrbKfV742EozD4lg5zV298gTR+nEs07
elfTvrR9M3U1tR+fVG6vZ/mnz0YZaALsANTfZej6StLCaQGtaUuOJRmF2FL75O3b
CmYlwMYRr2yW9IRetHCOT/5pyEG7bXuIWaMGTF/6vNJvH1ykCHkB1RM1vdrXy6rc
TMkKvui1nuCOvmw3x4CtFozbvqF30xwrI3/+bJ2TXda7cPt5V99DQWBg3PDXKNkd
5jr1LX/jmmwVccCSkY9N6G8LNlsJgsyyOaFD0fiMAEIK1gOm+VQD86c00lwou4+K
46PDrOLSdL7Oauj0l6NxgvuFEV9Zk9c0JvKUkcgGmmksUueL4fN8BoZp+djsVcgU
gPBQYi4ivj5bEOJwAXSjLDKebUgF1RbF/NC9QLrusOJulQFjjjyggzDMplyw9cYu
eX1CIgJwOoxiwuzQwFObLIWFwzguatlk3QDx+0123r8YP80Q71gwpG9aAs8KTY4x
Auk7wd00dIZ+5lXVOxjqGCHDJdBrhPvrTOjaR2YRhUCse/0en+xdMRPNYX+TjjSu
NcTpIs9WRHyjikwr+TqEJPk6GBGZrTWH0VcI1psxsrrlXHbPD0fkT1ZK+Soy7e0k
6PFBqfL0bLPkeTowy72F74FvYNXSnBbAIAFjG2Y1hN7O9Tp53ZHiFiZeREOjdYaK
gfg3i1yPXmTGe7HsiK17Sg8/xoXH/OB1KJreePUzWVFhbaZR4iuF7hud93K1p1bg
hVbYDZRxM5gzjSs8mKWNJ0orhalxcPuGPA6EDscwpZpS0AlkSgW/ulF2g7lCI7lk
vV+/My6AVSD3tDIu44XQjmU6eRDyd0k6Jc3ygvgkFgTtx+RG0CYaBqQGKvefa6hV
aXQgpGTpgZT+gJhQZb/PNQ8Gp5cfWCaUFh+oiHb24xb6FfpnfVmrQV/U5UWPIcWZ
iw7Qi8IJ0hHNBNtjToM59d9mGMAe/PbPJH1/n/q+9dczHnvdF8uE9nLINnHzS318
qIf92Ek/bhjARH288sF/EYa3GKbJTjSU+7yluZBf2OFoAvnkTLrRNI1dH84SfsUh
+gQPRsVpyT5U6ulIw6Rx9SFf5zRwdUYOTJOmkheB9DOisL2HuesogrgZDGdrFeWD
y95JUCPxwVh6rDQCsshdzf0dmDdFMYdZPrYj
=S1z9

**Comment by winauth** [comment]
Post your email

**Comment by wwickedseek** [comment]
tatarchenkozhenia@gmail.com

**Comment by winauth** [comment]
Send to you
