### ISSUE TITLE
WinAuth Password problem

### ISSUE THREAD

**Issue by Mark2001** [winauth/winauth#557]
I was using WinAuth as a two factor identification process when it suddenly started asking me for a password which I did not set, now I'm locked out of an account, I've contacted the business in question and they asked me to contact the authors of WinAuth. The problem now is that I have reinstalled Windows does this mean my WinAuth will not register with said account again. This is a serious flaw that this software can suddenly ask for a password which was never originally setup in the first place, how do I get around this issue

**Comment by winauth** [comment]
WinAuth doesn't suddenly just ask for a password. This in only prompted if you added one, or you had "Encrypt to only be usable on this computer" set and now you've changed accounts, hard reset your Windows password or re-installed Windows.

Open the winauth.xml in a text editor. and find the "<data encrypted="..." line. If you have a encrypted="y", you have a manual password. If you gave "u" or "m" then it is encrypted by your Windows account.

To recover, you need the original Windows account master key or the backups from the registry. If you've re-installed and didn't made a backup there's nothing that can be done.
