### ISSUE TITLE
Winauth recovery?

### ISSUE THREAD

**Issue by That3DPrinterGuy** [winauth/winauth#558]
I've tried the recovery guide, no matter how I input the pgp key it doesn't fix my winauth. Here are my pgpkeys I'm trying to restore/recover:

hQEMA53DDyNpqwwqAQf/XKdKLt5UcrYedLpW/mtZkzo4sSQPG2Ab9wpSitemDqpM
rAOIfFOZPMWfIexxTl/zUrTEvbhctJ8TBm6Zdu0fAxJUsVlNqrwZlUQQhEDeZnF8
LWybwtpMjJh5ftaZfX5V2R+xpOhiIAKU1ApkfX5vZhEA9qn4dxvHpKX1xLyANCCj
E5wf+PcW8EDHEMdpk7rizlnVic0BSby5g1/OBJAUycHjooSSDvyJ9oaurix6XDR5
kK+W34BX4cdkwL0cM0ggd6yYJ4taeyFnWI7/5Ey+Z5bodIyJNbAv9euE+kqufyT+
y7PcGuasqXUXvqCdziqXYwkhxb8dWTWmAvs8OeMGotLAwwFGGXyLbh7/RzgdNZAn
D/dTGNHiBk+cFzQVIxP+PcEvSps5Y2GqyC37ASlHg8HUv1Y1MQ6T7ylu0/IpUJr8
DPf07OEo+nxWrxawy32K3sjhpbW4Yc4nGL8mmX/gB9gocWSuBRNXjZ1chdj9/n5N
GknOrMA0AP25oQOAlok3WjrJva4bsu5Ge7wdEWUW30aWgOx8uMWC0l1gg39Fn45R
mp06rUW920/jsfIRju80FQ8O7VgDBAoWDlYTSfYfJGJw1RCW7MbFOxHXvDlRnJjU
tpVG/gcySfd93shNzIeb8zxEVX0ms11gt8EKkeVlH22RqsJo2ICuQ/LZK5JtVE7S
p1ZviZRGe5ukKg8fLtKxW431xs3EsV2m25pXXkueIP/sb8F+YGYy+v8InRv3cyCT
xRmen4QP/2bbsM7dFs3hG3jI2cGZR0uozqJB9z+Us91GMIFDx76EXAWV7AWrD09z
Yh3xmmbinEmW/Ndi6EceHJ3P/okCOq1z2UzURMSA/WofSHAFLw==
=V6FC

hQEMA53DDyNpqwwqAQf/Xga21M+SphGp7/uiTtK8XcJvo0bd7EVZYj9kiUZfHPIJ
Ry+v+BzZuV4QYTUveGUhMbBVqtC/K/KJ/u8pIepiyCn0REXlIgbGDTaOVpVmu7Wp
8fb2jKQNM3dGg42/UUFgyh1CD5dLY0O5z2Odubz68BaM1/Lq45EvBoCvf0WBpkhI
M1PUcf5IMcP3qPnwOvNsyImPxcDwKwGEirHc603EJkd7e4h5r1mSQKoYHYjxVcE4
fxypG6xzSC/N4ztNZ24c2UxJS/5myDmjk4CwZGu7sTAvf/FILZjrPe4dGVytxWMX
X72PHuW6NRyLWdcCZqQzIrWTNepcD5HY4u31CMcxWNLA2gGN5NoKIHTsJIu4rYm5
21nLFeRBLurXBPTGbCPC/dcmkkF5lu1UNwN7hq23Xj8tn5xdvulRHVyf+KSVDFHp
kqfoSzixweXX3x1gcNZG13nOFxRumsXpBD6irvHz8gkYKeci8l8zrEjVtebTEclG
K9GhY9yFVT1x9YFeV0NqlE6VV9+sj0xrC60OsAjqFWW1e2BBCNTUGlDGeuX/iJFU
3aoSpLtd8ngp7qmYfXMQEaMQZxv+a5GRsEm2rb7HsuOulPo0FG+sxwbPiqNuguod
iD6taz3LnfMSn9/SX0d7TRVSo7Y5k3KDiziBj/NZfc/A9l6ZCCwxofadWUaDwv4S
AGVdj8qHsJBSa/nxw2pjVpOk94Zwp4A5STtJG2SlnZo0iImfHL5FWey9aqRMTwhW
55YXkF/GfmLLaeIDw3U4iMxzioXSAysaeydSi/452Um8iayJ2xRFT/fbCb6V0A4I
N4Mnh6KWdpzOhAfC1K9KcwEnPdomr55fbFtbrZ15UDQ6PCWOIl+BJQBXIXqLGQ+5
6zuuXxvrocV9DtED
=L03N

hQEMA53DDyNpqwwqAQf/Ud/FUOf42vXSxN+jIKJF1EaKyxIy6fENC8JPR1dZ0zzd
jdFnzmfEgeFae+x06kP85SMMkcrio+Ha1oUCADNgtEsTBrN09IBU3WAIvc5IY3q0
ocj+G8s86/gg1CEAT9GeYt3v9H0v27wkVF+83lr8b8yd47doq2hGdn31SPzFQqZO
B85Vtam630egJzrwlk00PLQ5tfDoJygmgpep87IGWh3oj/SDXJB3J8KJueI6hFkg
Td3Aaa4rNRh/VdF4dBrZMhtmtylSQ+0yLUFtrgUUqZtBPQ85kC0Z5Tf/qW6Qle3z
dp52ifMWDJYaV80LMlgCncsHF9fAdzIvLhgmhTxEtdLA0QEMMFlvx+l4Jyu8h26v
bQlRXcHTFFGH+VsDqjMErg/IISC0AH4XkqYy6aR8jJGA+uFYrMkvpGXelxzfDfe2
JSndKb4LLrn5U/E324rVN1nolKsBbXIwQ75YQHKy/43xidSJ23EtVt2EInrGM8JZ
8D9OgpV0OybSbcqtzLuFfQIcjqaCKKFUt4RLuuc0/USjrg/9iEM4qSxtNLyX0Xbg
tIdvVANh52FLbi8B48a4tD2GLF3NS28Prk7FeAM5DldfryAlPVWUHLkhEJ71xS/K
aq57yehu5rgYzXhvsbq3KUhB2Ojo3GER8Ut91A7TRJFKqviHT0b2HV4pOab+0tmz
LmIKj8pDbV8eNztaORtUzU4Jo8T3W6eXv/k/ni7Bqzgm+WNSYBhYz6NwhdMQ8/++
p25bdJnk8PkSIRALQlFdSoYLpp2y2cBhXkNyEVZkjn6b0rPdNZ1ko8jVrdrxr92K
vraraIxDHwzTwG1KIz4Po0DCXq/A5abOmHkUbZhTvUZ2Af0sZG4uf5uh9h2lfkTB
f+n6
=Z4nv

hQEMA53DDyNpqwwqAQf7B8ItneSp35qLJgu3zfDtuwo7y8XXUpuTiXQNpQsFgtdf
SaU8bv1BRWd7dUNg7fBUU4VcLO6b0Db3WG1jzIoDmfiE1DRfTLRHzbcuxlAlb+LH
Itq53w30PiU50++CaG1Qj+/ZcR5i5jdtr9URuohm9d0EA3VBLRIbww9BapehmUeU
O6a8OHudkgek5hx5201utv+IcStaG8G2wkfNDPCAIvL4ILs703GMLQCbVZnHjDH4
IQEJGV+OiQGGlqCy4BvgCunbBlBB6wUdKr1XfnBhsU6V05V+WEk68Rtv0yYieKdU
YnzcLoRZoj8+JeTIMNf1ItyyjgHxZEG81kwRaOOLFtLCpgFxymxE+deBv1u58Q9M
aZOG1Bzvegch8uomJe4Q3FzSvfoYBnx3GJ93iVaFLyrgMHQjAXxgkMQAaRFfxFrM
PMCVo4qdo+YRdWCD31ElOtySiSHLm6PV87dCfC0nx/5M8eI0wS1JFu/OzUERDZlg
nznHbRYv3+iWzmWJKwH9WqyFMllQXRbzRXvXUX+r2y8cDn2tq2miLisWSiywHWKJ
vKJFjOcFykZ72oA0f23vkLtNtvVnCsv/YHMHMthP3mtx5y+wshh1zfkp2OYTo4qT
wivkQs4o2sJC0XahES7oVuThjFobkOa6ZjwaCZYjFm8SaNDaFQWmoIrd15Y3b8dN
BJ8Nc+izNTK9J8zTAyDb1XpND7BRwgHErzn4/w7Wy1uV6Qge4O8A8YfXPhdxXuvZ
RB6/azWn3/zrbNoW3oF6OS/iWJn7FtmZIoAIWzXiBA5IbmobFml8NumdS7yRgKFO
5lo/48ULsBS//GK9ht4auXZ8+pATindyFwxtwDBcTeLgXALS7xxZojRZagKIOuYb
InuGTY9M5nDo2kY0S3QatxZrkXjla/owWD2USn3W5L+slzSflr5BoV21PjifeDMR
iO0r5iyj30aXwLLYa5fV8lOWLtzedgJ+IzSMmWTZELtGfG7s2XxKaJ46pSfwG3NZ
0+LFfgS63luT9bQkjPNLDWgIkU/onn8SVxHYcbGloRV3jzwbTY/t1bivYABcARhs
xya2rZAjV3b4vnb+zz2LIucqLCl35BXy2HYUy9GfV940C9aAoSd3QsaXDAHRy+jv
JySjP5s3K/tdlmtjk50qUJ4F97A/jKprqmwdjhPuWdYDwXDc1UTQdewwKR/IAsih
q9FxQdEwSVjAn0KKK1Q/mGCqHRsX1WWrRUEy7hS27yjn8MXz47Z119gq6JnZMaWM
HLfHIib7bhChDiFbe8pq7/CXg1PFcOaw+lyKhDUuiy6JWgLM/zrcbMyaj17FkDD1
C8+ZsuL41GIobOpeMVPycyb6P+fTIp4F2elU/KVm4pgof9U7Xjr5sBp+dTDx/h8e
+9LGaGlCNgs9W1jJumPoVQyEESg2B5wVc4GPxV6ICtr2PCvLHzKTcfITE4BAFnh8
D+mdYKk16mSfHFEMUwOjIwYkFTTzpCJAF54zCMDkGqOn7YbvpQQ+Cg==
=JKD9

hQEMA53DDyNpqwwqAQgApLOUD7YrARk4zS+8adxPlBIPPIx9HOhmjUurCVMoPDEa
YXIHAF4UiurglrDHmSO5Ys0vKOr056/SaCRw3+RdD9DZTAOP2QOPBKuCo5q16zC3
HnpH2gvnNZUMcxObz0qt1vlp6d797nsi8TqVK48lktsiUhyc2KZLyOGbIpz59ShX
d9mMbQefOYI5NHuevdAcc9D7zEvlL0ruOM3ajGeT/+4aULDEQvukWrAV7Wf/Y5Jz
hkmcrEheEfM2MjZE5OH9ticpyf1ijlBccuSp96s6MGNjWO4uspF8vVkid5bsJy17
GOfiF3n/MxeSpZOb9l020I4qUvdpcy2mLwDkvtMsItLA7AEWa8lilEfK9EhKSroJ
5bpQ1ev4zbWzh8yseC9wxfcjJLmtkWKcWjqU8fSfKccRWgGOfVQnpw14FMJ/hr/K
2AMltUUcCDlzPj+BrglORkMqAS98/zyT5GauhOB64ZJ9bwG6bCSQoEM22d/XnLgM
yuCLmx5ONe9MyKxShLuXeCqfkfx4oKWY/P8PEk2PlAI0rqHKC12+qLQ2KUOuMvyW
VJsUAbHk/Xk2j+p4bDrQ8v5zvwELWbr7rlwmyLYeUB4j+MDpMKOzZQoqbqALOjo1
ZXr5xoVWZNNfmaLwheW/ulVwFibExtDd8NAYCuQ9beBpAPsV8tkJIQWR6XAcAFrc
VZ575mvbZZS8+TiqMiZlIQtlTylDab31M4FHZxMLx+NfM0l75xFNKHgbg8uG+N2M
4OFEn3apml8HP9iNuWQ2ZX5hYzCCo7XIiCRSNEI/O/4FKHe6eL5Yx/cvdy46KdFQ
HcIL862/aSbckX2jodpjvS/IqH/ilQK/7qtTvaczItdJokTSGhNF1ABpFGe6yY+F
CALsyzK+b9ZaWlbAFXTmIdHq3gBoXCQMY7OBMX4d
=Q20O

hQEMA53DDyNpqwwqAQgArnpUiRPDeZfovqhfEMgMP+fK2hrPQjAx6efEnF+ezdWs
EYZQFlcb0UhYtQ12bDH/OZrLx8J1TPQcKUnYjcdzbJxGrFqwA5Kpui7Tl6LIVToJ
cRXFHvki6TxRGcKEQ6W/XbcanKtc9zPxrVFG6FgVaQkPwC+DrIth0L5XLA5wrwov
9yxyNG7Lz75kC1EM467zztPjbo5ps0M/+tZiwZWaQVL07tQSwJEhzFFcBHee8Gez
AAexLFFMisAohL+EZGiYe6QMFGmnoaU+2nf29LLko7UTF/DYYirl0GJmIXGmTtAb
ng1i8yBkl/gnGGUxTZMTkfgL0GJxhj9AMfXJ4CWpCNLAwgFIXV49yK9H0MLeDr/2
n46ofFA+Me7/0fz2U7sUYVz+u2FxlJbBC0k3u5basJrhgwkNHK46AoaUUr1cEFBK
BLX/hqoho6Q98ZaHROSrucc98WwIGUEKV329UiQCzZAD4cy7IKxHwHb/Gsvj7FS0
6bcM16SECBAmdI3/eLG0H89C/uKljVHxXr9+Ednc2f3qR7rH37qebWvfNPJVjnW4
vjRDOrfJH9Qh+ML7s3dtRxTQ86fNkhh15ajpASoU8M+1SDEuXKFrvfmZKT9mZVdo
puHCFum9qFgZLDc2n5+O8P53noW0jN6SY14YnFpw1flwf3b5+lUzs/Z7iVjbhboz
3bl5ipTKwP831xPSBYmvEplDaCecqCeYcYxlbx+f/3RIIVxUwVvyvWiEHm+gRwE5
I2kXx3k8/frs/mGSGMcegokjrslZX2Go6R7WrIzmyHvrgjxkkLWgeecsIMbETzl2
uPKA7XQtK4WS05CMG5MOV6G66OPNlfz/lkZIBWiBeWNnVqsa
=2Qqm

hQEMA53DDyNpqwwqAQf/QnUEYk3H5XAeRMOvnnZnUaH2dmIadhIxyYSTvAueyJym
kX1cycLxN0DEO8Y4sVLe7Um7XUsWVndXVUnF42CZkqXZh+3OITZOaZcZDSld1poK
1SXWLcBLAF9JGUG2UTvyw07Uo/ArVHuvnX6GsHRe4+F+fb5X9vOqrnqaLr/KGpI9
RazRpY++g0KXfwxUmKXESmcYTNTfjlLugF3oerjI+r5o+vatqCR0EJurQXWs5TTg
MJqDVKHQ5mOgHwcobtyA8Cud1UfGgfoF0wzLsekDg55dNX8KmTwRtPppMbUdmEpg
HbmpPAQOdtvt3AAmcM69Dn+Xq3lnk8+0RISBBNjia9LAyAGxHuy+KnXs9SoRu+r1
fU7/sBumtnH/YTRuLv+hOnXua9hxcCRPn9ZHFc5QcRgm3NsA9g4XLtEbwiPxV+Vv
RqbZCf68xfeS4ZBN/Ok66PMwQj7f1sc72LG2bZlWavjdBSYBu8X1aMzag234WXUl
tQ2zHhyLtF4k/0sEn7lwt09CjqUvI7cDqLmdlVNEX7qYuSWY3lVn/Tx5zZHNhoYm
ZQAvjJ8XLMVfk1JEgOA/+FT1uIXvRmtFNw1tIjlLA319yPwrko8X1+x5xaB9IIBP
Xo4ELVXpUdiBYHOkE3dLXlT79V97EtcG7KCm9Gin6TyOrKrDaby1DBLUu5G4HaqL
T5y6kZy2Y+NChTEzO3qSKYglZelLPflVztRCfkX4sw4Haz0NqIaahZMiv6lMmPKo
602xPISORqBwquYNZtHiSYqKxp4WY9tGiP6+A2BzSYExclU0+EInvL9qI63TT+R3
/qz+ygSr3Rz8uqh/X23Ib1kr0kLMcGNoZV3yrzAt229x8Y507XVFwdIM
=NAyD

hQEMA53DDyNpqwwqAQf/XXtvEZjgtFsSW66Xn7Ca4AnRuxh02W6mpp6PsvTzWSz4
UHcpPq8AfWVTwGMLxddcYMI0ECz6Jc4/Z+S+iPHbUT6zBorJzLBff6jDhgoaUKze
uTcO4l945OryysoLO7BHZqOiyZY3vqOragy21wik8PoGGnRazvC2/tvqUFkEsLKt
pZ/KkGQaYAZZ50PizEBZotk6v4RzNVoLX7u7/zrE7U/i5pztF17f7lRpX4uzGRJ0
OVeUV1iEZVLK0R7HTjSNi7qJYqdmxfLwgZNCC1/HjSJGbTFI2AQ/RSjw51gOteUa
zCNWx1XSAPba442bsLcCOmHUXBAjGjmgqpHKKoBK89LAwQGUWpDiDQ/3IHLx+xTr
yaqWv5RjnHe3hJhPkVJttQ4LX3mQ4ZmNsCe1gOqmq+3JS//lMFk4Uxxeud72lMgK
hj/7yhG6sB7CQoDXdODuFWyDot2Pdyos+e89J8jBA6MmGYMokzF3cuWyJV5yOVMR
hXZGxuv74celr1QQB8Rm5TgyL2+BESGfl5rKiSl06GyZ5on9motVspc9iwHiOqYS
sBYtMZ99/YEpnck/G8/INmj1RxDtpxGMp6g9RYDq1t6BdTVMaedls67b9K48IUGH
D/M1FQiTFfpyLgzug02BO2IhGeCjQ/U/Zg3lFHMg+nOBWj6WS0RUeoXce+UucWZe
IAD/Hfeb2enhQOl6djeRgKCSUqiuvvs2UlXtjFd+yxBPdT7H8oyforWee2+E04WB
W4LL4p/n7+rDF8LCF+r5wt8U1OauksrdSoEUBi5qBsgbaDtE4/wBma86GpcrS/hS
7TxupDKtQuHbyVjKLwKXLM7BLvy4KKiKCzrBfUpinpjuLeY=
=PvY2

hQEMA53DDyNpqwwqAQf/VdjpbIbhwcH4hhmYMdqv1ufbCIjy3rdvVp6JW1iAkGHw
eIrINgOGaKqKLk07QP/MHJ/fF+vyuX4LQ99a9tegtyEL4EWWlRudjbdPK13CVHNU
JSHyRk2OuFglSz+rfL8GYOEBT3HGLvHOz5eI3f5b45E941mfuxG6gmJdlumUFLby
3tKb+Q4MksHLoL67xH2FnUGTEN+49Tx3+EulpxpOTsJx9Y+fMnXSye3tDbvfrFoG
bGuvxTJYTb0+cxlIJ6kInEWVUQWacAtdSBDJiAtl53uhtOyKjN1gaYBC6IWmxN0M
xTzwmd4YvYmKlB3ourwxxuMejfR6hiyuoyUJzliUkNLAxAGaQDBz7aUYjlttzoi+
fYRZ4gTfKk1s1fEb8OYCOmn5sUzrbq/zmWqNsMnz1Vz4Vb5Xxn9etb17OJKALuu/
UfLckpR++k6NoHe790KM6ry22ip7dJIXU87B39HygP7I3hYKzqA+UjB/aWJ4H0LX
9EQ3uV/H0aUzvHTHEY1WFt+3w96cmhlpvohxc1ChSdcM4gSplLs+8G2et40/DPxr
YrxmxU3y2RcESAKmLpWsQp1dGu6Fgfoh2IJFQeYSilhtuxbWldgfj10Wncd5eedX
bmjL/Djg/zxvu5UA84OKmlnGDKVjRtXpcjm+dBkrjaMrZrtgVwe1waIYX3oOgcMc
kAZJSsyHS4JOuJD8YLVt0OIeQ2pvYbpsrnIXdnU4W6H6333rr8wrKlXnbzlbSQhP
EOSHaxl2pK5MngxLsEcpziiRqKoG/R0GAmhQvfV070GhKmgKEzxrMkqLupglMc+R
neD+GDlg97HHxsL72tZ1NnJyGmbTfdSb+OKskPNMJY6Vy4qXnfM=
=yca2

hQEMA53DDyNpqwwqAQf9EInf9DNCKjxm0b8NihSvqB8WAjQ56ciquN81wQ9qn7Yh
A63yFoDQ4GGcshyvfBmJPXFgvJArAx5zKtG1Zl7sIfQOAQgfNaoDTpbBKDwHYbyD
vmVGGmrxbgrQ+ieuTEI0+nDUR3Oehy0aHQd0sF/rtLuOHrY/VE/fpUKQXSj7vKCZ
Qd8xj4Zad/JJW4qY0F+0+m9+qJIH2LfoQYpEpANhI/kQcrgjCudwbssc6zhex36W
SoG5T2El5ISIx7mW4UZTzoj+4hg/biysze0zlgMMKjA24nP4+m5GQbCAuE1KHGUF
Rxu5rKhfUgyjprMjxUoz3/9d8N91GJOSf8fAfLctjtLAvgGex2TVz3FM3/nfGJNG
jnGE9lT2FkhfsqAHbDqGQUfV+eKekYVhoW3t629zu6d0dqnG/3b2ixpZsx7kTdpo
Bxd3rsEi1hXiGzF07xFs6qxS36Xy8R/fKeGhzhJfNQIt5uU9z78TNaffKb3Y1A6d
bX6GTj8axluabuYZ5jdVhfIKFggoUy7C9sq/9PhCx35p7cX+hzFtyhdaFBxhfmTL
GLBsPG/BmdtWK1dDw+XE22oC8AMXYcka/wU9PT3J5Ka27YV1jFzDd4combqxSBSp
iKE2OwFDoHL5wgeE7oYUfUvhoM88+JxNcZOMQcr1pfJhf3oslvtu8BxZL5ZpFTww
10X91HUiZGZy4MNYv6mZMJyQqCer5cRnne9+pF0mU467Zfo472LK4FesDnrqMbUH
N7/93dG4qHczPrBNI2XUWbzXzB6MrHupcJbBsMk0TwAYY3KKrgvwnh/Fh18wVF+K
URbOFi3JCG6/1syiMF12SSAH0luqnE60Tl4zgHhYvIc=
=k+hY

You can reach me at Joe@**************erguy.com, Thank you Joe.

**Comment by winauth** [comment]
Email sent
