### ISSUE TITLE
I can't restore my backed up 2FA settings?

### ISSUE THREAD

**Issue by surashu** [winauth/winauth#559]
I keep getting this error when I try to import them.

![sketch](https://user-images.githubusercontent.com/12764163/31985042-3d0a8770-b996-11e7-935f-aa5d736cca1e.png)

**Comment by winauth** [comment]
Need more information. What are you trying to do?

**Comment by surashu** [comment]
@winauth I managed to fix it. Apparently, WinAuth was making a `C:\Users\Surashu\AppData\Roaming\WinAuth` temp file, and for some reason the temp file wasn't getting renamed to XML. I exited WinAuth and renamed it manually to `WinAuth.xml` and it worked. I don't know why it couldn't rename the temporary file though.
