### ISSUE TITLE
winauth gives incorrect codes

### ISSUE THREAD

**Issue by ingber** [winauth/winauth#561]
I've used winauth since around when it was first available.  I'm using the current 3.5.1.  Today it is giving incorrect codes.  I verified this against Authy and Android Authenticator, and my first clue was when it did not work for an application.  I checked my PC clock against other clocks, and it is correct to the second.

Yesterday, I did reset my PC clock which was off several seconds, and changed Internet time from windows to nist servers.

Is there some way to reset WinAuth?

**Comment by ingber** [comment]
I restored my exe and xml files from backups and now it is running correctly.

**Comment by winauth** [comment]
Glad it's working. You can right click each authenticator and "Sync time" that will reset the internal time diff correcting codes.

**Comment by eschulma** [comment]
It would be nice to be able to "Sync time" for all authenticators at once. I had the same problem after my PC clock was changed.
