### ISSUE TITLE
"Confirmations" greyed out (Steam)

### ISSUE THREAD

**Issue by xSil3nt** [winauth/winauth#565]
When I right click on my steam authenticatior, the confirmations button is greyed out, i cannot click it.

**Comment by winauth** [comment]
It would be grey if you hadn't set up your authenticator though WinAuth, where just the secret key was imported, or if it was set up before WinAuth added the confirmations feature. In that case you would need to remove it from your Steam account and add it again.

**Comment by BlueRaja** [comment]
Neither of those is true in my case, but it's still greyed out :(
