### ISSUE TITLE
MD5 password hash

### ISSUE THREAD

**Issue by IgelRM** [winauth/winauth#566]
Hello, thanks for this awesome convenient program.

I noticed that the hash entry in the `winauth.xml` is labeled MD5. I think MD5 doesn't seem like a save way to store passwords anymore. I hope for a switch to SHA256 or similar or an option setting to do so.

Thanks

**Comment by winauth** [comment]
The MD5 entry isn't used to store anything. It's just a hash of the encrypted data to check data integrity.
