### ISSUE TITLE
need help with winauth

### ISSUE THREAD

**Issue by Flashbeta** [winauth/winauth#574]
i used winauth on my guild wars 2 account...... after i changed my internet connection when i open my guild wars 2 account it asks for a code from my winauth ..... then when i opened my winauth it didnt ask me for password as usual it wants me to add guild wars 2 again and to do that i need to open my guild wars 2 account which is locked by winauth !  so i sent a ticket to guild wars 2 support to remove winauth from my account so i can relink my winauth with my account again .... but no response till now .  can u help me in any way ?

**Comment by beerisgood** [comment]
They cant remove your WinAuth, just your whole 2factor.

**Comment by winauth** [comment]
Sounds like you lost you config / switched users /reformatted your PC. If your secret key is gone and you don't have a back up there's not much that anyone can do. There is a backup in your registry, if you still have that we can retrieve the key.

**Comment by beerisgood** [comment]
@winauth Which registry data is needed?

**Comment by winauth** [comment]
https://winauth.github.io/winauth/lost-forgotten-password.html

**Comment by beerisgood** [comment]
Thanks i found all keys.
How can i restore them?
