### ISSUE TITLE
Unable to log into Bitfinex two step

### ISSUE THREAD

**Issue by Kistvaen** [winauth/winauth#579]
Recently my smartphone's battery stopped working and there are no replacement batteries in stock anymore. The Google and Windows Authenticator apps on my phone did enable me to log into Bitfinex and Coinbase. I am reluctant to buy a new handset or phone as I would prefer to reduce my EMR exposure and therefore move away from wi-fi and 4G. 

I came across WinAuth as a solution so I installed WinAuth v3.5.1 on my desktop. However, I am still unsuccessful at logging onto the Bitfinex and Coinbase websites. When the two-step process asks me for the 2FA code it doesn't recognise it. I understand that it might be to do with the time setting on my computer, so I changed the time to -1 and +1 hours, same result.

I would be grateful if you can give me some ideas on how to successfully log into these sites. I have already raised a ticket with them.

Many thanks

**Comment by winauth** [comment]
Right click the authenticator and choose "Sync time..." from the menu. Wait for the next code.

**Comment by Kistvaen** [comment]
Hi, thanks for the suggestion. I hadn't realised there was that option. However, it still doesn't enable me to log in.

**Comment by winauth** [comment]
The code does generate the right values, I use it on my own Coinbase and Bitfinex accounts. Restarting WinAuth will also reset clock. Are you sure the secret key is right? All I can suggest is to remove it and add again.

**Comment by Kistvaen** [comment]
I am feeling quite bashful. I don't think I wrote down the secret key from when I installed the apps on my phone. Or do you mean the one WinAuth generates? I have copied that. I sought how to uninstall a programme or app on Windows 10, but I can't locate WinAuth. Sorry to be a pain and ask such basic questions; is there a reference guide I could read as well?
