### ISSUE TITLE
Problem with "0" in URL

### ISSUE THREAD

**Issue by beerisgood** [winauth/winauth#594]
I want add the barcode image from a URL, but i got:
![winauth](https://user-images.githubusercontent.com/9625159/35173969-7117fa12-fd65-11e7-967c-b788e9ba4695.png)

The URL contain a zero (0) in the domain URL and it looks WinAuth cant handle it.
I use version 3.5.1 under Win10

**Comment by X-Coder** [comment]
I have a similar issue when I try to paste a totp base64 encoded image (string starts with data:image/png;base64)

I tried two different variants:
1. string length of 3858 chars works fine, no issues
2. string length of 5594 chars doens't work: gives above error and the chars entered into the field are invisible. Maybe its some kind off overflow in this textfield?

The only difference between these two variants is: second one is containing a additional image paramater, containing a URI, which is supported by other apps like FreeOTP and loads a icon from a specified URI.

**Comment by X-Coder** [comment]
Has this issue been fixed?

**Comment by beerisgood** [comment]
Nope but the Dev doesnt maintain this tool any longer
