### ISSUE TITLE
Can i import my authenticator from my registry backup ?

### ISSUE THREAD

**Issue by devprojectid** [winauth/winauth#616]
i move my winauth from my old computer to my laptop, i just have registry backup with PGP inside, can i import that ?
how ? 

@tycho @Elbandi @cdmackie @Efreak @XP1

**Comment by tycho** [comment]
You can't. It's PGP-encrypted with the WinAuth author's key, so he's the only one that can decrypt it.

If you still have the WinAuth XML file, you can import that. It should be in `Users\whatever\AppData\Roaming\WinAuth`.

**Comment by devprojectid** [comment]
i dont have access to my old computer.

regedit value it's like this 

[HKEY_CURRENT_USER\SOFTWARE\WinAuth3\Backup]
"SFIRdHg+mGn4WFtKuhBjEmaBHGx5DbPy79fff0e3UxM="="
-----BEGIN PGP MESSAGE-----
Version: BCPG C# v3.1.8.20

hQEMA53DDyNpqwwqAQf8C9a46T8jOEtVgpNQg2QcIChVf4I5r7+j8DCwbz566DOu
GpftZqdso7eYlytMgDg3+G45ptMjmi2Y1cuqQcIB85VBfN/Ahshs0WcNddj28n6n
p0FNWVGprII65rWuuEnsHdXTqj6L/krK/jAld7eAeDR/E0rAc6FXFzWAUN4d4vkJ
gXf5/11zSoWlOnYNiKHKSX1X6x7yJ9anL3S5T1inusxM151iiYU1lofnnU3qq+D3 -----

**Comment by tycho** [comment]
No, the registry value is not going to help you. It's encrypted so only the WinAuth author's PGP key can decrypt it.

**Comment by devprojectid** [comment]
ok, i check to my old Hardisk, and i found xml file in here Users\whatever\AppData\Roaming\WinAuth, but nothing inside, it's empty

**Comment by winauth** [comment]
Email me the registry data. winauth@gmail.com

**Comment by devprojectid** [comment]
i've sent it to you, thankyou
