### ISSUE TITLE
Authentificated my Guild Wars 2 Account with WinAuth but it is not showing it

### ISSUE THREAD

**Issue by Anetsecuritysucksass** [winauth/winauth#638]
Hi,

I authentificated my Guild Wars 2 with WinAuth a few weeks ago and now that i want to connect to my account it is asking the digits but when i open WinAuth it is only showing another account and not the Guild Wars 2. Therefore I am stuck since i cannot give any digits...

How do i proceed since i cannot access my Guild Wars 2 account now because of that ?

Thank you for your help

**Comment by Anetsecuritysucksass** [comment]
Please help

**Comment by winauth** [comment]
Did you save it?

If so, send the recovery information following https://winauth.github.io/winauth/lost-forgotten-password.html

**Comment by winauth** [comment]
You can also send it to recovery@winauth.com
