### ISSUE TITLE
please consider adding the Square Enix Software Token

### ISSUE THREAD

**Issue by wildsprite** [winauth/winauth#639]
at the title says
please consider adding the Square Enix Software Token(https://play.google.com/store/apps/details?id=com.square_enix_software_token) to Winauth
I'm not sure what this would take but your software is vastly superior to anything else and I hope this can be done.
note: I did try to find this in your issues but could not, if it is there please accept my apologies

**Comment by winauth** [comment]
As I remember they use a branded version of another token system, rather than an open-source implementation.
