### ISSUE TITLE
winauth recovery

### ISSUE THREAD

**Issue by entis47** [winauth/winauth#643]
windows defender (most probably) has made my winauth.xml blank. I've tried recovering it by using the registry backups and adding <pgpkey> in the xml file but it doesnt work. 

I've seen users here post their pgp keys to get it decrypted, i was hoping the same could happen to me. 

here are the keys.

-----BEGIN PGP MESSAGE-----
Version: BCPG C# v3.5.1.2

hQEMA53DDyNpqwwqAQgAl1Oy5WKn3yWLHnGjCxcqs/KjjNjYzjYjz2V9z6E8GtQA
zV9IQgcr5UL3wPygPELElRuzV+H+260DwuWVJfSVdnnntgTH7zgEhzB+U0s6Mskd
mHpD03r0rpPPe5ZFUoAHUZTGOup5otgMZ29xJ/qtUI/dbCmy38wGnPw4Wnuh8KnE
/mhg8wRp9Fz6Dk0VoWyjR2xlZTfWW7gefZ2CTQUcwSy2aB6s/4gBhge87H42mLgM
TrJm0Fd8A8rSY/grvPIV6VqM80V74X3884LwWCJ+fDVAqcSyl2KQiURTlI5Cy6Ca
aPseuucmhHgpJdetQE2JXuWXhQ90zwJaB9oG+7Ke+9LCjgHx8b88sgMZrUyImWsY
+nvarmmzJTEsuTyCA6/B4UTZu5naSurTDxIqF1ngsEQM2gGbVQw9kwQjFpP1kEMw
JMVFYbj2Vl881llQLNM56UcOeEizKNxzFOJ5FjN/ZLJz1bTmjlbUbDeL49Sa8Rv0
8fg8e/Cl4483RBivcdSWvx7OnrJQ0HJgFtu1to7nKS62heyAxbhzvTVNaNApO5c1
8spey0MgwXFgHsjq6mSCp24Cpfx189FXFFdClzJzm+jVBnJpkZRDzIQDeX57kCr+
aU3rS+VkuSSFvpEsFOntLrK597XNqj5c6WQjGlHIEy0cYzuFrArrwOMqrV9S6VLk
9wSWPQbPqyQotgARINpKX7Cbka+RODYZcBwXmEGXFzHwZehOu1G1FWJUFUrrLCOa
RH7798mn4KqnUULuKk1uhAYK6VmU8ek+kJU/tvW+WNx+RBC8kOmo+LFqHNCF9/pb
yBBbmCR0cyWc5JcvmstzJNVnkna+C++sRMu2bfFjYXtcfOGjdJA4oupz77EEv0Dw
AXk5Gwkv8ycpkdMY8g7VvjSRUOe9iWZPQ8cDJXdb+G2OAaQ6tFzzR+CwJ1BtgEhJ
PlEzJITMpWutGUJk6rYDVauVu7PgsI85kV4Z1ZaEXJy7/ei3o8GC2DJTHyUfNcWf
ES9CnFrcm/kmcD1gSLt0lOKCulMqaUOfYkrqySWCVWrmw7sdTzCZ3XGKp4C7WX+r
7tTnua4WJE6BK7YEnpo8iTjhovbzJhWbJ0oEcmmY/JzSLjJR1AtDwqgqPUn52XxT
ADQmgq8AVLHDQ6L/cgHzx+0C2UY4HeYF4L0MksV+mKkUabBlnuga7hgC00Plwk0P
IJjk0vUKfwynQyfj7eDj7M4DO3cPY6UxHxlhAkDF/lKyByD7uH+p4GDUOVTXD2Mo
4qUjUZ6fvFtGK7NCgbJwbbk3nr+HJnk0ooVvShE6586pdjiDbr/EANJiRF9dAt9h
2ehe1xqZVr2tYWB9njfmIMfgVhsI0hDL4+BJRAnOdaxycUcF0WYb1Ios2OzikzlF
8fe/i0nhKjxqs1cyL3P3bMs4FDJO898c3wIl8n1W4VzViA5mHOr8xWCtSb1NlTqa
7+8QgkkNXrt5IaLdO0jmlA==
=giwa
-----END PGP MESSAGE-----
-----BEGIN PGP MESSAGE-----
Version: BCPG C# v3.5.1.2

hQEMA53DDyNpqwwqAQf/QUc68a+EvOdU0v4yX1HHcOjSoAgvyPf/odAtPaDQ8sMj
9yGPvK/Qd9rsnx71w21wu++UHFE9jrzX4ASLcDt5x9NF6Dip1JWCnVteqy7KxsH/
XOJii3uWmhNcgbcN9l378lp4EvxgzeQUR6LpBew9Rb2/O0y6L4GBJKuO+SZxPDnf
FymKXI76PQkTq2Ncm4iRWd1fbSyNZ6jjz2tbRIYFNrL2ItWz4G+2w21tHh+BYfKO
LqVOtfqxa1Cve3McbNtnJPMGG9ldjQKLm44+HXgCjyhxV3zrL+iWLSVtw12gv84X
ob2Il9ZeclRcb/t2Jdgz60aR96F0OY9sWAIm0Us3h9LArgFh6aqTG3QL9nyc8Pqk
qwfoio+ZK6isyqCEH17YBCYh9pbOPq0LsjyMHR2gWzLGGvUXQOoWLmx+zgSkA/7r
vKeU4SwbX+L+p8ImGXvj8dzupz7J3YAx/izaSCtD6s/iccv5QrDWM0QaHi1FaejP
9qFDAtEhyeB0C6zjhGiVpmVNOm9CkQ6ZbvUxVEHHPL/qtOSa2EWv9iqpSqBNumGj
lRmbAza8xDFnG8QYpBlp0N2Kl+YpUTYeV0kRcivz3iaSCXdwYpXwjIQusUnMLx9t
tRgg6bFQQT2VTdDcjrOuy+TB7E1Ms4rm2Wh+xykKcg0+lle2AbEfI2JbIMQ3rRtn
teAmLJFvUkhUfrDFIm4cZyzg/dRbNlwvvFo++2XB+c8XfImPVEqqL4ALvnvmiq7x
MUw6457387ASBLoS9GhfAff6cT15wyzTPNffVx0TO8poUIFE6EEMzAlrimzGyrGL
antouHF3kDFQcNk86YqPQQ==
=Yx6b
-----END PGP MESSAGE-----
-----BEGIN PGP MESSAGE-----
Version: BCPG C# v3.5.1.2

hQEMA53DDyNpqwwqAQf/ffEM63KsO/xXsRrhpR3v0OoEi0iVQaF9UK8+NbLDR4Cr
8BOhRppbdL7454+AILkjvE/ufUu6MY7sdy2xZT4ER5poOFLj7K/rMMRq6e7Gvggg
cSkNPIOgWo0XkeAcTwJBGoxC4iczYGZOEYlIMFUJlfRBYEIKyfvgjOLG0+n+ig73
/PtUP/62TqDuTHi/61F440BjVn2lO7Sr8W8N3ZtbkYMDxf/CyeY2awCXtCyowmkn
fPD7UYbEqz3KO4ClKwcNKXbDVn5ActPC0UxKP5+9v+v3a2LBS0YXEt/y/axZZuOl
3ry6pIJScwexoqlZ50FS4xChOMSj2h2x0ts97KP9Z9LCoAGx2JAUNjybfqYzryMd
PDU6M57OiBAVtz0R3snM2+3pjOyg6YjnLIivlntqMLxEPs2BUvXwp322ujfOUwJs
LBHWaEnLtHPKqYyUicykpE4gvRya7iMER3++7NDjbBnYH6wlaO6La6Nd+0uXzvQA
vn1XnQiyMXGieDL0kvy9vcSyJZfEezayuW0PomSRJ4HQzulAV14tnnVvrxx1buXt
41fbx7OHH2Aa9e15VFR+bmnlufqVu4KRpvzGgae5o3kgtI404i1V7QLS54nTaL63
ugECXAbe56GGNbPZi0tE99FVxrTte95ox/Juax6V4kE8/OOAcf2Rec88nwvohGt/
/S61SnnElX493x5Bs7tW/D4lD5+n/c5Ddl4ze5Xd/jRGfVfDvijk0Pea9578IO/3
5uwXYp2/MeI3/9m/G/7QWv3/97y9hLspppjjs7ipUYJVcaI/vwOoAAuNMXGvj25P
XkkzqIqYagOn/dKbd7f6MWDcNVkyyNHSDcJt4+FG/avDbRMqbjYtMjeAexeDKiC6
sMlmy4Pxi6uHA3YUOLhOLJBBIrKS8J2sXkDidKuKlUx0c/c6DBdLJ/b7FP7/fFiq
cODjTbKtORIXrdHz4qwBhsMCdCHb2miBMPFY8LV9E5Bh+qK3CXo+T+/rwe0AEVcj
RcEueI4LeGXBiOt4GrcKiqrdI/rGxaOixcLMgTXV6QWI1KGOYx1e3+HGWmoXKm2E
gtkOWIEkQWRqfguOx+TBJRUqXIq7s60MWrdQXua7uCzNZeV4pslJputY5c8ehPtY
tMNRVf9wXPtkFKFKhD3JTIQmHDPQVfvzLu4ZreJIR75ocXLE9t6JR0fDEVcBElse
2W3D2ksaZJHOBS1f3hrxndyiyBn9QdhgfOOBBgRU9CpZV0faBx/DupdxcnKUIW3A
JR3VA2TMz7tUVO5EVMbWE5czwGmItCDpn189Yh32oxabZSp56YqcM9zhCegftqWZ
q7PSOObL1orynI7Hlu/GyNw/zCDJ4xlxje5hFfVAFUSNEG5qAvzOIwMkiYhYFkip
uYQMH7UjNBbjGIK6YufCBoCA0i6nXkK+0hqQfAjmlZnGLqmX/kVqEZ68DRZDGjQu
GrqRrAkrp+BTPfw0MDTj9EiBKhpAHLrT9Afq9V4/+R4rEg==
=jR9B
-----END PGP MESSAGE-----

**Comment by winauth** [comment]
Please provide your email address

**Comment by winauth** [comment]
Or better, email it recover@winauth.com and it'll automatically get sent back.
